### ISSUE TITLE
Import-D365Bacpac  Failed

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#106]
Hello Mötz,

issue when using Import-D365bacPac

due to passing databaseName to Set-AzureBacpacValues to exeecute SQL Command (whereas you need to send the NewDatabaseName )

Successfully imported database.
VERBOSE: [14:29:52][Invoke-SqlPackage] Total time spent inside the function was 01:04:03.8207957
VERBOSE: [14:29:52][Import-D365Bacpac] Importing completed
VERBOSE: [14:29:52][Import-D365Bacpac] Start working on the configuring the new database
VERBOSE: [14:29:52][Import-D365Bacpac] Building sql statement to update the imported Azure database
VERBOSE: [14:29:52][Get-SQLCommand] Building the SQL connection string.
VERBOSE: [14:29:52][Get-InstanceValues] Execute the statement against the DB instance
VERBOSE: [14:29:52][Get-InstanceValues] Extracting details from the result retrieved from the DB instance
VERBOSE: [14:29:52][Get-SQLCommand] Building the SQL connection string.
VERBOSE: [14:29:52][Set-AzureBacpacValues] Execution sql statement against database
[14:29:52][Set-AzureBacpacValues] Something went wrong while working against the database | Exception calling "ExecuteNo
nQuery" with "0" argument(s): "ExecuteNonQuery requires an open and available Connection. The connection's current state
 is closed."
WARNING: [14:29:52][Set-AzureBacpacValues] Stopping because of errors

PS C:\windows\system32> Import-D365Bacpac -ImportModeTier2 -SqlUser "sqladmin" -SqlPwd "xxx" -BacpacFile "C:\Temp\AxDB_REFERENCE.bacpac" -AxDeployExtUserPwd "xxx" -AxDbAdminPwd "xxx" -AxRuntimeUserPwd "xxxx" -AxMrRuntimeUserPwd "xxx" -AxRetailRuntimeUserPwd "xxx=" -AxRetailDataSyncUserPwd "xxx" -NewDatabaseName "Reference_db80"  -DatabaseServer xxxxx.database.windows.net -Verbose

**Comment by Splaxi** [comment]
Hi Charles!

I see the issue based on the issue you reported. Expect an update in 15-20 minutes.

Will ping you on twitter ;)

**Comment by Splaxi** [comment]
Should be solved in 0.4.65

Will be released in 5-10 minuts from this post

**Comment by Shind44** [comment]
Work
