### ISSUE TITLE
Import-BacPac

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#112]
When importing in Tiers2 environnement it missed a SQL script part to reenable SQL Azure context

update sysglobalconfiguration
set value = 'SQLAZURE'
where name = 'BACKENDDB'

update sysglobalconfiguration
set value = 1
where name = 'TEMPTABLEINAXDB'

if not we have error when synchronizing the DB
---> System.Data.SqlClient.SqlException: Reference to database and/or server name in 'TEMPDB.DBO.T_TRVREQUISITIONLINE_89D1D5091B9D4913861F8296525E9983' is not supported in this version of SQL Server.

**Comment by skaue** [comment]
Looks like the file has been completely changed over time. This part should obviously be in the routine. It must have fell out at some point.

**Comment by Splaxi** [comment]
Those things already exsist inside the `Clear-SqlBacpacDatabase.sql` script and for `Clear-AzureBacpacDatabase.sql`

So I don't quite understand that it would fail.

But I know that you have faced some issues Charles, so maybe the export didn't run the desired configuration.

I can live with us setting these things on the actual import as well, just to make sure.

**Comment by Shind44** [comment]
Mötz,

you right, this is called on New-D365Bacpac across  Invoke-ClearAzureSpecificObjects

but i think there is an issue here because when i have create the bacPac, I specified -ExportTiers2 and it seems that the script apply exportTiers1 mode

i need to make more tests to reproduce this issue

**Comment by Splaxi** [comment]
If you did a 

`New-D365Bacpac -ExportModeTier2 `

and then imported that bacpac file with 
`Import-D365Bacpac -ImporModeTier2`

That would explain the issue.

I believe that we should support that scenario, but at the moment we don't and that is why you hit an issue. Let us simply update the scripts that is run against either SQL or Azure, after the import. That way we don't care about where the bacpac file was exported from.

@ITRasmus & @skaue What are your thoughts on this?

**Comment by Shind44** [comment]
Mötz,

yes that the repro step, 

i do 
`New-D365Bacpac -ExportModeTier2`

and after
`Import-D365Bacpac -ImporModeTier2`

Why :
to upgrade (8.0 to 8.1) the Tiers 2 box and keep the same Database

but normaly that the last time i need to make this action, next time we will upgrade environnement without reploy it (April 2019)

**Comment by Splaxi** [comment]
Oh, I forgot to mention that we actually have a working solution for this.

New-D365Bacpac -ExportOnly 

Import-D365Bacpac -ImportOnly

This should be the way you do it, when using the files as a backup / restore in a Tier 2 environment

🤘👍

**Comment by Shind44** [comment]
👍 Thanks Mötz, i close the issue
