### ISSUE TITLE
Import-BacPac with or without TrustedConnection

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#113]
Mötz,

Import-BacPac on Tiers1 do not work with or without TrustedConnection when we try to import bacBac on a non D365 Environnement (Pure SQL Server server without any D365 component)

PS C:\Users\ccoadmin> Import-D365Bacpac -ImportModeTier1 -BacpacFile "E:\XXX\BACPAC\AxDB_REFERENCE.bacpac"  -NewDatabaseName  "XXX_AXDB_REFERENCE"  -DatabaseServer "localhost" -verbose

VERBOSE: [12:35:20][Test-PathExists] Testing the path: E:\XXX\BACPAC\AxDB_REFERENCE.bacpac
VERBOSE: [12:35:20][Test-TrustedConnection] Capabilities based on the centralized logic in the psm1 file.
VERBOSE: [12:35:20][Import-D365Bacpac] Testing if we are working against a Tier2 / Azure DB
VERBOSE: [12:35:20][Import-D365Bacpac] Start importing the bacpac with a new database name and current settings
VERBOSE: [12:35:20][Test-PathExists] Testing the path: C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe
VERBOSE: [12:35:20][Invoke-SqlPackage] Starting to prepare the parameters for sqlpackage.exe
VERBOSE: [12:35:20][Invoke-SqlPackage] Start sqlpackage.exe with parameters
***** Argument 'TargetUser' has an invalid value: ''.
*** Argument 'TargetPassword' has an invalid value: ''.**
VERBOSE: [12:35:21][Invoke-SqlPackage] Total time spent inside the function was 00:00:01.0308910
VERBOSE: [12:35:21][Import-D365Bacpac] Importing completed
VERBOSE: [12:35:21][Import-D365Bacpac] Start working on the configuring the new database
VERBOSE: [12:35:21][Import-D365Bacpac] Building sql statement to update the imported SQL database
VERBOSE: [12:35:21][Get-SQLCommand] Building the SQL connection string.
VERBOSE: [12:35:21][Set-SqlBacpacValues] Execution sql statement against database
[12:35:21][Set-SqlBacpacValues] Something went wrong while working against the database | Exception calling "Open" with "0" argument(s): "Login failed for user ''."
WARNING: [12:35:21][Set-SqlBacpacValues] Stopping because of errors
PS C:\Users\ccoadmin>

when we cannot specified sqlLogin and SqlPwd because this parameters are only included into -ImportModeTiers2 parametersSet

**Comment by Splaxi** [comment]
Hi Charles,

I understand why it fails. 

We are back at what we are trying to achieve with the tools. From my point of view we are trying to help and assist with most of the documented stuff that we have to do during a project. Getting bacpac files in and out of Tier1 and Tier2 environments are the real issue we aim to solve.

That said, I can totally understand that having the tools at hand, it would be convenient to use them for more than just as planned.

Questions for you:
* Where did the AxDB_REFERENCE database originate from? 
    - A local Tier1 development box?
    - An Azure hosted Tier1 development box?
    - A MS hosted Tier1 development box?
* What do you plan on using the database for on a non-d365fo box?

I would recommend you guys to look into that dbatools.io powershell project. They have all the tools for standard backup / restore of SQL Server databases. Taking a AXDB_REFERENCE database and convert it to a bacpac file doesn't make sense, from a performance point of view.

A solution could be to have 1 custom SQL Script that generates the backup for AXDB_REFERENCE from the source system and 1 custom SQL Script that restores the backup into the receiving system. That way everything was done from the same tool, if that is a requirement.

**Comment by Shind44** [comment]
Mötz,

Where did the AxDB_REFERENCE database originate from?
**> A MS Hosted Tiers 2 environnement**

What do you plan on using the database for on a non-d365fo box?
**i want to import the bacPac every night into a SQL Server instance (Standalone Server)
after bacPac is imported i can backup the DB with SQL tools (to generate .bak) file and so deploy it into DevBox as need with less downtime as possible

.Bak restore process is really fast compare to bacpac import

so the process is

----------------------------------------------------
> MS Hosted Tiers 2 
     -> BACPAC EXPORT
     -> Upload to Azure

> CHARLES HOSTED SQL  
    -> Download from Azure (bacpac file)
    ->Import BacPac 

> CHARLES HOSTED SQL 
     -> Backup DB to generate .bak file
     -> Upload .bak file to azure
----------------------------------------------------
> DevBox (to refresh environnement on demand)
    -> Download .bak file from azure
    -> Restore database
   -> Synchronize D365

and after restore automatically bak file into Devbox or Tiers 1 MS Hosted environnement

and for sure, this SQL non-d365 box is multi customer so multi bacpac import and sql backup will be done each night
**

**Comment by skaue** [comment]
I create the bacpac on Sandbox, then upload to cloud storage, then download to a DEV (with D365), then import bacpac. I then optionally create bak, and upload bak to LCS or to cloud storage. 
I never go through "my own" SQL somewhere.

**Comment by Shind44** [comment]
I create a PR to allow specify sqlLogin and sqlPwd when use ImportTier1 mode (non mandatory parameters)

**Comment by skaue** [comment]
Assuming you can authenticate using your current Windows credentials, the SQL credentials shouldn't be necessary. I thought the cmdlet permitted sqluser and sqlpassword, and in which case it would ignore "TrustedConnection".

**Comment by Splaxi** [comment]
We **might** have som core logic that simply look after some details on the machine and determines whether or not it is a Tier1. That is used to validate the trusted connection setting. I say **might** ;)

I see the PR from Charles.

On one side I'm ok with opening up for the use of SQL for Tier1, while on the other side I would like to keep things as they are. The reason for that is that we don't confuse people that much, if we can keep the Sql parameters to Tier2 only.

**Comment by Splaxi** [comment]
And Charles pushed me enough to bring in the change....

@Shind44 all issues with this will be blamed on you if other people get it wrong.

Please help me making sure that people don't use the -SqlUser and -SqlPwd on Tier1. So whenever you see something like that, let us promote that it shouldn't be necessary.

**Comment by Shind44** [comment]
Mötz,

you need to believe in people do they know what they do :)

however we can add additionnal PSF Message Log if we detect this context to help people 
or add new OutOfBox mode -ImportOutOfBox that made exactly the same action like Tier1 but with a parameters Set witch allow to use SqlLogin and SqlPwd

it will be more safe

**Comment by Splaxi** [comment]
I'm in to believing in people. So let us just keep things as they are :)
