### ISSUE TITLE
enhancement : Import-D365AadUser

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#144]
Add users to a specif group when importing them (at least allow user to be added automatically into the Admin system role)

**Comment by Splaxi** [comment]
The current solution will replicate what the current ADMIN is member of. So if you make that account member of any security role, the new user should get the same security role.

Could you please share some details?

We are very hesitant on extending the current format for importing users. If you need something beyond the current implementation, you could look into the d365.integrations module. It has a working sample for importing users and should be fairly easy to extend to handle security roles also.

**Comment by Shind44** [comment]
Mötz,

the goal was to import user and add it into a role

Actually, when we use this command user was created into the DB with only the default "User" role

if we need to add others roles, we need to go manually into D365 UI interface and foreach new user add additionnal role; not easy to automate this process

**Comment by Shind44** [comment]
Mötz,

I close, i try multiple times since i open the case and that's work as expected
