### ISSUE TITLE
get-d365instancename bad function call

### ISSUE THREAD

**Issue by Zechman** [d365collaborative/d365fo.tools#169]
get-d365instancename function call "get-d365environmentsetting" and function correct name is "get-d365environmentsetting**s**" .

also get-d365Url has the same problem.

This is a big problem for functions like  rename-d365instance

**Comment by skaue** [comment]
True. The method is referred in singular and should be plural.
@Splaxi quickfix? 
https://github.com/d365collaborative/d365fo.tools/blob/ec56b0f2ca96765a5ce6badfd690c4c4f7dfc4a0/d365fo.tools/functions/get-d365instancename.ps1#L28

**Comment by skaue** [comment]
I've added a fix for this in the following Pull Request:
https://github.com/d365collaborative/d365fo.tools/pull/168

**Comment by Splaxi** [comment]
Should be solve with 0.4.94

**Comment by Splaxi** [comment]
This will be closed due inactivity. Please comment here or create a new issue if you still face the same issue.

**Comment by fwilkinson** [comment]
I am using 0.5.26 and I am still getting the "Get-D365EnvironmentSetting" is not recognized issue when trying to use "rename-d365instance" command.  As mentioned above, it looks like it should be "Get-D365EnvironmentSettingS" (plural).

**Comment by Splaxi** [comment]
I'll give it a look!

**Comment by Splaxi** [comment]
I just tested with a clean onebox / local VHD. Removed all previous versions of the module, and restarted the entire environment.

It work flawlessly.

@fwilkinson Could you try and use this gist, to have a helper that removes all previous versions.

https://gist.github.com/Splaxi/dba292d41841a60fdb1c4f3acca71f40

Copy&paste the function into a powershell console.

Run the following command afterwards:
``` 
Uninstall-ModuleOldVersion -Module d365fo.tools
```

**Comment by fwilkinson** [comment]
I reboot seemed to help but now getting an error after IIS stopped (running rename-d365instance -newname “test”:

Set-Content : Stream was not readable.
At line:3163 char:57
+ ... (Get-Content $File).replace($OldValue, $NewValue) | Set-Content $File
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Windows\Syst...tionHost.config:String) [Set-Content], ArgumentExcep
   tion
    + FullyQualifiedErrorId : GetContentWriterArgumentError,Microsoft.PowerShell.Commands.SetContentCommand



Ford Wilkinson
Director of Cloud Services
Phone: (970) 300-2428 | fwilkinson@soprissystems.com<mailto:fwilkinson@soprissystems.com>

**Comment by Splaxi** [comment]
Could you share some details about the environment that you are trying to rename?

**Comment by Splaxi** [comment]
Hi,

Just wanted to check on the issue.

We'll close the issue 10th of June, if no further development has been made.
