### ISSUE TITLE
Implement Enable-D365User

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#17]
Implement Enable-D365User

Please implement the ability to streamline the re-activation of an environment after database refresh from PROD to sandbox environment. We always have activated the users by execution SQL-Statements like this:
update userinfo set enable = 1 where ID = 'sys-ax-batch'

To get a similar “interface” for this new functions as it exists Update-D365User I would suggest to use the same parameters. So an sample call would be:
Enable-D365User -Email "sys-ax-batch@contoso.com"
Enable-D365User -Email "%contoso.com%"

**Comment by Splaxi** [comment]
Great idea!

Will do it doing the weekend, we need it on Monday for our own project, so nice suggestion 🙂

**Comment by ITRasmus** [comment]
Fixed with commit b61275b496696a3bd685165a11e89902f3c7dfc0

**Comment by PaulHeisterkamp** [comment]
Nice! Thanks a lot!
