### ISSUE TITLE
Enable-D365User broken when table USERINFO has triggers

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#170]
The method fails with the following error if the table USERINFO has triggers.
The target table 'userinfo' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

The method and logic needs to be rewritten, something in like outlined here:
https://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table#13198551

**Comment by Splaxi** [comment]
Should be solve with 0.4.94

**Comment by Splaxi** [comment]
This will be closed due inactivity. Please comment here or create a new issue if you still face the same issue.
