### ISSUE TITLE
Customisation Analysis Report Issue

### ISSUE THREAD

**Issue by taral1311** [d365collaborative/d365fo.tools#173]
While running the command for on premise environment of d365 getting error for Module does not exist.

Any suggestion for same?

**Comment by skaue** [comment]
Can you copy the error (text or image) and paste in here?

**Comment by Splaxi** [comment]
@taral1311 Could you please share some more details for this issue? Otherwise we will close the issue due to inactivity. You're more than welcome to comment here or start a new issue with more details.

**Comment by taral1311** [comment]
I got solution for my error.

Please finnd below my command

C:\AOSService\PackagesLocalDirectory\Bin>xppbp.exe -metadata=C:\AOSService\PackagesLocalDirectory -all -model="ISPLEXIM" -packagesRoot=C:\AOSService\PackagesLocalDirectory  -xmlLog=C:\temp\BPCheckLogcd.xml -module="ISPLEXIM" -car=c:\temp\CAReport.xlsx

**Comment by skaue** [comment]
Without the error, I cannot be sure. @taral1311 didn't provide the error, and the "solution" is not really solving it, but rather not using the PowerShell at all. Only parameter not provided by New-D365CAReport is "packageRoot". I believe I was able to run the command without that parameter, but I will have to go back and try. Adding the parameter should be easy, though.
