### ISSUE TITLE
Implement Start-LcsDownload please

### ISSUE THREAD

**Issue by ptuerk** [d365collaborative/d365fo.tools#190]
I have to download backups from the LCS from the Asset Library at regular intervals.
Please consider that all backups have the same name and cannot be identified unambiguously by the name.
The last backup interests me, that would be the default behavior.
An exact identification via the timestamp of the backup would also be great.

**Comment by Splaxi** [comment]
At the moment Microsoft hasn't extended their API in LCS to handle that scenario. The reason for that is that LCS needs to redirect the request for the file download to blob storage account and create a timebased SAS token. From what I know, that doesn't exists just yet.

But with the module you are more than capable of build you own solution that can assist you with that. 

If you rely on the "Export Database" feature from LCS, then you still need to do some manual work for getting the file downloaded from LCS.

So either create your bacpac file with the module on the desired environment and use the cmdlets / functions that are available to upload and download files. Or simply have someone download the file and upload it to a blob storage container and use the module to download it on other machines.

The 2LCS application, also open source and available here on github, could be of interest for you. It doesn't have the required feature, but the maintainer behind might be able to put something together.

**Comment by ptuerk** [comment]
Thank you for the detailed answer. I love this tool
