### ISSUE TITLE
Run as Administrator

### ISSUE THREAD

**Issue by ITRasmus** [d365collaborative/d365fo.tools#2]
Functions relying on sql user password from AOS configuration, requires to be run as Administrator.
Functions should validate that a password is specified when it isn't running as Administrator

**Comment by Splaxi** [comment]
This should be fixed as of 0.3.8.

Example of implementation. Look at New-D365Bacpac.ps1 for real implementation.

if (!$script:IsAdminRuntime -and !($PSBoundParameters.ContainsKey("SqlPwd"))) {
#The script didn't run elevated and didn't have the -SqlPwd parameter set.
}
