### ISSUE TITLE
Invoke-AzureBackupRestore fails

### ISSUE THREAD

**Issue by Splaxi** [d365collaborative/d365fo.tools#221]
Hi guys, 
Hope you're doing well. 
I've used your tool before. And I like it. 
But after updating to the last version, the script was stopped working. 
I've received the next issue, and I can't solve it. 
[Invoke-AzureBackupRestore] Something went wrong while creating the copy of the Azure DB | Exception calling "
ExecuteNonQuery" with "0" argument(s): "CREATE DATABASE AS Copy of  operation failed. Internal service error.
A severe error occurred on the current command.  The results, if any, should be discarded."

_Originally posted by @vzugravyi in https://github.com/d365collaborative/d365fo.tools/issues/65#issuecomment-474052491_

**Comment by Splaxi** [comment]
Hi @vzugravyi

Your issue was registered under an old and already closed issue. I copied you message into this issue.

The error message indicate that something went wrong on the Azure side of things and not in the module.

You have 2 options now:
**No. 1**
Try a see what error / exception details can be found in the `$Error` variable.
Simply type `$Error` and see what it returns. Try `$Error[0]` 

**No. 2 **
Try and rerun the cmdlet / funtion again, this time with the `-Verbose` option. If it fails again, you should try and see what details are hidden in the logging area. This can be done with `Get-PsfMessage` -Level Verbose

**Comment by vzugravyi** [comment]
let me try. 
More details. 
I use the next statement. 
`New-D365Bacpac -ExportModeTier2 -DatabaseServer "skg-test-appdbserver-932330d.database.windows.net" -DatabaseName "sskg-test_axdb_23sr" 
-SqlUser "sqladmin" -SqlPwd "2018dsdss" -NewDatabaseName "uat2devdb" 
-BacpacFile "D:\DB_backup\uat2devdb.bacpac"`
I see the DB copy created on Azure SQL server, but I'm not able to open it via SQL management studio. Only after 5-10 min, I can see the tables from that DB and can retrieve some data. It looks like the DB is still busy or something else. 
The error message is showed from invoke-azurebackuprestore function. I think around the $null = $sqlCommand.ExecuteNonQuery() line.

**Comment by vzugravyi** [comment]
$error shows only this one
![image](https://user-images.githubusercontent.com/2940890/54563215-53892480-49d1-11e9-81ce-f1490b589e33.png)

**Comment by Splaxi** [comment]
Just to clarify things a bit.

When we create the new database inside Azure SQL DB, we use the "CREATE DATABASE AS Copy Of" SQL statement, that will in fact create a copy of the database. This statement will execute and finish instantaneously, even though that the new database is **not** created yet. This process takes time and Microsoft designed it to be asynchronous, so nothing can timeout, while the new database is being provisioned.

That behavior explains why you are able to see the new database inside SSMS, but **not** able to connect to it or query it for data and tables.

We have planned for that behavior in the module, where we running a continuous thread that simply queries some system objects that **should** tell us when the creation of the new database is finished. 

While writing this respons, I actually started an New-D365Bacpac a Tier2 environment on one of my customers environments. The environment is running 8.1 and PU23. It creates the new database without any issues and starts the bacpac process as expected.

![image](https://user-images.githubusercontent.com/8750181/54602472-18730980-4a42-11e9-8205-83536741d952.png)

How long after you started the New-D365Bacpac do you receive the error? Got any idea about the size of the database that you are trying to create a bacpac for? Is the environment the default Tier2 environment that comes with your subscription or an add-on Tier2 environment? What version and PU is the environment running? Is the environment fresh deployed or has it been updated / upgraded from lower versions?

**Comment by vzugravyi** [comment]
1. It worked fine before for 8.0, 8.1.2. Right now we have 8.1.3. PU. 23. 
2. 12 GB is the size of data. 
3. Default is Tier2. 
4. It was updated through LCS 

The issue is come from try {
        Write-PSFMessage -Level InternalComment -Message "Executing a script against the database." -Target (Get-SqlString $SqlCommand)

        $sqlCommand.Connection.Open()
        
        $null = $sqlCommand.ExecuteNonQuery()

I'll try to replace the context of newazuredbfromcopy.sql and check if it works.

**Comment by Splaxi** [comment]
You can actually run a .sql file directly against the database, if you want.

Invoke-D365SqlScript

Then you can test to see if something goes wrong or not, outside the planned execution.

Next step is to run the same sql statement from SSMS and see how it behaves....

**Comment by vzugravyi** [comment]
The two DBs were created. One from SSMS, the second by adjusting the newazuredbfromcopy.sql. 
In both cases, the db was created by around min, but was available to open properties after 6 min. :(

**Comment by Splaxi** [comment]
The 6 minutes isn't a problem - Generating a copy of 12 GB database in Azure simply takes time.

When things worked earlier, how big was the database then?

**Comment by vzugravyi** [comment]
Before, it was 6 Gb. 
I've just added the next line. 
![image](https://user-images.githubusercontent.com/2940890/54609746-39e0ef00-4a5c-11e9-87b9-9d56229d2fcc.png)
maybe it could help. 
Do you use some the default timeout in d365fo.tools?

**Comment by vzugravyi** [comment]
if I change something for the test purpose in the invoke-azurebackuprestore.ps1 file, I don't see the new changes applied. Should I launch something?

**Comment by vzugravyi** [comment]
I've found a solution. :) 
It works for me.  I've changed one line and add two more lines. 
![image](https://user-images.githubusercontent.com/2940890/54613268-17060900-4a63-11e9-8dfa-580307d46e54.png)

**Comment by vzugravyi** [comment]
Thanks for the help. :) And have a nice weekend

**Comment by Splaxi** [comment]
Glad you solved it - but I would like to highlight a few things for you 🙂

If you look at this line
```
$sqlCommand = Get-SqlCommand @SqlConParams -DatabaseName $DatabaseName
```

Then you can see that we actually have a centralized function to create the `$sqlCommand` object, which is name `Get-SqlCommand`.

Looking inside that function, you will see the following:
```
$sqlConnection.ConnectionString = ($Params -join "")

        $sqlCommand = New-Object System.Data.SqlClient.SqlCommand
        $sqlCommand.Connection = $sqlConnection
        $sqlCommand.CommandTimeout = 0
```
Notice `$sqlCommand.CommandTimeout = 0` part? The SqlCommand object is actually a .NET type, so reading the docs for that type [System.Data.SqlClient.Sqlcommand.Commandtimeout](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout?view=netframework-4.7.2#remarks)

Reading the **remarks** section, states that a zero should let the execution of a command run infinitely.

With that settled, let's continue with the next thing.

Setting the CommandTimeout multiple times, 1 before the opening of the connection and 1 after, doesn't do a difference. Setting it before or after the connection is opened, should also not make a difference. While digging around I discovered that we were using the default ConnectionTimeout of 15 seconds, which wasn't our intention - so you actually got me to look close enough, to find room for improvement, so thank you!

Changing to the master database - that is where I see that things could make a difference. The reason for that is that we actually used the master earlier, but in some attempts to fix other things, we needed to switch to the current database. If you look closely, the next section after the "Clone DB" invoke, we create a new SqlCommand and that one is using the master database. 

Will do some testing, with the new connection timeout and use the master database for both SqlCommand and see if things break on my side. If not - then I'm going to push the changes and then you can update your module installation and see if things work for you or not.

**Comment by Splaxi** [comment]
On a side note, the reason why didn't see a change your changes being applied, is that the modules ships with a master file, containing all functions and commands, to optimize the load time of the module.

But I guess that you discovered that, if you were able to see your changes make a difference.

**Comment by Splaxi** [comment]
The issue should be resolved by now, otherwise open it again an let us take it from there...
