### ISSUE TITLE
Implement new parameter -CustomSql for new-d365bacpac

### ISSUE THREAD

**Issue by ptuerk** [d365collaborative/d365fo.tools#24]
Before exporting the copied database, we need to delete tables that take up too much memory and are not required (history tables).
This reduces our Azure database by several GB.
I suggest a parameter called "Truncate" with a table list,
e.g. -Truncate Batch, BatchHistory, BatchJobHistory, DatabaseLog, SysDatabaseLog etc.

**Comment by Splaxi** [comment]
We plan on adding a customsqlscript parameter to the new-D365Bacpac.

Would that help?

**Comment by ptuerk** [comment]
Yes, that would help. Is there an upper limit for the length of the parameter?

**Comment by Splaxi** [comment]
Should be implemented with 0.3.70.

Please test and report back
