### ISSUE TITLE
Add Export-D365bacpac

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#240]
### Enchantment 
Could you add **Export-D365bacpac** script to support moving Tier1 Gold DB to Tier2

Please find a description of this operation here
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig

**Comment by Splaxi** [comment]
With our current knowledge that scenario has been supported since the very beginning.

Could you point out where you think that things are not as they should be?

**Comment by Splaxi** [comment]
If you look closely at the very bottom of the page, you will see that the docs actually points back to our tools and this github repository...

**Comment by valerymoskalenko** [comment]
I have found that **New-D365Bacpack** is what I'm looking for. Just didn't find it... 
Could you create **Export-D365Bacpac** as the alias for **New-D365Bacpack ** ?

**Comment by turbozapekanka** [comment]
The name is indeed confusing. Should've called Export instead of New
