### ISSUE TITLE
Reuse of passwords when importing database

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#25]
When you Import the database to Tier 1 from Tier2, according to MS docs (earlier version), you need to run a SQL script for prepare the target database with the correct credentials. Part of this step is to create the database users, with passwords from LCS. However, one can just as easily simply create the users from the existing SQL Server instance. This removes the dependency to having the passwords gathered from LCS. 

So instead of:
CREATE USER axruntimeuser WITH password 'abc'

You can use:
CREATE USER axruntimeuser FROM LOGIN axruntimeuser

This is now reflected on the docs, and so should the SQL run in d365fo.tools
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server

:-)

**Comment by Splaxi** [comment]
Hi,

Just to make sure, you are talking about the bacpac process from Tier 2 to Tier 1 - right?

Looking into script that we run when moving a bacpac from Azure DB to SQL Server [set-bacpacvaluessql.sql](https://github.com/d365collaborative/d365fo.tools/blob/master/internal/sql/set-bacpacvaluessql.sql)

Only the axdeployextuser user is created with password, while the rest is created from login like you are pointing out.

CREATE USER axdeployextuser WITH PASSWORD = '@axdeployextuser'

Looking into the docs, per the link you shared, they even use that in their script example [update-the-database](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server#update-the-database)

The script we run when moving from SQL Server to Azure DB is [set-bacpacvaluesazure.sql](https://github.com/d365collaborative/d365fo.tools/blob/master/internal/sql/set-bacpacvaluesazure.sql)

That one is creating all the users with password, as per the docs [update-the-database](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-sql-server-to-azure-sql#update-the-database) 
 
So from my point of view we should already be in the clear about this.

Do you agree or am I misunderstanding something - which is very likely :)

**Comment by Splaxi** [comment]
And I just realized the real issue with this!

The Import-D365Bacpac cmdlet needs another parameterset config, that knows what password parameters that are needed for either Azure or Sql.

We need a new parameter switch, that instructs either. With that, we are able of configuring what parameters a mandatory or not.

Great find!!!

**Comment by skaue** [comment]
In my script I even create the axdeployextuser user from the existing login. I believe the docs is outdated here, because the axdeployextuser user was introduced later (7.2?), and it might not be there in all source environments. I believe you can safely create it from instance user without any issues, just like the other users. This should be ok for 7.3 and onward, unless I am mistaken.

**Comment by Splaxi** [comment]
Should be fixed in 0.3.54.
