### ISSUE TITLE
Invoke-D365SDPInstall: Error when running "ReRunStep" on a failed runbook

### ISSUE THREAD

**Issue by devax** [d365collaborative/d365fo.tools#251]
Using current version 0.5.25.
When I have a runbook with failed steps, and then try to rerun a step like so: `Invoke-D365SDPInstall -Path $myPath -Command ReRunStep -Step 1 -RunbookId $myRunBookId` then I get this error:

> [10:15:29][Invoke-D365SDPInstall] It seems that you have entered an already used RunbookId. Please consider if you are trying to re-run some steps or simply pass another RunbookId.
WARNING: [10:15:29][Invoke-D365SDPInstall] Stopping because of RunbookId already used on this machine.

When invoking ReRunStep, it is obvious that you are using an already used RunbookId. Effectively, you currently cannot use the ReRunStep functionality.

This seemed to work with previous version 0.5.24.

**Comment by Splaxi** [comment]
Hi!

Great catch, I'll make sure that the isn't run when you have to provide a existing runbook id. 

For a start I'll go with RunAll only, then we can see if other commands complains about and already existing runbook down the road.

**Comment by Splaxi** [comment]
0.5.26 should have the fix in place

**Comment by devax** [comment]
Awesome -- thank you!
