### ISSUE TITLE
Suggestion: Extra check for Maintenance Mode before DB export

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#253]
Could you implement Extra check for Maintenance Mode before any DB export and Installing DP?
For the following commands

- New-D365Bacpac
- Invoke-D365SDPInstall

I have a case when I forgot to disable Maintenance Mode on the db. Then export/import it to another environment. And then has an issue on Deploying Deployable Package.

I think just a warning/error message should be enough.

**Comment by Splaxi** [comment]
Hi,

Thanks for the suggestion! 

I would argue that implementing the check as a default check, to run always, is a bit out of scope for the module.

But I would like to meet your needs and implement new parameters for each suggested function / cmdlets, to test for that. 

Ultimately I would prefer to implement the check as a standalone function / cmdlet, and then you have to write a your own implementation, consisting of the specific series of functions / cmdlets you need to make sure that things don't break. 

While writing this, I believe that the latter approach, where we give you the opportunity to get the current maintenance status and have it fail, as a standalone function / cmdlet is the best solution...

**Comment by Splaxi** [comment]
Release 0.5.28 will contain a new cmdlet for you.

Get-D365MaintenanceMode
