### ISSUE TITLE
Get-D365Module doesn't detect binary only modules on onebox

### ISSUE THREAD

**Issue by gertvdh** [d365collaborative/d365fo.tools#256]
It seems Get-D365Module doesn't detect binary-only modules on a onebox environment. Can't we always use the RunTimeProvider? Since that seems to work always.

**Comment by Splaxi** [comment]
The command is one of the oldest we have and we created it more as "let's see what we can do". We got some initial help from @Ievgenm (if I remember correctly) and didn't spend more time on making sure that we did use the correct approach.

I would argue that you know more about the issue than I do, so please change the code to fit your need and lets go with that.

If other people are getting issues with the new approach, we will have some test candidates to share what they are facing and that way we maybe able to find an even better way to do it.

But for now, just create a PR with the desired change, and I will make sure to release it tonight.

**Comment by Ievgenm** [comment]
I do not see any issues with using runtimeprovider only. Disk provider can give you more data but because it is not used anyway, runtime should be ok.

**Comment by gertvdh** [comment]
I will do the changes then

**Comment by gertvdh** [comment]
If you use the runtime provider, the modules that are not compiled on dev machine will not show up anymore. So a combination should be used probably

**Comment by Ievgenm** [comment]
What is the point ? If they are not compiled they could be completely broken or work in progress, why do you want to see them?

**Comment by gertvdh** [comment]
I know, but the Cmdlet will behave a bit different then before

**Comment by Ievgenm** [comment]
It's up to you cause you raised the issue. But I would change it anyway, fortunately we can afford potentially breaking changes, can we, @Splaxi  ? :)

**Comment by Splaxi** [comment]
Breaking changes is something that is creepy up on me these days, I know how frustrating it is when things change and my things starts to break. The project is pretty cutting edge and most people know that.

But I want to be fair, if we have found an issue, that doesn't produce the correct result, then we are allowed to introduce breaking changes.

If anyone needs the old behavior, we can import the old and rename the new way of working to Get-D365ModuleV2

I'm up for the breaking stuff, to make it better!

**Comment by gertvdh** [comment]
I made a pull request which does not have a breaking change I think. It will get the modules using the runtime provider and on a onebox it will also add the missing modules (which are not compiled) through the disk provider.

**Comment by Splaxi** [comment]
I'll uptake it and release it right away!

**Comment by Splaxi** [comment]
Give it 10-15 minutes, then 0.5.29 will be available on powershellgallery.com and then you should have what you are looking for!

Cheers @gertvdh !
