### ISSUE TITLE
Suggestion: Switch database could allow Integrated Security

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#26]
The switch-d365activedatabase should support Integrated Security for localhost scenarios (onebox, dev vm, tier1). No need to provide credentials when using Windows Authentication.

"Integrated Security=True"

**Comment by Splaxi** [comment]
We might have a better testing / checking mechanism based on the findings from Invoke-D365DBSync.

We will give it some more testing and share our results.

**Comment by Splaxi** [comment]
We just implemented the latest logic to validate trusted connection in import-d365bacpac.

Please help test it, before we hop onto switch-d365activedatabase. So we don't have to spend to much time fix issues across to many cmdlets at once.

**Comment by skaue** [comment]
Tested the import ok using the following script:

```
Import-Module d365fo.tools

$importParams = @{
    ImportModeTier1 = $true
    BacpacFile = 'D:\Backup\uat_adhoc.bacpac'
    NewDatabaseName = 'AxDB_New'
    Verbose = $true
}

Import-D365Bacpac @importParams
```
Works like charm!

**Comment by skaue** [comment]
The database sync works like charm for local db without having to run as admin using the following script:
````
Import-Module d365fo.tools

Invoke-D365DBSync -Verbose
````

**Comment by Splaxi** [comment]
done with 0.3.70
