### ISSUE TITLE
Suggesting: Location of SqlPackage.exe

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#262]
A new version of SqlPackage has been released. https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download 
You are able to install it side by side with the old version. The new version path is 
C:\Program Files\Microsoft SQL Server\150\DAC\bin\  for x64.

Could we have a new parameter to specify the location of the SqlPackage.exe?

**Comment by Splaxi** [comment]
I think that would be a great idea!

Let me see what I can do about it

**Comment by Splaxi** [comment]
Should be part of the 0.5.30 release
