### ISSUE TITLE
Section of SQL is not replaced with database name

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#27]
The following section needs to be changed:
https://github.com/d365collaborative/d365fo.tools/blob/f32b256a3db6136302e4982304c4402df25f7528/internal/sql/set-bacpacvaluessql.sql#L32

It should be replaced with the target database name.

**Comment by skaue** [comment]
Suggested fix:

https://github.com/skaue/d365fo.tools/commit/685d90b03738083034dfaea96d4f3062fb03c1dd

**Comment by Splaxi** [comment]
Should be fixed with 0.3.54.
