### ISSUE TITLE
Rename-D365Instance breaks Financial Reporting (MR) Designer

### ISSUE THREAD

**Issue by torbennehmer** [d365collaborative/d365fo.tools#273]
When Renaming the instance using `Rename-D365Instance NB-INV-71-INW1` the MR configuration breaks. When starting the MR designer, I get the following error message:

> AADSTS500011: The resource principal named https://nb-inv-71-inw1.cloud.onebox.dynamics.com was not found in the tenant named inway.de. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
> Trace ID: bca...
> Correlation ID: 703...
> Timestamp: 2019-05-15 07:01:44Z

Any idea how to fix this?

**Comment by Splaxi** [comment]
Hi,

Thanks for posting the issue!

I have never seen the issue before, but that might be because we never did run MR designer a local VHD / onebox after a rename.

I would like to help out, but I think we need to take the discussion on another medium, because you might need to share some technical details that shouldn't be public.

My first impression is saying it might never work, because you did provision your own AAD as the tenant for the box, but your AAD tenant cannot validate the name that you just renamed the box to, because Microsoft owns that domain.

Are you able to run the MR designer on a onebox, that hasn't been renamed, but provisioned to your own AAD tenant? I didn't test it yet and will first be able to do the testing next week.

**Comment by Splaxi** [comment]
Maybe - just maybe this could be of some help to you

https://blogs.msdn.microsoft.com/jpsanders/2018/01/30/azure-app-service-error-aadsts50011-the-reply-address-http-azurewebsites-netsignin-oidc-does-not-match-the-reply-addresses-configured-for-the-application/

**Comment by Splaxi** [comment]
Hi,

Just wanted to check on the issue.

We'll close the issue 10th of June, if no further development has been made.

**Comment by torbennehmer** [comment]
Sorry for not reporting so long, my workdays have been very busy.

The link in question is not applicable, I think as it mentions another error number (one less 0 in it, AADSTS50011 vs. AADSTS500011). I'm wondering anyway, why he doesn't complain about the missing info in inway.de otherwise.

In general: In a standard one-box Hyper-V Environment, MR works as intended (at least with a contoso DB), even though I have not checked to run any reports, just tested the integration runs. Apart from that MR is really picky:

Even a simple renaming of the systems host name breaks it, and has to be fixed by reconfiguring the database configuration as per https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/vso-machine-renaming#update-financial-reporting -- or by hacking the hosts file to point the orignal system name to 127.0.0.1. 

If you forget this, the OneVersion platform updates already run into a timeout at some Financial Reporting DB Update steps as they cannot connect to the FR DB. So even without environment renaming this is a pain.

I'm not exactly sure, how to handle this, actually. 

One Question: What I have been wondering: Is there a specific reason, you enforce the cloud-onebox-etc. domain name? If this actually is solveable only through AAD manipulations, it might be prudent to move it to some internal domain. 

Other than that: At a minimum, it would be great to get the toolkit to at least rename the machine in a way so that the MR DB links keep working. This would at least allow us to use scripts for mostly-automated system updates without manual intervention. 

As a developer I could live with a broken MR, even though our presales guys with their local machines on their notebooks tend to disagree (we are not renaming their environments currently).

I would be more than willing to help you to debug this, unfortunately, I'd need some more pointers on what's going on there, as I am not deep expert in AAD and what's happening inside the services in this regard.

**Comment by Splaxi** [comment]
Hi Torben,

Thanks for getting back! 

I'll provide a more in depth reply later, but I wanted to tell you that we already have a cmdlet in place to rename the windows machine. 

https://github.com/d365collaborative/d365fo.tools/blob/d432d8b9c33dac8f7b4477d2823968a62395eeb8/docs/Rename-D365ComputerName.md

**Comment by Splaxi** [comment]
Hey Torben,

More links for you to dive into.... 

https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1229384273?message_id=1229384273

**Comment by Splaxi** [comment]
Hi Torben,

With more than 22 days of silence, I'll close the issue.

You are welcome to open a new issue or we can re-open this one, if you want us to visit things again.
