### ISSUE TITLE
Import-D365Bacpac -ImportModeTier1 results in error

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#282]
Import-D365Bacpac -ImportModeTier1 -BacpacFile "C:\Backup\Prod_20190522.bacpac" -NewDatabaseName "AxDB_Prod_20190522" results in the follwowing error

Test-PathExists : Cannot bind argument to parameter 'Path' because it is null.
At line:2856 char:33
+     if (!(Test-PathExists -Path $executable -Type Leaf)) {return}
+                                 ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-PathExists], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-PathExists

Start-Process : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:2896 char:29
+     Start-Process -FilePath $executable -ArgumentList ($Params -join  ...
+                             ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.StartProcessCommand

Set-SqlBacpacValues : Cannot process argument transformation on parameter 'TrustedConnection'. Cannot convert value ""
to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At line:11579 char:67
+ ...  Set-SqlBacpacValues @Params -TrustedConnection $UseTrustedConnection
+                                                     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-SqlBacpacValues], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-SqlBacpacValues

**Comment by Splaxi** [comment]
We did a small change, to support the use of the latest sqlpackage version.

What version do you have installed? 

I'm 99% sure I used 2 weeks ago, on a Tier1, 8.1.3 without any issues.

**Comment by PaulHeisterkamp** [comment]
I did an update auf the Powershell module and application version is 10.0.1 -------- Ursprüngliche Nachricht --------Betreff: Re: [d365collaborative/d365fo.tools] Import-D365Bacpac -ImportModeTier1 results in error (#282)Von: Mötz Jensen An: "d365collaborative/d365fo.tools" Cc: Paul Heisterkamp ,Author We did a small change, to support the use of the latest sqlpackage version.
What version do you have installed?
I'm 99% sure I used 2 weeks ago, on a Tier1, 8.1.3 without any issues.

**Comment by Splaxi** [comment]
Hey Paul!

Could you try an import the module with `-Force` ?

After that, please run the below command and see what output you get. You should get a valid path for the SqlPackage.exe. I just did on a v8 and v10, freshly deployed (Tier1 - local oneboxes).

```
Get-PSFMessage -Level Verbose -FunctionName Variables.ps1 | Where-Object message -like *sqlpa* | Format-List
```
You could also run the `Import-D365Bacpac` / `New-D365Bacpac` with the `-Verbose` switch, then when you hit the internal function that consumes the SqlPackage, you should see if the path is valid also.

Last thing is that you can try an update the configuration for the SqlPackage:

```
Set-D365SqlPackagePath -Path "C:\...."
``` 

But please try and run things with -Verbose or simply hit us with the output from `Get-PsfMessage -Level Verbose | Format-List` and let us see what we can learn from that.

**Comment by PaulHeisterkamp** [comment]
Hi Mötz,

here is the result for 
`
PS C:\Temp> Import-Module -name d365fo.tools -Force
Exception calling "Parse" with "3" argument(s): "Requested value 'dynaxonebox' was not found."
At line:196 char:5
+     $Script:ServerRole = [ServerRole][Enum]::Parse([type]"ServerRole" ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
`
The Get-PSFMessage did not return any value and here is the result for Import-D365Bacpac with -Vebose

`PS C:\Temp> Import-D365Bacpac -ImportModeTier1 -BacpacFile "C:\Backup\Prod_20190522.bacpac" -NewDatabaseName "AxDB_Prod_
20190522" -Verbose
VERBOSE: [20:42:53][Test-PathExists] Testing the path: C:\Backup\Prod_20190522.bacpac
VERBOSE: [20:42:53][Test-TrustedConnection] Capabilities based on the centralized logic in the psm1 file.
VERBOSE: [20:42:53][Import-D365Bacpac] Testing if we are working against a Tier2 / Azure DB
VERBOSE: [20:42:53][Import-D365Bacpac] Start importing the bacpac with a new database name and current settings
Test-PathExists : Cannot bind argument to parameter 'Path' because it is null.
At line:2856 char:33
+     if (!(Test-PathExists -Path $executable -Type Leaf)) {return}
+                                 ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-PathExists], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-PathExists

VERBOSE: [20:42:53][Invoke-SqlPackage] Starting to prepare the parameters for sqlpackage.exe
VERBOSE: [20:42:53][Invoke-SqlPackage] Start sqlpackage.exe with parameters
Start-Process : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:2896 char:29
+     Start-Process -FilePath $executable -ArgumentList ($Params -join  ...
+                             ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.StartProcessCommand

VERBOSE: [20:42:53][Invoke-SqlPackage] Total time spent inside the function was 00:00:00.0280517
VERBOSE: [20:42:53][Import-D365Bacpac] Importing completed
VERBOSE: [20:42:53][Import-D365Bacpac] Start working on the configuring the new database
VERBOSE: [20:42:53][Import-D365Bacpac] Building sql statement to update the imported SQL database
Set-SqlBacpacValues : Cannot process argument transformation on parameter 'TrustedConnection'. Cannot convert value ""
to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At line:11579 char:67
+ ...  Set-SqlBacpacValues @Params -TrustedConnection $UseTrustedConnection
+                                                     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-SqlBacpacValues], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-SqlBacpacValues

VERBOSE: [20:42:53][Import-D365Bacpac] Total time spent inside the function was 00:00:00.0490000`

Set-D365SqlPackagePath -Path "C:\...." didn´t change anything... :-(

**Comment by Splaxi** [comment]
Hey!

Please remove any old versions from your machine.

This gist should help you with that...

https://gist.github.com/Splaxi/dba292d41841a60fdb1c4f3acca71f40

**Comment by PaulHeisterkamp** [comment]
Will try tomorrow, now I have to watch soccer... :-)

**Comment by Splaxi** [comment]
👍

**Comment by PaulHeisterkamp** [comment]
Hey,
also after uninstalling all old versions and re-install of current version the behavior is still the same.

**Comment by Splaxi** [comment]
Hey Paul.

Should we reboot / restart this issue?

I really wanna help out and make sure things work for you. Let me know if how you see us proceed with this, so we can get on top of this.

**Comment by Splaxi** [comment]
Hi Paul,

Closing the issue for now. Let us reboot when you have time to test things a bit more.

I have been using the Import-D365Bacpac several times over the last few weeks. So we need to spend some time on your scenario.
