### ISSUE TITLE
Suggesting: Could you add a full command line to Invoke-SqlPackage in Verbose or Debug mode?

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#284]
Could you add a full command line to Invoke-SqlPackage in Verbose or Debug mode?

So, instead of
`VERBOSE: [06:50:13][Invoke-SqlPackage] Start sqlpackage.exe with parameters`

I would like to have

`VERBOSE: [06:50:13][Invoke-SqlPackage] Start sqlpackage.exe with parameters "C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe" /Action:import /TargetServerName:localhost /TargetDatabaseName:fc-fno-uat-20190607 /SourceFile:"C:\TEMP\fc fno uat 20190607.bacpac" /Properties:CommandTimeout=0 `

**Comment by Splaxi** [comment]
Should be fixed in 0.5.38
