### ISSUE TITLE
A command with name 'Get-LastResult' is already available on this system.

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#29]
While installing d365fo.tools with the command Install-Module -Name d365fo.tools I´m getting the error following error. This is a brand new 1611 VM with only PowerShell-Module installed for Visual Studio-TFS integration.

PackageManagement\Install-Package : A command with name 'Get-LastResult' is already available on this system. This
module 'd365fo.tools' may override the existing commands. If you still want to install this module 'd365fo.tools', use
-AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by PaulHeisterkamp** [comment]
![image](https://user-images.githubusercontent.com/18070325/43966682-d8e8953c-9cc2-11e8-8fb6-d8592a26aa96.png)

**Comment by Splaxi** [comment]
We are working on a solution.

For now just add the -allowclobber to move on. 

The issue is that we are depending on another powershell module and that is exposing the mentioned get-lastresult, actually an alias. 

We are trying to work with the creator behind the module.

**Comment by PaulHeisterkamp** [comment]
Good to know. Yes I just added -allowclobber to move on.

**Comment by Splaxi** [comment]
Could you find a fresh machine of any kind? Doesn't have to be a functioning D365 machine.

We updated some import logic and hope it solves everything. Can you confirm?

0.3.55 version if you validate the version after installation.

Get-Module -ListAvailable should give you a list of modules and their version information.

**Comment by Splaxi** [comment]
Perfect! Issue is closed with this testing.
