### ISSUE TITLE
d365fo.lcs?

### ISSUE THREAD

**Issue by anderson-joyle** [d365collaborative/d365fo.tools#292]
Is it time to start creating a "d365fo.lcs" repository capable to download/upload files from/to asset library, get all RDPs from all cloud environments at once, VMs states, etc?

**Comment by Splaxi** [comment]
All API's that are available from LCS, are already implemented in the tools at the moment.

I have been giving it a fair amount of thought what we should do with the future releases of LCS. 

Boiled down the most important things we have in the module are bacpac handling and upload/download to azure storage.

Every single lcs api will have a matching Azure DevOps market place solution. So adopting the LCS API is more about that we can do it, than solving a real need.

What are your thoughts and comments?
