### ISSUE TITLE
New-D365Bacpac someting went wrong while removing db...

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#293]
Run export from Tier 1 environment and staging db was not removed because of "something went wrong" and the staging DB ended up in recovery mode. Had to remove it manually

**Comment by turbozapekanka** [comment]
Here is another "Something went wrong" error:


PS C:\windows\system32> New-D365Bacpac -ExportModeTier1 -BackupDirectory D:\Temp\ -NewDatabaseName TTIDemo -BacpacFile "
D:\Temp\TTIDemo.bacpac"
[16:53:33][Invoke-SqlBackupRestore] Something went wrong while doing backup / restore against the database. | Exception
calling "ExecuteNonQuery" with "0" argument(s): "The database to be restored was named 'AxDB'. Reissue the statement usi
ng the WITH REPLACE option to overwrite the 'TTIDemo' database.
RESTORE DATABASE is terminating abnormally.
10 percent processed.
20 percent processed.
30 percent processed.
40 percent processed.
50 percent processed.
60 percent processed.
70 percent processed.
80 percent processed.
90 percent processed.
Processed 979568 pages for database 'AxDB', file 'AXDBBuild_Data' on file 1.
100 percent processed.
Processed 8 pages for database 'AxDB', file 'AXDBBuild_Log' on file 1.
BACKUP DATABASE successfully processed 979576 pages in 75.536 seconds (101.315 MB/sec)."
WARNING: [16:53:33][Invoke-SqlBackupRestore] Stopping because of errors. | Something went wrong while doing backup /
restore against the database.
PS C:\windows\system32>

**Comment by turbozapekanka** [comment]
More details


Processing Table '[dbo].[RTAX25REGISTERTRANS_INVENTRECEIPTTOTAL]'.
Processing Table '[ax].[SYSTEMPARAMETERS]'.
Processing Table '[dbo].[TMSTRANSPORTATIONPURCHASELOADBUILDINGTEMPLATESEQUENCESTAGING]'.
Processing Table '[dbo].[BATCHSERVERCONFIG]'.
Processing Table '[dbo].[CAMDATACOSTACCOUNTINGLEDGERSETUPVALIDATIONMESSAGE]'.
Processing Table '[dbo].[AGREEMENTHEADERHISTORY]'.
Processing Table '[ax].[RETAILBARCODEMASKSEGMENT]'.
Processing Table '[dbo].[UNITOFMEASUREREPORTINGTRANSLATION]'.
Processing Table '[dbo].[JMGPROFILERELATION]'.
Processing Table '[dbo].[ASSETPOSTINGPROFILEDISPOSALSTAGING]'.
Processing Table '[dbo].[VENDTRANS_IN]'.
Processing Table '[dbo].[EXIMPARAMETERS_IN]'.
Processing Table '[dbo].[PROJADJUSTMENTSALEINPROCESS]'.
Processing Table '[dbo].[ECORESTRACKINGDIMENSIONGROUPITEM]'.
Processing Table '[dbo].[FISCALDOCUMENTTAXTRANSOUTGOINGICMSDIF_BR]'.
Processing Table '[dbo].[INVENTTABLEMODULE]'.
Processing Table '[dbo].[VENDRFQAMENDMENTJOUR]'.
Processing Table '[dbo].[SYSMAPPARAMETERS]'.
Processing Table '[dbo].[CFPSTABLE_BR]'.
Processing Table '[dbo].[PAYROLLBENEFITCALCULATIONRATEHEADERSTAGING]'.
Processing Table '[ax].[RETAILINFOCODETRANSLATION]'.
Processing Table '[dbo].[DOMAINEVENTTRANSITIONMODEL]'.
Processing Table '[dbo].[LEDGERPRINTLAYOUT_CN]'.
Processing Table '[dbo].[SYSAADCLIENTTABLESTAGING]'.
Processing Table '[dbo].[PAYROLLPOSITIVEPAYEXPORTSTAGING]'.
Processing Table '[dbo].[ECORESBOUNDEDATTRIBUTETYPEVALUE]'.
Processing Table '[dbo].[MCRSALESQUOTATIONLINE]'.
Successfully exported database and saved it to file 'D:\Temp\gold.bacpac'.
[22:05:32][Remove-D365Database] Something went wrong while <c='Green'>removing the Database.
WARNING: [22:05:32][Remove-D365Database] Stopping because of errors. | Something went wrong while removing the
Database.

File                    Filename
----                    --------
D:\Temp\gold.bacpac gold.bacpac


PS C:\windows\system32>

**Comment by Splaxi** [comment]
Could you run the command with `-Verbose`

And right after it fails, simply:
```
$error
```

**Comment by Splaxi** [comment]
Did you have a chance to do some more testing for us to look at?

**Comment by turbozapekanka** [comment]
Not yet. But I will. Next time I move gold to test

**Comment by turbozapekanka** [comment]
Added -Verbose:

Processing Table '[dbo].[LEDGERPRINTLAYOUT_CN]'.
Processing Table '[dbo].[SYSAADCLIENTTABLESTAGING]'.
Processing Table '[dbo].[PAYROLLPOSITIVEPAYEXPORTSTAGING]'.
Processing Table '[dbo].[ECORESBOUNDEDATTRIBUTETYPEVALUE]'.
Processing Table '[dbo].[MCRSALESQUOTATIONLINE]'.
Successfully exported database and saved it to file 'D:\Temp\stl-gold.bacpac'.
VERBOSE: [22:42:21][Invoke-Process] Total time spent inside the function was 00:25:50.1437109
VERBOSE: [22:42:21][Invoke-SqlPackage] Total time spent inside the function was 00:25:50.1749379
VERBOSE: [22:42:21][New-D365Bacpac] Invoking the Tier 1 - Remove database from SQL
VERBOSE: [22:42:21][Test-TrustedConnection] Not capable of using Trusted Connection based on supplied SQL login
details.
[22:42:22][Remove-D365Database] Something went wrong while <c='Green'>removing the Database.
WARNING: [22:42:22][Remove-D365Database] Stopping because of errors. | Something went wrong while removing the
Database.

VERBOSE: [22:42:22][New-D365Bacpac] Total time spent inside the function was 00:28:49.5735416
File                    Filename
----                    --------
D:\Temp\stl-gold.bacpac stl-gold.bacpac

**Comment by turbozapekanka** [comment]
PS C:\windows\system32> $error
Stop-D365Environment : The 'Stop-D365Environment' command was found in the module 'd365fo.tools', but the module could
not be loaded. For more information, run 'Import-Module d365fo.tools'.
At line:1 char:1
+ Stop-D365Environment
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Stop-D365Environment:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:678 char:26
+ ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...llGet.Telemetry:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by turbozapekanka** [comment]
PS C:\windows\system32> Get-PSFMessage -Errors

Timestamp              FunctionName        ExceptionType TargetObject Message
---------              ------------        ------------- ------------ -------
10/22/2019 10:42:22 PM Remove-D365Database Exception                  Stopping because of errors. | Something went w...

**Comment by turbozapekanka** [comment]
PS C:\windows\system32> Get-D365Database

Name
----
AxDB
AxDW
DynamicsAxReportServer
DynamicsAxReportServerTempDB
DYNAMICSXREFDB
FinancialReportingDb
stl-gold

**Comment by turbozapekanka** [comment]
PS C:\windows\system32> Remove-D365Database -Name stl-gold
Remove-D365Database : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:21
+ Remove-D365Database -Name stl-gold
+                     ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-D365Database], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Remove-D365Database

**Comment by turbozapekanka** [comment]
Same error in a new PS session

**Comment by Splaxi** [comment]
Thank you for sharing all this!

You should run the `Remove-D365Database` with the -DatabaseName parameter and not name.

```
Remove-D365Database -DatabaseName stl-gold
```

I'll do some testing on my side as well.

**Comment by turbozapekanka** [comment]
Already removed the database manually, will try next time

You may also notice there is an error related to Stop-D365Environment,
This is something that happens after I update the module, the command does not work, but it works with 2nd attempt. Not sure if this is a bug.

**Comment by turbozapekanka** [comment]
This worked today without any errors. I did update the tools before export.

**Comment by Splaxi** [comment]
This would be linked to the pooling issue we solved in the 0.6.75 version. 

#644
