### ISSUE TITLE
Enhancement Request: Enable 'synclist' parameter in Invoke-D365DBSync

### ISSUE THREAD

**Issue by RobvanB** [d365collaborative/d365fo.tools#294]
When using SyncMode 'PartialList', you will need to specify a value for the 'synclist' parameter, but the tool currently does not accept that parameter.

**Comment by Splaxi** [comment]
Hey @robvanB

You're the very first to come with a request for more than FullSync. 

Would an Invoke-DBSyncPartial cmdlet with the needed parameters be an acceptable solution?

**Comment by RobvanB** [comment]
Hi Motz -

Sure,that would work!

Rob.

**Comment by Splaxi** [comment]
Hi Rob,

Please download the latest version and take it for a spin!

https://twitter.com/splaxi/status/1172435177131216898
