### ISSUE TITLE
Empty database after importing a bacpac created with New-D365Bacpac

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#296]
Exported a bacpac from Tier1 environment, uploaded to LCS Asset library, imported to Tier2 - ended up with empty database.

**Comment by devax** [comment]
For what it is worth, I just did the exact same thing today and the result was good.
This is the command I used to export the bacpac:
`New-D365Bacpac -ExportModeTier1 -DatabaseServer $sqlServerInstance -DatabaseName $sqlDbNameTarget -BacpacFile $bacpacfile`

Before exporting, I made sure to run the commands on the source SQL database as described here: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-goldenconfig

**Comment by Splaxi** [comment]
Thanks for reporting the issue.

I will try and have a look at it next week, when I'm back from vacation. 

Could you try to export the bacpac from a Tier1 environment and import it, either into the same or another Tier1, without uploading it to the LCS library? Just to make sure that what you are seeing is actually an empty database when exporting. Or it is broken when uploaded to the LCS library...

**Comment by turbozapekanka** [comment]
This is how I exported it:
New-D365Bacpac -ExportModeTier1 -BackupDirectory D:\Temp\ -NewDatabaseName TTIDemo -BacpacFile "D:\Temp\TTIDemo.bacpac"

I did not shut down any services or run any prep scripts as I assumed that these tools do this for you.
This is cloud-hosted environment on PU25 version.

Tier2 which I imported this to is on PU28 though. Could this be the cause of the issue?

I will now try to import the same bacpac to another environment.

**Comment by devax** [comment]
> This is cloud-hosted environment on PU25 version.

> Tier2 which I imported this to is on PU28 though. Could this be the cause of the issue?

Could be, depends on the application version on these machines.
From the link I've posted before:

> The developer environment must run the same application version of Finance and Operations as the target UAT environment. In addition, the platform version of the developer environment must be earlier than or the same as the platform version in the target UAT environment.

**Comment by turbozapekanka** [comment]
Imported to another Tier1 environment, but running on different (PU28) version.
Import was successful but when I try to open it shows the error: "The browser session was lost due to an error on the server."

**Comment by Splaxi** [comment]
And you are sure you don't need to provision the database, because you are in another tenant?

**Comment by turbozapekanka** [comment]
Everything is in the same tenant.

**Comment by turbozapekanka** [comment]
I'm now thinking about extra packages Tier1 environment normally have installed, which are not present in Tier2, like FleetManagement, DemoDataSuite and others. Exported bacpac from Tier1 probably have more tables/fields than in Tier2 environment, does it cause any problems?

**Comment by Splaxi** [comment]
Normally not.

We recommend that you execute a database sync, from the tools, after you switch out the databases.

This will remove unwanted and extra tables from the database. 

What is pushing my buttons, is that you say that you see the dat company, and nothing else. But is the data valid and complete?

**Comment by turbozapekanka** [comment]
Well there is no data. It looks like empty database.
I now updated the Tier1 database to match the Tier2 version and try to import again.

**Comment by turbozapekanka** [comment]
Updated source Tier1 to match the Tier2 version (10.0.4 pu28) and the same issue - empty database after import to Tier2

**Comment by turbozapekanka** [comment]
I also tried to import a backup exported from the same Tier2 environment and it also resulted in blank database. Microsoft is looking into this now

**Comment by turbozapekanka** [comment]
It seems that it fails because of multiple partitions. Is this a known limitation?

**Comment by Splaxi** [comment]
I haven't seen it before.

What did Microsoft say? 

I think I saw something on the Yammer groups about how to update the partitions in the database.

https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=168556004515840&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=partition

**Comment by turbozapekanka** [comment]
https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=168556004515840
https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=135604753899520

**Comment by turbozapekanka** [comment]
I found these topics and made them aware. Not sure if this is something they're going to fix but they suggested to submit at https://experience.dynamics.com/ideas/

**Comment by turbozapekanka** [comment]
This was confirmed as a product bug
Here is a workaround:

update userinfo set DEFAULTPARTITION = 0 where id='admin' and PARTITION=XXX
update userinfo set DEFAULTPARTITION = 1 where id='admin' and PARTITION=YYY
Restart IIS

**Comment by Splaxi** [comment]
Thanks for posting the solution!
