### ISSUE TITLE
Import-AadUser wrong synthaxe un readme

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#3]
Hello,

in readme.md, you say that we can use the import-AadUser with this synthax :
Import-AadUser -Userlist "Claire@contoso.com,Allen@contoso.com"

but the script failed because the value separator must be ";" and not ","
Import-AadUser -Userlist "Claire@contoso.com;Allen@contoso.com"

in the powershell function, you split by using this command
  $usersFromList = $UserList.Split(";")

**Comment by Splaxi** [comment]
Great find!

Will update the Readme later today. 

Cheers for taking the time to report the issue.

**Comment by Splaxi** [comment]
Readme updated
