### ISSUE TITLE
Suggestion: Import-d365bacpac should check for the existence of the bacpac file

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#30]
If the bacpac file for whatever reason doesn't exist, the script acts like the file was actually imported (stating "import completed"). 
Maybe the cmdlet should throw if the file is missing, just as it throws if sqlpackage.exe is missing.

**Comment by Splaxi** [comment]
We are working on refactoring the import-d365bacpac.

Will include check for existing of the file.

**Comment by Splaxi** [comment]
Done with 0.3.70
