### ISSUE TITLE
Get-D365DatabaseServer command missing

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#300]
How can I get the db server name? e.g.  xxx.server.database.windows.net

**Comment by Splaxi** [comment]
Everything is available from the 

```
Get-D365DatabaseAccess
```

Which is just a subset of the `Get-D365EnvironmentSettings`, which returns objects. You need to query those objects, to get the details from them.

This example will give you the same details as the `Get-D365DatabaseAccess` cmdlet.
```
(Get-D365EnvironmentSettings).DataAccess
```

**Comment by turbozapekanka** [comment]
Thanks, this worked!
