### ISSUE TITLE
Invoke-D365SDPInstall does not update BIService and RetailSelfService

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#301]
Invoke-D365SDPInstall -Path "c:\temp\PU28" -Command RunAll
BIService and RetailSelfService still has old version

C:\Temp\PU28>AXUpdateInstaller.exe list
List of services installed on the system:

ALMService       Version: 7.0.5314.35432
AOSService       Version: 7.0.5314.35432
BIService        Version: 7.0.5179.35392
DevToolsService  Version: 7.0.5314.35432
DIXFService      Version: 7.0.5314.35432
MROneBox         Version: 10.0.136.10007
PayrollTaxModule         Version: 10.0.136.10007
PerfSDK  Version: 7.0.5314.35432
ReportingService         Version: 7.0.5314.35432
RetailCloudPos   Version: 10.0.136.10007
RetailHQConfiguration    Version: 10.0.136.10007
RetailSDK        Version: 10.0.136.10007
RetailSelfService        Version: 10.0.8.10023
RetailServer     Version: 10.0.136.10007
RetailStorefront         Version: 10.0.136.10007
SCMSelfService   Version: 10.0.136.10007

**Comment by Splaxi** [comment]
Could you test the same on another machine, where you use the tools from Microsoft, so we have a baseline to compare against?

Inside your folder there should be Topology file, can you share the content of that, so we can see what services are registered inside it?

**Comment by turbozapekanka** [comment]
I ran this on a 10.0 VHD image from LCS
And I get the same results when running this manually like that:

`AXUpdateInstaller.exe generate -runbookid="OneBoxDev" -topologyfile="DefaultTopologyData.xml" -servicemodelfile="DefaultServiceModelData.xml" -runbookfile="OneBoxDev-runbook.xml"
AXUpdateInstaller.exe import -runbookfile=OneBoxDev-runbook.xml
AXUpdateInstaller.exe execute -runbookid=OneBoxDev`

here is the topology xml:
`<?xml version="1.0" encoding="utf-8"?>
<TopologyData xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>AX topology</Name>
  <MachineList>
    <Machine>
      <Name>MININT-F36S5EH</Name>
      <ServiceModelList>
        <string>ALMService</string>
        <string>AOSService</string>
        <string>BIService</string>
        <string>DevToolsService</string>
        <string>DIXFService</string>
        <string>MROneBox</string>
        <string>PayrollTaxModule</string>
        <string>PerfSDK</string>
        <string>ReportingService</string>
        <string>RetailCloudPos</string>
        <string>RetailHQConfiguration</string>
        <string>RetailSDK</string>
        <string>RetailSelfService</string>
        <string>RetailServer</string>
        <string>RetailStorefront</string>
        <string>SCMSelfService</string>
      </ServiceModelList>
    </Machine>
  </MachineList>
  <BackupScript>
    <FileName />
    <Automated>false</Automated>
    <Description>Please backup your environment now, set this step to complete once you finished backup</Description>
  </BackupScript>
</TopologyData>`

Probably I expected too much from the tools.
They seem to do exactly the same steps, just simplify generation of the topology xml file.

**Comment by valerymoskalenko** [comment]
JFi
I used to the following script
```
Write-Host '..[1/4] Set topology' -ForegroundColor Yellow
Invoke-D365SDPInstall -Command SetTopology -Path $packageDirectory -RunbookId $runbookId -Verbose

Write-Host '..[2/4] Generate runbook' -ForegroundColor Yellow
Invoke-D365SDPInstall -Command Generate -Path $packageDirectory -RunbookId $runbookId -Verbose

Write-Host '..[3/4] Import runbook' -ForegroundColor Yellow
Invoke-D365SDPInstall -Command Import -Path $packageDirectory -RunbookId $runbookId -Verbose

Write-Host '..[4/4] Execute runbook' -ForegroundColor Yellow
Invoke-D365SDPInstall -Command Execute -Path $packageDirectory -RunbookId $runbookId -Verbose
```

But it looks the same as
```
Invoke-D365SDPInstall -Command RunAll -Path $packageDirectory -RunbookId $runbookId -Verbose
```

**Comment by Splaxi** [comment]
Yes, RunAll will simply execute all individual steps in one go.

**Comment by Splaxi** [comment]
@turbozapekanka 

Can we close this issue? I saw your post on yammer some time back, where you saw that the tools from MS also did give you the same results.

**Comment by turbozapekanka** [comment]
Yes
