### ISSUE TITLE
Enhancement: Import-D365Bacpac new parameter -EnableDiagnostic

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#302]
New Enhancement
For Import-D365Bacpac add the new parameter "-EnableDiagnostic TextFilename (or something like this). This will add two parameters to SqlPackage:
/d:True 
/df:"TextFilename"

Please find example for SqlPackage
SqlPackage.exe /a:import /TargetServerName:fcfnogold-1 /TargetDatabaseName:fcfnodm4backup20190905 /SourceFile:"D:\TEMP\fc fno dm 4backup.bacpac" /Properties:CommandTimeout=1200 **/d:True /df:"d:\temp\diag.txt"**

The official documentation is here https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-2017#script-parameters-and-properties

**Comment by Splaxi** [comment]
Great idea!

Hopefully I will have time to add that over the next week 🤞

Will keep you posted 😁

**Comment by valerymoskalenko** [comment]
Another new parameter, as enchantment 
For Import-D365Bacpac add the new parameter "-SqlPackagePath FilePath" (or something like this).
Where FilePath is something like "C:\Program Files (x86)\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe"
Default value is "'C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe'"

I just install a new version of SqlPackage and script stopped :-( Update remove version 140 but add version 150 of SqlPackage.
![image](https://user-images.githubusercontent.com/22589392/64588883-5c6d1880-d3ac-11e9-9354-00017d7f5a2b.png)

**Comment by Splaxi** [comment]
This should already be solved by:

https://github.com/d365collaborative/d365fo.tools/blob/development/docs/Set-D365SqlPackagePath.md

**Comment by Splaxi** [comment]
Hi, 

0.5.41 should include the new diagnostic parameter.

Both for import / new bacpac cmdlets....

**Comment by Splaxi** [comment]
https://twitter.com/splaxi/status/1172427593137541122

Please open a new issue if you find any errors we should take care of.

**Comment by valerymoskalenko** [comment]
Thank you! I have tested it and it works as intended.
Feel free to close this ...ticket.
