### ISSUE TITLE
Enhancement: Invoke-D365SDPInstall: Support zip-path

### ISSUE THREAD

**Issue by JohannesDrexler** [d365collaborative/d365fo.tools#304]
I would suggest that the parameter 'Path' should support a path to a zip file and then unpack this zipfile in a folder with the same name as the zip next to the zip and then use extracted path.

In my opinion, that would improve the workflow to update a machine.

I can provide a pullrequest if needed

**Comment by Splaxi** [comment]
Please do, and we can work together on how things should look.

Let me know if you need any introduction to some of our concepts.

A fair warning - you don't need to create test.ps1 files. Just write the code and ignore the failed tests, until we settle for something. We have some tools in places to create test.ps1 files and update the documentation based on the meta data.

**Comment by Splaxi** [comment]
@JohannesDrexler 

Did you find time to look at this? Let me know if you need anything 😉

**Comment by JohannesDrexler** [comment]
@Splaxi Here is a PullRequest with how i think this can be handled -> https://github.com/d365collaborative/d365fo.tools/pull/315

If the $Path is a Zip-File the Zip-File will be extracted to a folder in the same directory as the ZipFile. Lets say i have downloaded the latest updates and placed them like this `C:\Temp\pu29.zip`, then i call `Invoke-D365SDPInstall -path "C:\Temp\pu29.zip" -quickinstallall` then the command will extract the zips content to "C:\Temp\pu29" and update the value of the parameter `$Path` to this directory.

**Comment by Splaxi** [comment]
Hey @JohannesDrexler 

I need your full name and twitter handle, if you want me to give you the credits that you earned from skipping in with a pull request for the tools.

Let me know the name and online (twitter?) alias you want me to include.

**Comment by Splaxi** [comment]
Is part of the 0.5.48 release...
