### ISSUE TITLE
Rename-D365ComputerName does not rename the SQL server server name

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#326]
select @@SERVERNAME stilll returns old name

more information https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/vso-machine-renaming#update-the-server-name-in-sql-server

**Comment by Splaxi** [comment]
Thank you for sharing!

We thought we already included in our script, but as your found out - we didn't!

The newest release: 0.5.52 will contain an updated version of the Rename-D365ComputerName. Take it for a spin and test how it works out for you.
