### ISSUE TITLE
Invoke-D365SDPInstall Test-PathExists error

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#327]
I run this on top of a fresh FinanceAndOperations v10 VHD and get this error:

PS C:\windows\system32> cd c:\temp
PS C:\temp> Invoke-D365SDPInstall -Path "C:\Temp\FinanceAndOperations_10.0.234.10001_Application" -Command RunAll
[12:14:50][Test-PathExists] The C:\Logs\InstallationRecords\Runbooks path wasn't found. Please ensure the path exists an
d you have enough permission to access the path.
WARNING: [12:14:50][Test-PathExists] Stopping because of missing paths.

The path does exist and I'm running as Administrator and should have access.

**Comment by turbozapekanka** [comment]
The execution seem to proceed though, despite the message saying "Stopping". What's going on?

**Comment by Splaxi** [comment]
Before closing the powershell session, please run

Get-PsfMessage -Level Verbose 

And

Get-PsfMessage -Error

**Comment by Splaxi** [comment]
And share a screen shot if you can 👍

**Comment by turbozapekanka** [comment]
I've restarted the VM already.
Looks like it was updated successfully, No sure what what that error/warning about.

**Comment by turbozapekanka** [comment]
It should be very easy to reproduce though.
I started with fresh V10 VHD, renamed the VM, downloaded the 10.0.6 PU30 update and executed the above command.

**Comment by Splaxi** [comment]
For us to be able to assist and help you, we need you to provide a bit more information the next time.

I'll do a test install tomorrow, just to see if I get the same error as you...

**Comment by Splaxi** [comment]
I just tested with latest version of the tools on a VM, no problems.

I will try on the latest vm release from lcs later today, just to make sure...

**Comment by turbozapekanka** [comment]
Run this on a VM that has been previously updated to 10.0.4 and the error does not show up. So it might be something to do with the fresh VM, never updated.

**Comment by Splaxi** [comment]
I found the error!

This path exists on a newly extracted VHD (onebox): C:\Logs\InstallationRecords

But the this path does NOT exists: C:\Logs\InstallationRecords\Runbooks

We have some safe mechanism checking in place, that tests for the "C:\Logs\InstallationRecords\Runbooks" path, which fails. But the failing error isn't termination and that is why it continues execution the installation of the deployable package. Which in the VERY second it starts, creates the missing "Runbooks" folder and then when we start looking, it seems it already exists.

I'll be doing some refactor of the testing mechanism, so we can handle this scenario.

**Comment by Splaxi** [comment]
Release 0.5.54 should fix this issue going forward.
