### ISSUE TITLE
Work on documentation

### ISSUE THREAD

**Issue by Splaxi** [d365collaborative/d365fo.tools#329]
https://www.youtube.com/watch?time_continue=38&v=t4vKPhjcMZg

https://www.divio.com/blog/documentation/

**Comment by valerymoskalenko** [comment]
Agree. Tutorials are missed on this tool.

**Comment by Splaxi** [comment]
Any help would be greatly appreciated, so if you know something and have time to spare, please feel free to skip in.

I can polish it up if needed and put it into the wiki.
