### ISSUE TITLE
Question: Compile all module

### ISSUE THREAD

**Issue by rabol** [d365collaborative/d365fo.tools#333]
Hi

How do I compile all modules ?

**Comment by Splaxi** [comment]
Great question!

We just updated the d365fo.tools module to implement a simple way to compile all available modules.

I expect to be able to share a How-To in the next 1 or 2 days.

And if you just want the code that works, look below. You need to be on 0.5.53 (was released less 3 hours ago)

```
Get-D365Module | Invoke-D365ModuleFullCompile
```

**Comment by rabol** [comment]
Works!

Thanks a lot

**Comment by rabol** [comment]
Just one small issue: the result is in the <module> folder as pr. the compile command, so after doing a 'full' compile one have to look into all the log files to see if there is any errors.

Is there a 'trick' to see if there is any errors ?

**Comment by Splaxi** [comment]
Not really.

You could use the -ShowOriginalProgress parameter to get some insights in your console. 

These cmdlets / functions is meant to replace a build / compile from Visual Studio or the build environment. They are meant to assist you making sure 3. party and ISV solutions can compile after importing.

You should be able to write your own analyse function, that traverses all the files generated and scan them for error message. 

For now this is not on our road and I don't see it getting there unless other people are willing to spend the time digging out the dirty details and providing that for us to uptake and implement.

**Comment by rabol** [comment]
Ok, no problem
