### ISSUE TITLE
Implement a bacpac file trimmer

### ISSUE THREAD

**Issue by anderson-joyle** [d365collaborative/d365fo.tools#348]
History tables like BatchHistory and BatchJobHistory take a long time to be imported. Maybe we could exclude such tables from bacpac file in advance (since it behaves like a zip file) to speed up import process.

**Comment by Splaxi** [comment]
If you can share a working sample of some code that does what you expect, then we can look into it.

It is fine if you just work on an extracted folder, from a bacpac file

**Comment by Splaxi** [comment]
And Christmas came early this year dear @anderson-joyle 

This is implemented and released as of 0.5.61. So grab it while it is hot!

**Comment by anderson-joyle** [comment]
Nice. Sorry for taking to long to respond back. When I finally managed to come up with some test code, you already released the solution.
Cool. I will try the new release once I have the change.
