### ISSUE TITLE
Power shell for Debug UAT Database in Development Sandbox

### ISSUE THREAD

**Issue by celuxcwb** [d365collaborative/d365fo.tools#351]
This is not a mistake, and I don't know if it's the best place for this kind of suggestion. I am using D365FO.Tools for many things.

This library is amazing, but you would like to make a suggestion.

Could you create a PowerShell to configure Development Environment to debug UAT environments like this Microsoft documentation?

https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-debugdiag

Thanks for this channel.

**Comment by Splaxi** [comment]
Hi,

First of, thank you for the kind words. 

I need some more details from you, where you help me understand which parts you want me to support. 

If we are talking about updating the web.config file, that should be easy, but fixing the IP address / firewall rule is a whole other story. 

Do you know how we can use debug process with self-service environments, where we don't have RDP access to the AOS instance in the UAT environment?

**Comment by Splaxi** [comment]
Issue will be closed due to lack of communication.

You're welcome to ping me when you have more details to share, and we can reopen the issue and continue from there.
