### ISSUE TITLE
New column "StartType" to the command Start-D365Environment

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#360]
### New enhancement

I had faced a minor issue when Batch service doesn't start after Start-D365Environment -All
And the issue was that Batch service was Disabled.

Could you add new column "StartType" to the following commands

- Get-D365Environment
- Start-D365Environment
- Stop-D365Environment 

**Hint**
Instead of the following
`Get-Service -ComputerName $server -Name $Services -ErrorAction SilentlyContinue| Select-Object @{Name = "Server"; Expression = {$Server}}, Name, Status, DisplayName`

Should be something like this
`Get-Service -ComputerName $server -Name $Services -ErrorAction SilentlyContinue| Select-Object @{Name = "Server"; Expression = {$Server}}, Name, Status, StartType, DisplayName`

I.e., the new parameter StartType

**Comment by Splaxi** [comment]
Great idea!

Let me see if I can get it done over the next few days.

**Comment by Splaxi** [comment]
This is solved in 0.5.64
