### ISSUE TITLE
Invoke-D365AzureStorageUpload does not offer an option to set a proper content type for newly uploaded files

### ISSUE THREAD

**Issue by devax** [d365collaborative/d365fo.tools#364]
I plan to provide a PR that will cover the following functionality:

If you use the commandlet `Invoke-D365AzureStorageUpload` to upload a file to Azure storage which is not yet present in Azure storage, the "Content type" property of the file will always be set to `application/octet-stream`. If you compare that with what Azure Storage Explorer does when uploading the same file, you will see that Azure Storage Explorer will in many cases figure out the correct content type for uploaded files and set the property accordingly.

Some examples:

- \*.jpg/\*.jpeg files should result in content type "image/jpeg"
- *.png files should result in content type "image/png"
- *.pdf files should result in content type "application/pdf"
- *.docx files should result in content type "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
- etc.

A list of (valid) media types can be found here: https://www.iana.org/assignments/media-types/media-types.xhtml

As a minimum, a parameter should be added to the current commandlet to allow to pass a specific content type to the function, which then should be used as the content type property when uploading to Azure storage.
If no value for the new parameter is provided, it would be nice if function tried to figure out the content type based on the file extension. .NET framework methods can be leveraged to accomplish that.

**Comment by devax** [comment]
Created PR #365 to implement this functionality.

**Comment by Splaxi** [comment]
This is solved in 0.5.64
