### ISSUE TITLE
Invoke-D365DBSync error

### ISSUE THREAD

**Issue by ptuerk** [d365collaborative/d365fo.tools#37]
If I use the following command:

Invoke-D365DBSync  -DatabaseServer "DENUE--AX-QRA15" -DatabaseName "AXDB" -SqlUser "sqlAdmin" -SqlPwd "LokalCosm0123!" -LogPath "C:\AOSService\PackagesLocalDirectory\_logs"  -Verbose

I get the following error:
VERBOSE: CommandFile \bin\SyncEngine.exe
VERBOSE: Parameters  -syncmode=fullall -verbosity=normal -metadatabinaries=""
-connect="server=DENUE--AX-QRA15;Database=AXDB;Trusted_Connection=false; User Id=;Password=;"
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At line:88 char:16
+ ...  $process = Start-Process -FilePath $command -ArgumentList  $param -P ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

VERBOSE: Process Started
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At line:93 char:19
+     Write-Verbose $process
+                   ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerbos
   eCommand

Time Taken for sync:
00:00:00.0019951

it seems to me that the sqlUser and the sqlPwd are not recognized

**Comment by Splaxi** [comment]
Thanks for reporting this issue.

What version of the module are you running?

Get-Module d365fo.tools

Please confirm what type of environment you are running on.
* Local VM / Onebox (downloaded VHD from Microsoft) ?
* Tier 1 - hosted on Azure Subscription?
* Tier 1 - hosted on MS Subscription?
* Tier 2 - hosted on MS Subscription?
* Any Local Business Data (LBD) type of environment?

Could you try and load the module once again and run the below command?

Get-PSFMessage | out-file c:\temp\messages.txt

And then upload the content of the file to pastebin or something similar, and share the link here?

**Comment by Splaxi** [comment]
If you want any assistance please reach out to us. We are present on twitter and other platforms as well.

**Comment by Splaxi** [comment]
Closed because of lacking feedback.
