### ISSUE TITLE
D365FO Sequences

### ISSUE THREAD

**Issue by ITRasmus** [d365collaborative/d365fo.tools#38]
As mentioned by [valerymoskalenko  ](https://github.com/valerymoskalenko) in issue #36 

Inserting records into D365FO, should use the Sequences used in SQL server instead of the old SYSTEMSEQUENCE Table. 

The Sequence is named like SEQ_TABLEID

**Comment by Splaxi** [comment]
The first findings show that there is configured a default constraint that automatically pulls the next from the sequence.

So we should have any more work on this.

**Comment by ITRasmus** [comment]
Agreed
