### ISSUE TITLE
Expose Start-LcsUpload

### ISSUE THREAD

**Issue by Splaxi** [d365collaborative/d365fo.tools#387]
If we want to enable AzCopy transfer into the Asset Library (LCS), we need to expose a copy of `Start-LcsUpload` to end user.

We also need to expose a copy of `Complete-LcsUpload`

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed, because [Invoke-D365LCSUpload](https://github.com/d365collaborative/d365fo.tools/blob/master/d365fo.tools/functions/invoke-d365lcsupload.ps1) seems to cover this?

**Comment by Splaxi** [comment]
The original thought was something like:

What if you want to upload a massive file? This takes forever with the current implementation. As we already have some support for AzCopy transfers, we could just expose the inner workings and that way support a faster upload.

But it requires some signaling, for starting the upload, for LCS to return an endpoint (blob url), upload/transfer the file and then signal that the file has been uploaded/transfered.

As you can see on the age of the issue, we never got to fixing it - and no one ever requested it 🙈🙊🙉
