### ISSUE TITLE
Issue using Rename-D365Instance

### ISSUE THREAD

**Issue by MichaelPedersen1** [d365collaborative/d365fo.tools#39]
When using this command on a onebox dev vm I get the following error message.

Cannot find an overload for "Replace" and the argument count: "2".
At line:2 char:5
+     (Get-Content $File).replace($OldValue, $NewValue) | Set-Content $ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

The message appears three times and IIS service is restarted and active URL typed (unaltered).

Do I use the tool in the wrong way?

Thanks

**Comment by Splaxi** [comment]
Hi!

First:
Did you run the powershell console elevated? Also known as "Run As Administrator"?

I can see that you say you are running it on an onebox, which is the only support box.

Could you share your command with parameter values? If they are sensitive you can just replace the value with something else.

**Comment by Splaxi** [comment]
We just updated the logging for rename.

Could you install the latest version 0.3.71 and try again.

If it fails - please execute the below command

Get-PSFMessage | out-file c:\temp\D365Fo.Toolsmessages.txt

You can share the content of the file on pastebin and share the link to here. It will help us with helping you.

**Comment by MichaelPedersen1** [comment]
The PowerShell commands is running in the context of Administrator.


I have attached the content of the log file below.


Best regard,

Michael


Timestamp             FunctionName               Line Level   TargetObject         Message
---------             ------------               ---- -----   ------------         -------
8/21/2018 3:41:23 AM  d365fo.tools.psm1          32   Verbose                      Gathering all variables to assist...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          35   Verbose                      $Script:IsAdminRuntime: True
8/21/2018 3:41:23 AM  d365fo.tools.psm1          38   Verbose                      $Script:WebConfig: web.config
8/21/2018 3:41:23 AM  d365fo.tools.psm1          41   Verbose                      $Script:WifServicesConfig: wif.se...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          44   Verbose                      $Script:Hosts: C:\Windows\System3...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          47   Verbose                      $Script:DefaultAOSName: usnconebo...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          50   Verbose                      $Script:IISHostFile: C:\Windows\S...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          53   Verbose                      $Script:MRConfigFile: C:\Financia...
8/21/2018 3:41:23 AM  d365fo.tools.psm1          56   Verbose                      $Script:SqlPackage: C:\Program Fi...
8/21/2018 3:41:23 AM  Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 3:41:23 AM  Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 3:41:23 AM  Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          59   Verbose Microsoft.Dynamic... Fetched the D365 environment object
8/21/2018 3:41:26 AM  d365fo.tools.psm1          62   Verbose                      $Script:AOSPath: C:\AOSService\we...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          65   Verbose Microsoft.Dynamic... Extracting the DataAccess object ...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          68   Verbose                      $Script:DatabaseServer: localhost
8/21/2018 3:41:26 AM  d365fo.tools.psm1          71   Verbose                      $Script:DatabaseName: AxDB
8/21/2018 3:41:26 AM  d365fo.tools.psm1          74   Verbose                      $Script:DatabaseUserName: axdbadmin
8/21/2018 3:41:26 AM  d365fo.tools.psm1          77   Verbose                      $Script:DatabaseUserPassword: AOS...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          80   Verbose                      $Script:BinDir: C:\AOSService\Pac...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          83   Verbose                      $Script:PackageDirectory: C:\AOSS...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          86   Verbose                      $Script:MetaDataDir: C:\AOSServic...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          89   Verbose                      $Script:BinDirTools: C:\AOSServic...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          92   Verbose                      $Script:Url: https://usnconeboxax...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          100  Verbose                      $Script:ServerRole: Development
8/21/2018 3:41:26 AM  d365fo.tools.psm1          119  Verbose                      $Script:EnvironmentType: LocalHos...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          120  Verbose                      $Script:CanUseTrustedConnection: ...
8/21/2018 3:41:26 AM  d365fo.tools.psm1          123  Verbose                      $Script:IsOnebox: True
8/21/2018 3:41:26 AM  d365fo.tools.psm1          132  Verbose                      $Script:InstallationRecordsDir: C...
8/21/2018 3:41:26 AM  Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 3:41:26 AM  Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 3:41:26 AM  Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 3:42:11 AM  Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 3:42:11 AM  Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 3:42:11 AM  Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 3:42:26 AM  Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 3:42:26 AM  Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 3:42:26 AM  Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:00:41 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:00:41 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:00:41 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:00:50 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:00:50 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:00:50 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:01:05 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:01:05 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:01:05 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:01:12 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:01:12 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:01:12 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:01:21 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:01:21 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:01:21 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:05:57 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:05:57 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:05:57 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...
8/21/2018 11:06:06 AM Get-ApplicationEnvironment 4    Verbose                      Testing if we are running on a AO...
8/21/2018 11:06:06 AM Get-ApplicationEnvironment 17   Verbose                      Shadow cloning all relevant assem...
8/21/2018 11:06:06 AM Get-ApplicationEnvironment 50   Verbose                      All assemblies loaded. Getting en...





________________________________
Fra: Mötz Jensen <notifications@github.com>
Sendt: 21. august 2018 15:39
Til: d365collaborative/d365fo.tools
Cc: MichaelPedersen1; Author
Emne: Re: [d365collaborative/d365fo.tools] Issue using Rename-D365Instance (#39)


We just updated the logging for rename.

Could you install the latest version 0.3.71 and try again.

If it fails - please execute the below command

Get-PSFMessage | out-file c:\temp\D365Fo.Toolsmessages.txt

You can share the content of the file on pastebin and share the link to here. It will help us with helping you.

**Comment by Splaxi** [comment]
Hi Michael,

I think the content got cropped because of the e-mail reply.

Could you please upload the content to pastebin and share the link. Then we avoid losing details.

Cheers!

**Comment by MichaelPedersen1** [comment]
The link for pastebin entry. https://pastebin.com/W0tr2GU9

Thanks

**Comment by Splaxi** [comment]
Michale found a bug.

This has been fixed in 0.3.75.
