### ISSUE TITLE
Implement Invoke-D365SqlCmd

### ISSUE THREAD

**Issue by caleblanchard** [d365collaborative/d365fo.tools#397]
Right now there is a Invoke-D365SqlScript where you can pass in a script file. It would be nice to have the ability to pass the command directly without having to pass a sql script file.

I can write the function and submit the PR, I just need direction on if we should create a new function called Invoke-D365SqlCmd and change the $FilePath parameter to $Command, or if we should rename the existing command and allow passing either $FilePath or $Command similar to how the Invoke-SqlCmd cmdlet works in the SqlServer PS module.

**Comment by Splaxi** [comment]
Hi Caleb,

That's is actually a super idea!

I would vote for having 1 single cmdlet / function, but with 2 parametersets. One that takes a file and one the simply takes a string parameter with the SQL cmd / statement.

I'm voting for keeping the current name as is, so we don't introduce more breaking changes than need to be - but we could alias it with Invoke-D365SqlCmd if that would make you more eager to help with the task 😉

**Comment by caleblanchard** [comment]
Sounds good to me. I will work on adding new parameter to Invoke-D365SqlScript for -Command and create alias for Invoke-D365SqlCmd.

**Comment by Splaxi** [comment]
You only need to create the new capabilities. I'll sort out all the unit tests and what else is going to fail in our pipeline.

Just make it work on your machine and push it. Then we'll take it from there.

**Comment by Splaxi** [comment]
There is several other cmdlets / functions you could take inspiration from here in the module on how to handle parametersets. If you want to see how we have done it previously 😉

**Comment by Splaxi** [comment]
Should be fixed in 0.5.82...
