### ISSUE TITLE
Invoke-D365InstallLicense  - Fails on Sandbox tier 2 environment

### ISSUE THREAD

**Issue by shashisadasivan** [d365collaborative/d365fo.tools#406]
Not sure if this is standard, but when trying to run the invokeLicense on a Tier2 sandbox environment, it errors out with "Sql authentication is not enabled for server" (we always connect as a SQL user dont we?)

Full details of the command and output (Running this in the UAT environment) :
`PS C:\windows\system32> Invoke-D365InstallLicense -Path "D:\MyLicense.txt" -ShowOriginalProgress -DatabaseServe spartan-srv-oce-d365XPSprod-1231231231232.database.windows.net -DatabaseName db_d365XPSprod_20200210_11400048_1231 -SqlUser axdbadmin -SqlPwd 4uR9*$ut^6ld
04/01/2020 20:14:10: Failed to open SQL DB connection window authentication.
04/01/2020 20:14:10: Bindir: G:\AosService\PackagesLocalDirectory
MetadataDir: G:\AosService\PackagesLocalDirectory
SqlUser: axdbadmin
SqlPwd: 4uR9*$ut^6ld
SqlServer: spartan-srv-oce-d365XPSprod-1231231231232.database.windows.net
SqlDatabase: db_d365XPSprod_20200210_11400048_1231
Sql scripts:

04/01/2020 20:14:10: Failed to open SQL DB connection window authentication.
04/01/2020 20:14:10: Sql authentication is not enabled for server "spartan-srv-oce-d365XPSprod-1231231231232.database.windows.net".
04/01/2020 20:14:10: Bindir: G:\AosService\PackagesLocalDirectory
MetadataDir: G:\AosService\PackagesLocalDirectory
SqlUser: axdbadmin
SqlPwd: 4uR9*$ut^6ld
SqlServer: spartan-srv-oce-d365XPSprod-1231231231232.database.windows.net
SqlDatabase: db_d365opsprod_20200210_11400048_f51f
Sql scripts:

04/01/2020 20:14:10: Failed to open SQL DB connection window authentication.
04/01/2020 20:14:10: Sql authentication is not enabled for server "spartan-srv-oce-d365XPSprod-1231231231232.database.windows.net".
04/01/2020 20:14:10: The operation failed.
04/01/2020 20:14:10: The operation failed.`

**Comment by Splaxi** [comment]
Hi @shashisadasivan 

I wouldn't recommend that you run a command like `Invoke-D365InstallLicense` against a Tier2 environment.

Commands like that, is meant for Tier1 developer machines only.

**Comment by shashisadasivan** [comment]
Thank you @Splaxi , much appreciated
