### ISSUE TITLE
Set-D365Admin error

### ISSUE THREAD

**Issue by dusanhruby** [d365collaborative/d365fo.tools#407]
Hi,
I'm trying to run Set-D365Admin, result is:
PS C:\windows\system32> Set-D365Admin -AdminSignInName admin@somecompany.com -verbose
VERBOSE: [13:15:54][Set-AdminUser] MetaDataDirectory: G:\AosService\PackagesLocalDirectory
VERBOSE: [13:15:54][Set-AdminUser] Path to AdminFile: G:\AosService\PackagesLocalDirectory\Bin\Microsoft.Dynamics.AdminUserProvisioningLib.dll
VERBOSE: [13:15:54][Set-AdminUser] Adjusting parameter set to the PU that is in use in this environment.
VERBOSE: [13:15:54][Set-AdminUser] PU29 or higher found. Will adjust parameters.
VERBOSE: [13:15:54][Set-AdminUser] Updating Admin using the values admin@somecompany.com, AAD-Global, , , spartan-srv-emea-d365opsprod-xxxxxxxxxxxx.database.windows.net, db_d365opsprod_20200323_xxxxxxxx_xxxx, , , G:\AosSe
rvice\WebRoot\, https://xxxxxx.sandbox.operations.dynamics.com
[13:15:54][Set-AdminUser] Something went wrong while provisioning the environment to the new administrator: admin@somecompany.com. | Exception calling "Invoke" with "2" argument(s): "String cannot be of zero length.
Parameter name: oldValue"
WARNING: [13:15:54][Set-AdminUser] Stopping because of errors. | Something went wrong while provisioning the environment to the new administrator: admin@somecompany.com.

Running on Tier2 also Cloud-hosted Tier1.

Best regards

D.

**Comment by Splaxi** [comment]
Hi,

This command should never be run against a Tier2 environment.

What PU is your developer environment running? When you say Cloud Hosted, are you signed in with the admin account via RDP?

**Comment by dusanhruby** [comment]
Yes, it was on cloud-hosted and I was signed with admin account and it is PU33, but just I have found out is working without error. I'm sure I was logged on the same environment, don't understand why now is ok, sorry for bothering you :)

**Comment by Splaxi** [comment]
Not a problem at all, happy to help.

We have seen issues where the batch service cannot be stopped and that breaks things. But we can't report on that, because we simply hook into some code provided by Microsoft.

You restarted / rebooted the VM between your attempts, it would explain why it worked the second time...
