### ISSUE TITLE
BP check for all customizable modules/models

### ISSUE THREAD

**Issue by anderson-joyle** [d365collaborative/d365fo.tools#412]
Today I had to execute xppbp.exe for all customizable modules/models for a project.
Would it be a good idea to add some sort of argument to invoke-d365bestpractice.ps1 saying "export all customizable models"?

Thanks.

**Comment by Splaxi** [comment]
Hi @anderson-joyle 

Could you give us some more details what you are after?

Do you have X numbers of models, that you want to run xppbp.exe against? Do you need to run them against different base modules or the same base module?

Do you know of a way to list all customization models, so we can get some inspiration to work with?

**Comment by anderson-joyle** [comment]
You can tell if a model is customizable by looking to its descriptor file. Tag **Customization** can be set to Allow or DoNotAllow.

_Do you have X numbers of models, that you want to run xppbp.exe against? Do you need to run them against different base modules or the same base module?_

Thats right. Basically I had to invoke xppbp.exe for all models. I came up with the script below. Not pretty, but get the job done.

I pretty much read all descriptor files in **PackagesLocalDirectory** folder and, for those marked as ALLOW (for Customization tag), I build all arguments based on model name.


`
$metadataPath = "K:\AosService\PackagesLocalDirectory"
$outputPath = "C:\Temp\XPPBP"

$descriptorFolders = Get-ChildItem -Directory $metadataPath -Recurse

ForEach ($descriptorFolder in $descriptorFolders)
 {
    
    if ($descriptorFolder.Name -eq "Descriptor")
    {
        $descriptors = Get-ChildItem -File $descriptorFolder.FullName -Filter "*.xml"

        ForEach ($descriptor in $descriptors) {
            [xml]$XmlDocument = Get-Content -Path $descriptor.FullName

            $customization = Select-Xml -Xml $XmlDocument -XPath "//Customization"
            $model = Select-Xml -Xml $XmlDocument -XPath "//DisplayName"
            $module = Select-Xml -Xml $XmlDocument -XPath "//ModelModule"
            $xmlLog = Join-Path -Path $outputPath -ChildPath "$($model).xml"
            $car = Join-Path -Path $outputPath -ChildPath "$($model)-BPCheck.xlsx"

            $modelArg = “-model=$($model)”
            $moduleArg = “-module=$($module)”
            $metadaPathArg = “-metadata=$($metadataPath)”
            $packagesRootArg = “-packagesRoot=$($metadataPath)”
            $xmlLogArg = “-xmlLog=$($xmlLog)”
            $carArg = “-car=$($car)”


            if ($customization.Node.InnerText -eq "Allow")
            {
                 Write-Output "Processing $($module)-$($model). File output $($carArg)"

                Start-Process -FilePath "K:\AosService\PackagesLocalDirectory\bin\xppbp.exe" -NoNewWindow -Wait -ArgumentList $modelArg,$moduleArg,$metadaPathArg,$packagesRootArg,"-all",$xmlLogArg,$carArg 
            }
        }
    }
}`

Hope I make it more clear.

**Comment by Splaxi** [comment]
I got enough to work on something.

Cheers for taking the time to share your stuff!

**Comment by Splaxi** [comment]
I finally got a better understanding with the difference between modules / models.

I'll wrap it up for you over the next few days. You will get a new cmdlet, that will help you get what you are after. And then you should be able to pass into the `invoke-d365bestpractice` cmdlet

**Comment by anderson-joyle** [comment]
Awesome!

**Comment by Splaxi** [comment]
Newest release:

```powershell
Get-D365Model -CustomizableOnly | Invoke-D365BestPractice 
```

The `Get-D365Model -CustomizableOnly` gives a few more hits than your code. I don't know if the descriptor file is more correct than the Customize value on the model file it self, loaded like the D365FO platform would. I argue the latter is more correct, but you might feel different about that.
