### ISSUE TITLE
Switch-D365ActiveDatabase extra feature

### ISSUE THREAD

**Issue by jeroeneikmans** [d365collaborative/d365fo.tools#423]
When I restore a bacpac on a Tier-1 machine, the old AxDB database is renamed 'AxDB_original'. That's nice, but now I want to rollback/switch back. So I want to make the 'AxDB_original' database 'AxDB' again. It would be nice if Switch-D365ActiveDatabase could do that.

**Comment by Splaxi** [comment]
We had this request a few times, but never got around to fix it. 

Today was the day, but it will first be released in 24 hours time.

Will let you know when it is ready for download.

**Comment by Splaxi** [comment]
Part of 0.6.15

The example is included in the switch cmdlet.
