### ISSUE TITLE
New-D365Bacpac has problemes with = in SqlPwd

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#44]
If you have a SqlPwd like this "=B5*=ABCD**XXX" you will receive the following error when using New-D365Bacpac.

Exception setting "ConnectionString": "Keyword not supported: 'password=b5*'."
At line:38 char:5
+     $sqlConnection.ConnectionString = ($Params -join "")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting	

![image](https://user-images.githubusercontent.com/18070325/44813003-fa92a400-abd8-11e8-924e-696aff1447d2.png)

**Comment by Splaxi** [comment]
Single quotes should solve the problem. 

https://stackoverflow.com/questions/23014180/sql-server-2008-password-ending-in-a-semicolon

A hack for now could be
-SqlPwd "'=B5*=ABCD**XXX'"
Contains double and single quotes. Double quotes to tell powershell this is a text and single quotes to tell the sql connection that this is the entire string for the password.

**Comment by PaulHeisterkamp** [comment]
Thanks Mötz! The "hack" works fine...
Enjoy you vacation!

**Comment by Splaxi** [comment]
Great to hear!

You could create a pull request where you fix this issue in the internal get-sql command 

I'll help you with it if you want 😊

**Comment by PaulHeisterkamp** [comment]
I will try to find some time today :-)

**Comment by Splaxi** [comment]
So @PaulHeisterkamp - did you find some time to fix this little issue? :)

**Comment by Splaxi** [comment]
Fixed in 0.3.88

**Comment by PaulHeisterkamp** [comment]
Great! Sorry for the late response but it’s a busy time...
