### ISSUE TITLE
Disable flight docs has wrong link

### ISSUE THREAD

**Issue by AndreasVolkmann** [d365collaborative/d365fo.tools#443]
The docs on `d365fo.tools/docs/Disable-D365Flight.md` has the wrong link in the title.
https://github.com/d365collaborative/d365fo.tools/blob/master/docs/Disable-D365Flight.md

It links to the temp db clean up (https://msdyn365fo.wordpress.com/2019/12/18/cleanup-tempdb-tables-in-a-msdyn365fo-sandbox-environment/)

**Comment by Splaxi** [comment]
Thanks for sharing that.

We can't explain why, because the source code doesn't have that mentioned link in it. But we managed to fix it. It will be updated with the next release.
