### ISSUE TITLE
New-d365isvlicense errors out on local VHD

### ISSUE THREAD

**Issue by Alpa-Chino** [d365collaborative/d365fo.tools#444]
![ftoolslicenserrormsg](https://user-images.githubusercontent.com/54580225/87123157-84583180-c286-11ea-96e4-1dfc79d7b940.PNG)

I'm admin on this machine and I'm running as and administrator, so it shouldn't have a problem with acccess rights to create that extractionpath/licensemergepath for this command :
Get-ChildItem -Path $licenseMergePath | Remove-Item -Force -ErrorAction SilentlyContinue

**Comment by Splaxi** [comment]
Hi @Alpa-Chino,

I'll take a look later today, to see if I missed anything.

**Comment by Alpa-Chino** [comment]
Hi Mötz!

Did you manage to take a look at it? Let me know if you need some help in repro etc.

**Comment by Splaxi** [comment]
My initial test did not yield the same result as yours.

So a more detailed repo with scripts would be very helpful

**Comment by Alpa-Chino** [comment]
Hi!

I figured out what is the problem: The package provided by the isv does not contain a License folder under AOSservice/Scripts.
Creating the folder if does not exists helped:
$licenseMergePath = Join-Path $packageTemp "AosService\Scripts\License"
        if (Test-Path -Path $licenseMergePath) {
            Get-ChildItem -Path $licenseMergePath | Remove-Item -Force -ErrorAction SilentlyContinue
        } else {
            $null = New-Item -Path $licenseMergePath -ItemType Directory -ErrorAction SilentlyContinue
        }
        Write-PSFMessage -Level Verbose -Message "Copying the license file into place.

**Comment by Alpa-Chino** [comment]
I assume the original scenario for this script was that here is a package with an expired license, lets swap it with the new one.
Well, we got an "licenseless"deployable package and a license file from one of the ISV s (we asked them, because we have multiple common customers and the packages are the same only the licenses differ) and we are the ones creating the All-in-ONe package. (with licenses, that's what im testing now actually)

**Comment by Splaxi** [comment]
What the original scenario was, is hard to say, because it was created a late night, because of an ISV that didn't provide a fully working package.

I'm guessing that the code you provided, should be implemented and that it would help with your scenario - right? Will you do the PR and get the fame or should I just uptake it and make it part of the release?

**Comment by Alpa-Chino** [comment]
I am pretty new to GitHub so I'm just acclimatizing to the etiquette here :) I would not want to force something into "your" repo.
I will prepare a pull request soon.

**Comment by Splaxi** [comment]
You're not forcing anything in 😉

I just want to make sure that we get the update into the module, so I can support your scenario along the already implemented scenario and I don't want you to feel overwhelmed by Git / Github.

Let me know if you need anything.

**Comment by Alpa-Chino** [comment]
I did the changes as described here https://github.com/d365collaborative/d365fo.tools/wiki/Branching
but when publishing the branch it says i dont have write access to the d365collaborative/d365fo.tools  and offers to fork.
I did the exact steps as described, all looked fine. What im missing?

**Comment by Splaxi** [comment]
You need to fork to a repository on your Github account, that way you have a connected repository.

You can now push code changes from your local git repository on your machine, to your connected repository. 

From that you do a pull request, between your connected repository and our repository. 

From there I'll take over and make sure our testing works as desired. 

Just ignore any errors on the pull request, until I get back to you. We have some unit tests that protects us from accidental changes, but we auto generate several of these things when we merge your changes.

**Comment by Alpa-Chino** [comment]
Done, sent a PR. Hope everything is ok!
How much it takes for the change to reach the "published" status?

**Comment by Splaxi** [comment]
If everything just works out and I feel it helps, it will be release in the next 1-2 hours for the entire world.

If you want credits for your work, I need your name and your twitter handle, so I can add that to the file, and that way give credit.

**Comment by Splaxi** [comment]
You can now delete your local branch and your "AlpaChino-N365new-d365isvlicensefix" branch on your repository, because I've merged your PR into our code base.

Just waiting for your details, if you want to get credit for the work you did. When I've that, I'll publish it.

**Comment by Alpa-Chino** [comment]
Sorry i im asking dumb questions: What type of details are usually provided? :D

**Comment by Splaxi** [comment]
Your First name and last name, and your Twitter handle, so people can connect with you and I can give you a shout out 😀

It's fair if you don't want that details shared with the public, but I strive to be transparent to who did help out and improve the tools 😁

**Comment by Alpa-Chino** [comment]
Szabolcs Eötvös and i don't have twitter account :D

**Comment by Splaxi** [comment]
You should get one, so we could stay connected and help each other of with stuff.

I'll add your name and publish it. Thanks for taking the time to troubleshoot it and even provide a PR with the fix 🤘

**Comment by Alpa-Chino** [comment]
I m usually active at the Finance and Operations Insider program yammer. I know yammer's follow function is not really working, but you can connect there. Expect some more feedback from us, we just started switching some of our scripts with yours, it's under testing so probably I'll be reaching out soon 😃

**Comment by Splaxi** [comment]
I'm looking forward to that! I love feedback and I hope we can help each other out to make it even better 😉
