### ISSUE TITLE
Please add -PackagesRoot to New-D365CAReport

### ISSUE THREAD

**Issue by jeroeneikmans** [d365collaborative/d365fo.tools#445]

**Comment by Splaxi** [comment]
Hi @jeroeneikmans 

Could you please share a bit more details about that parameter? What does it do that we don't already support? 🤔

**Comment by Splaxi** [comment]
Is it related to this issue?

https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/304933/customisation-analysis-report-car

**Comment by jeroeneikmans** [comment]
Yes that is exactly the issue. In invoke-d365bestpractice.ps1this is already implemented.

**Comment by Splaxi** [comment]
Will be released later today.

**Comment by Splaxi** [comment]
0.6.21 contains the change..
