### ISSUE TITLE
Path not found when running New-D365Bacpac on Devbox

### ISSUE THREAD

**Issue by HerreSch** [d365collaborative/d365fo.tools#446]
Installed D365FO Tools on a newly deployed cloud hosted box. Seemed to work fine, until the process was aborted with the following error message. 

C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe path wasn't found.

The path seems to be 130 (there is nothing really in the 140 folder. I have upgraded SSMS.

**Comment by Splaxi** [comment]
Hi @HerreSch 

You should run the install sqlpackage cmdlet, and then try again. 

Otherwise there is a set sqlpackage path cmdlet, so you can update the location / path to the sql package that is part of your SSMS installation.

**Comment by Splaxi** [comment]
Hi @HerreSch 

Did you manage to get things going or do you need some assistance? I'm more than willing to help you out and make sure things are working like they should or your machine.

Otherwise I'm going to close this issue next week.

**Comment by HerreSch** [comment]
Hi Motz, yes, thank you. Have started to experiment  a bit with D365FO tools and did get it working. The whole thing with SQL versions seems to be a bit of a mess, as there are different versions on some older sandboxes it seems (though I am not 100% why they differ). Did get it to work though! Thanx for the help and keep up the good work. 
Cheers
