### ISSUE TITLE
Build missing files. 

### ISSUE THREAD

**Issue by xi-osman** [d365collaborative/d365fo.tools#449]
Question so I'm able to build a model but the model also has html and js resources but these do not get moved over to the WebRoot. What command am I missing? 

Currently running this to build. 
```Invoke-D365ModuleFullCompile -Module```

**Comment by xi-osman** [comment]
Figured a way to deploy the resources but I have to use Visual Studio to build or use the command line to build.
![image](https://user-images.githubusercontent.com/463779/89132216-35de3180-d4d8-11ea-8d51-7f926a13414c.png)
Is there a command or flag I need to add on ```Invoke-D365ModuleFullCompile``` to deploy resources like the highlighted text from above?

**Comment by Splaxi** [comment]
Hi @xi-osman 

Thanks for reaching out! This is the first time anyone actually requested something like that.

So your solution contains HTML and JS files, that you want be compiled and then "deployed" to the output folder of the module?

Could you share some more screenshots of the expected behavior, so I can learn more about your scenario?

Would it be a solution if we could wrap the devenv command that you just shared, into the module? That way we could keep what we already have and don't break stuff, while giving you some tools to work with.

**Comment by xi-osman** [comment]
Hey @Splaxi 

My solution contains an [extensible control](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/build-extensible-control) this way we are able to create something custom that's where HTML and JS comes in. For our development flow we have these Review machines where we automated a build of our branch (We use GIT). But the static files never made it into the WebRoot\Resources\Html and this makes it hard to review since we now have to log on the machine and do a build again. 

Build via Power Shell using d365fo.tools
![image](https://user-images.githubusercontent.com/463779/89193544-bf8b0f00-d56b-11ea-8548-16313a32a809.png)


Build via Visual Studio or devenv using a VS sln 
![image](https://user-images.githubusercontent.com/463779/89193148-307df700-d56b-11ea-9331-49cf084e3962.png)

Or if I can replicate what this tool can do that would be more great. 
![image](https://user-images.githubusercontent.com/463779/89193672-f3fecb00-d56b-11ea-815d-10b793ec3695.png)

Unless I'm doing this process wrong. Would I have to build, create package then apply package? Hope this gives you enough info and I do apologize for censoring a lot just don't want to share our company's code :)

**Comment by Splaxi** [comment]
I'm closing this issue.

I believe the tools are not capable of fixing this for you and you should look for the solution in some of the public tools provided by Microsoft.
