### ISSUE TITLE
Time variable is missing

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#45]
This statement fails on version 0.3.87

https://github.com/d365collaborative/d365fo.tools/blob/b981f2f3e04eba4dc6839e2b29a6033caaeb9568/internal/functions/invoke-azurebackuprestore.ps1#L51

The Time variable is not present and the SQL fails.

**Comment by Splaxi** [comment]
Found the issue and have implemented it in 0.3.89...

**Comment by Splaxi** [comment]
Please check and test again :)

**Comment by skaue** [comment]
Yea, I was showing this to a colleague and it all broke down.... complete demo failure... no worries, though. Easy to fix and resolve, and report back...

**Comment by Splaxi** [comment]
Will close the issue, as we expect it to work like planned :)
