### ISSUE TITLE
Service Fabric Topology Automation

### ISSUE THREAD

**Issue by MeritJB** [d365collaborative/d365fo.tools#457]
We are looking to investigate some refresh automation against service fabric ("self-service") style environments. When in "classic" environment types we had control over VMs that were part of the topology, now under service fabric there JIT access controls as well as no RDP access to AOSs. So we are looking for design alternatives to accomplishing automation that has DB movements and SQL queries at their core.

Any community help would be greatly appreciated!!

**Comment by Splaxi** [comment]
Hi,

We are all in the same boat with the Self-Service environments.

Moving databases from PROD -> Tier2 is fully supported by the LCS API. The same goes for exporting a bacpac from Tier2 -> LCS Asset Library, but with a little caveat. You don't get to connect to the Azure Database prior the export, which is what I believe you are looking for.

Let me start by asking: Why do you need access to the Azure DB for the Tier2? If you just want to delete data from a selected list of tables, we can do that directly against the bacpac file, before we make it available for any Tier1 environments.

If you want to mask data, clean specific columns or update configuration details, you will need to look into Power Automat UI Flow. The UI Flow will be able to click on the buttons inside LCS, both enabling the access (IP address) and click on the JIT, so you can refresh the page, and collect all the details from the page. So I would argue that it is more than doable, but it will take you some testing and designing of the end-2-end process, before it just works.

If you could share your overall scenario and be as specific as possible, I might be able to pitch you some ideas.

**Comment by MeritJB** [comment]
Good Morning!
Thanks for the great ideas. Just to round it out this is the use case we're looking for:
Production get's refreshed to a Tier 2 automatically (which we know can happen via the LCS API), after the refresh in the T2 some tables get cleared out and some other tables have configuration edited (which we've been doing with simple SQL queries.

We did this all on one VM since it was easier to not segregate that, but the times of the various scripts were staggered to allow for processing.

As I read this, one idea comes to mind, since you note "_...we can do that directly against the bacpac file..._" Instead of a refresh then SQL edit; we do an export, bacpac manipulation, then import. I suppose it all depends on the level of edit potential we have on the bacpac file.

**Comment by Splaxi** [comment]
The only edit potential we have is full delete directly in the bacpac file. Data is stored in a binary manner, optimized for speed.

You could fake it, by having a bacpac from the destination environment exported and extract the data files from that file. Then when you deleted the data from the bacpac file, you could inject the data files for the tables where you want the configuration to be updated.

The Tier2 will not have its configuration data updated before the export, which could be a show stopper for you. More and more customers / partners creates a custom service endpoint, that you call directly after the Tier2 has been refreshed with data. That way you can update your configuration as needed, before the export.

Some use OData if possible, along with DMF - but the custom service endpoint offers you more flexibility, but comes with a price.

A way to have access to the Tier2 after the data refresh, is to have a permanent Registered Application configured in PROD, that is using the admin account. Then you can use that to communicate with OData, DMF or the custom service endpoint, fully automated.

**Comment by MeritJB** [comment]
I like were these ideas are going. Few questions.
_More and more customers / partners creates a custom service endpoint, that you call directly after the Tier2 has been refreshed with data_
and
_have a permanent Registered Application configured in PROD, that is using the admin account. Then you can use that to communicate with OData, DMF or the custom service endpoint, fully automated._

So the source environment (Prod) will have the same Admin user and same AAD app registered as the target (refreshing between the two obviously ensures this, and the two different URIs in the app registration configuration will ensure Prod's security). So I think a few use case examples of how we can use the custom service endpoint would really solve this. We don't need any configuration saved out of the target **before** the refresh, only some minor config **afterwards**. things like:
- Enabling a subset of users, and changing their theme.
- Changing subset of batch job's status.
- Purging AAD registrations (obviously except the one on the table here).

If we can discuss some non-SQL examples of the above, I would greatly appreciate it.

**Comment by Splaxi** [comment]
Enabling a sub set of users and changing their theme should be doable with OData directly, if I'm not mistaken.

Batch jobs exists as a OData entity, but it is readonly. I heard rumors about some capabilities to work with batch jobs from outside D365FO, or maybe it was just to see their state. This would require you to extend the current OData entity or create a custom service, that accepts a list of batch job rec ids, that you would like enabled.

The AAD registration is the same story. This time it exists as a DMF entity only, so you would have to extend it to a OData entity or go down the path of a custom service once more.

Nothing of what you listed is major things, as long as you are willing to develop your own custom service, that has 1 method per task that you want to automate / complete, so we can call it directly after the data refresh.

**Comment by MeritJB** [comment]
Thank you for the insights!  I'm going to go back with my dev team and see what the best custom service path forward might be. I think consolidating efforts into a set of services as opposed to using different methods for redacting/changing different components would be more elegant long term, with the extra overhead of development up front.
THANK YOU!

**Comment by Splaxi** [comment]
Looking forward to hear where you end up. I'm confident that it will work, you just need to figure out how you want it implemented and how it fits into your project.

Let me know if you hit any road blockers, I'm happy to pitch some ideas.

**Comment by dorianm** [comment]
Hi @Splaxi, I don't have much experience with D365 F&O/LCS and I'm stuck to automate sandbox environment refresh. I would like to automate the process but it seems to be difficult and this conversation is one of the most advanced I found about this subject 👍 

Do you know if there is any example of custom web service used to configure F&O after an environment refresh ? The [Microsoft documentation](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-general-refresh) evokes this solution but without example : 

> To complete this reconfiguration more quickly, we recommend that you build a custom web service endpoint that can be called on demand after the refresh is completed. An example of this type of web service will be added in a future update of this article.

Thank you in advance for your help 🙏

**Comment by Splaxi** [comment]
@dorianm 

Please start a new thread, and put in as many details as you can - then we can take it from there. I would recommend it to be a Discussion thread instead of an Issue 😉

Are you on the private yammer group that is provided by Microsoft for all partners and customers working with D365FO? There are several threads in there, that could be of interest to you...

**Comment by dorianm** [comment]
@Splaxi, thank you for your answer. I hesitated to open a new discussion about this subject. I'm going to try to have access to the private Yammer group to get more information then I'll open a new discussion if still needed. Thank you very much 🙂
