### ISSUE TITLE
Switch-D365ActiveDatabase Better Error Handling

### ISSUE THREAD

**Issue by ITRasmus** [d365collaborative/d365fo.tools#46]
When using Switch-D365ActiveDatabase and the database specified in NewdatabaseName does not exists, it does not rollback the rename of the original Database,

**Comment by Splaxi** [comment]
What about testing for existing db before rename?

**Comment by Splaxi** [comment]
Implemented a select against the new database, for the userinfo table. If it fails the cmdlet exit from now on. Should be fixed in 0.3.99
