### ISSUE TITLE
command.ps1

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#461]
Hello Motz

we found an issue in the last version 0.6.24

the enum "LcsAssetFileType" is duplicate in the file command.ps1 so the module cannot be load anymore

![image](https://user-images.githubusercontent.com/40988263/92255363-816a6d80-eed2-11ea-96fd-ce79a8c4ff77.png)

i don't know how you generate this file because it's not part of the git repository

Have a good day
Charles

**Comment by Splaxi** [comment]
Ah!

I'll fix it!

**Comment by Splaxi** [comment]
The fix should be on the way.

Please let me know if you still have issues.

**Comment by Splaxi** [comment]
The final fix is part of 0.6.27 - Please test it out and let me know.

Will close the issue, but feel free to open it if you still have issues.

**Comment by Shind44** [comment]
Hello Motz, it's ok for me thanks
