### ISSUE TITLE
 Import-D365AadUser broken because of breaking change in Microsoft.Dynamics.AX.Security.SidGenerator.dll in PU37

### ISSUE THREAD

**Issue by gertvdh** [d365collaborative/d365fo.tools#463]
It seems PU37 broke the  Import-D365AadUser functionn we are getting error

[Get-UserSIDFromAad] Something went wrong while working against the database | Cannot convert argument "sidAlgorithm", with value: "https://sts.windows.net/", for "Generate" to type "Microsoft.Dynamics.Ax.Security.SidGenerator+SidAlgorithm": "Cannot convert value "https://sts.windows.net/" to type "Microsoft.Dynamics.Ax.Security.SidGenerator+SidAlgorithm". Error: "Unable to match the identifier name https://sts.windows.net/ to a valid enumerator name. Specify one of the following enumerator names and try again:

Get-UserSIDFromAad is using $SID = [Microsoft.Dynamics.Ax.Security.SidGenerator]::Generate($SignInName, $Provider)

but that method has a 3th parameter now:

public static string Generate(string email, string domain, SidGenerator.SidAlgorithm sidAlgorithm)

**Comment by Splaxi** [comment]
Thanks for letting me know @gertvdh 

I'll see if I can find a fix for that, so we can get it to work on PU37.

If you find any more details, it would be awesome if you could share it.

**Comment by gertvdh** [comment]
That third parameter is an enum with one value, so if you pass that, it seems to work again. Sad that MS did not default the parameter

**Comment by gertvdh** [comment]
default could be [Microsoft.Dynamics.Ax.Security.SidGenerator+SidAlgorithm]::Sha1

**Comment by Splaxi** [comment]
Will do a fast release, so we get things back on track.

I'll ping you here, so you can download the latest release and test it once more.

**Comment by Splaxi** [comment]
v.0.6.28 contains the fix!

**Comment by Splaxi** [comment]
Oh.

I forgot, we need to support all versions, so it works for older versions as well. Let me fix that.

**Comment by gertvdh** [comment]
it works already with v.0.6.28

**Comment by Splaxi** [comment]
So you tested with 0.6.28 against the PU37 - right?

My concern is that all other people will not have the same bits installed, and then our code will fail. I'm going to see if I can find a way to test if we are on PU37 or not, to run either the old code or the new code, based on your findings.

**Comment by gertvdh** [comment]
indeed, tested on PU37

**Comment by gertvdh** [comment]
works for PU37 and also for lower version in 0.6.29

**Comment by Splaxi** [comment]
👍
