### ISSUE TITLE
If hotfix bundle is a file, the script should not expect it to be a folder

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#47]
The script is testing the path as if it was a folder and not a file. This causes this script to fail in my testing.

https://github.com/d365collaborative/d365fo.tools/blob/be2da00231306a527d9f7bc4be6caf5a169f25e3/functions/invoke-d365scdpbundleinstall.ps1#L67

**Comment by Splaxi** [comment]
Ah!

You're right! 

Will fix first thing tomorrow morning 😊

**Comment by Splaxi** [comment]
Fixed in 0.4.03
