### ISSUE TITLE
Implement a way to import Azure Active Directory application entries

### ISSUE THREAD

**Issue by gertvdh** [d365collaborative/d365fo.tools#473]
To enable OData and Custom services invocation, you should link a user/clientid in FinOps. 
Maybe Import-d365aadapplication is a good name?

This function would add one based on given parameters:
- ClientId
- Name
- UserId

**Comment by Splaxi** [comment]
Hi @gertvdh 

Are you looking for a way to do it on a Tier1 box? Would doing it via SQL be okay? Do you know the table name we should look into?

**Comment by gertvdh** [comment]
yep, only Tier 1, so SQL is the way. I will make a pull request

**Comment by Splaxi** [comment]
0.6.32 will contain this. Should be available 10 minutes from now.
