### ISSUE TITLE
trailing / in URL parameter in the command Send-D365BroadcastMessage

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#479]
trailing / in URL in the command

`
Send-D365BroadcastMessage -Tenant '$(AzureTenantId)' -ClientId '$(AzureApplicationId)' -ClientSecret '$(AzureApplicationSecretKey)' -URL '$(d365foEnvironmentURL)' -EndingInMinutes 5 -TimeZone '(UTC) Coordinated Universal Time - [Coordinated Universal Time]' -Verbose
`

So, if the URL address has a trailing "/" (ex: https://environmentnameaos.cloudax.dynamics.com/) it fails. 
if it doesn't have a trailing "/" (ex: https://environmentnameaos.cloudax.dynamics.com) it works. 

P.S. 
* It is a low priority
* related #254

BTW, is it possible to Install only this command? I.e. instead of Install-Module d365fo.tools, write something like the following Install-Module d365fo.tools.Broadcast
I use only this command on an Azure pipeline where D365FO instance and SQL server are not available. And I don't need a full set of commands. It will reduce the model download and installation time.

**Comment by Splaxi** [comment]
I'll get it fixed.

I've been wondering about the same, having a smaller edition of the tools, to lower the install / load time.

But I have seen proof that we could download the module faster, even with the same size, and the load time isn't that bad. 

You could create a spin off module, where you define what you need and don't, and that way lower installation and load times. 

Let me see if I can find the test where the download is faster and share it with you.

**Comment by Splaxi** [comment]
This might be something you can look into:

https://twitter.com/JustinWGrote/status/1172636154404818944

**Comment by Splaxi** [comment]
This one is fixed in the lastest release.

**Comment by valerymoskalenko** [comment]
Thanks!

Regarding decreasing installation time, I think it doesn't really matter. Execution of the full script takes about 50 seconds. I don't think that somebody feels the difference if I decrease it for a couple of seconds. ;-)
