### ISSUE TITLE
Improve Set-D365StartPage command

### ISSUE THREAD

**Issue by artemt1** [d365collaborative/d365fo.tools#48]
Please extend the command, so it will do few more steps:

1. Show Favorites bar in IE
2. Lock the Favorites Toolbar 
![image](https://user-images.githubusercontent.com/29033930/45472596-f87e2880-b734-11e8-92fe-fabc19a9a51b.png)
3. Add new favorites with the name "D365FO" and url equal to the current instance. End result will look like this:
![image](https://user-images.githubusercontent.com/29033930/45472674-35e2b600-b735-11e8-9447-00a28d8911a3.png)

**Comment by Splaxi** [comment]
Great idea.

Could you spend some time and find out how to do it by hand, using the registry. 

That would ease the work for us and help us to provide a solution to you.

If that is beyond your skills we will look into this when we have free time.

**Comment by artemt1** [comment]
Show favorites bar in IE:
[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\MINIE]
"LinksBandEnabled"=dword:00000000

Lock the toolbar
[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\] 
"Locked"=dword:00000001

Favorites are stored at:
C:\Users\Administrator\Favorites\Links
Example favorites attached.
[D365FO.zip](https://github.com/d365collaborative/d365fo.tools/files/2378642/D365FO.zip)

**Comment by Splaxi** [comment]
Great stuff!

Will look at it either tonight or tomorrow night. 

Most like it will be a new cmdlet, so you will have to run 2 different cmdlets.

**Comment by artemt1** [comment]
Should be fine.

**Comment by Splaxi** [comment]
Should be fixed in 0.4.07

Set-D365FavoriteBookmark
