### ISSUE TITLE
Import-D365Bacpac -ImportModeTier2 get an error

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#49]
If you want to use Import-D365Bacpac -ImportModeTier2 you will receive the follwing error:
Import-D365Bacpac : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Import-D365Bacpac -ImportModeTier2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-D365Bacpac], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Import-D365Bacpac

**Comment by Splaxi** [comment]
Could you share the entire cmdlet and parameters you executed?

Just replace sensitive information with dummy values...

**Comment by PaulHeisterkamp** [comment]
You will get the error if you execute only Import-D365Bacpac -ImportModeTier2, so there is no question for the mandatory parameters.
The full command you used is the following:
Import-D365Bacpac -ImportModeTier2 -BacpacFile "XxxxX" -NewDatabaseName "XxxxX" -DatabaseUserName sqladmin -DatabaseUserPassword "XxxxX" -AxDeployExtUserPwd "XxxxX" -AxDbAdminPwd "XxxxX" -AxRuntimeUserPwd "XxxxX" -AxMrRuntimeUserPwd "XxxxX" -AxRetailRuntimeUserPwd "XxxxX" -AxRetailDataSyncUserPwd "XxxxX"

**Comment by Splaxi** [comment]
On its own this cmdlet doesn't make sense 
Import-D365Bacpac -ImportModeTier2

Did you expect to be prompted for the bacpac file path or did you put that in, like this:

Import-D365Bacpac -ImportModeTier2 -bacpac "c:\temp\config.bacpac 

Just trying to make sure you share the exact command you executed when you got the error.

**Comment by PaulHeisterkamp** [comment]
Ahh now a got it. The parametername for the bacpac file path has been changed from -BacpacFile to -bacpac

**Comment by Splaxi** [comment]
Yeah, we are trying to simplify stuff.

Still learning how to name the parameters. 

Sorry for the inconvenience we caused!

**Comment by Splaxi** [comment]
Will close the issue next week if you don't make any updates.

**Comment by PaulHeisterkamp** [comment]
Thanks Mötz! You can close the issue now...
