### ISSUE TITLE
Invoke-D365LcsApiRefreshToken no clientId

### ISSUE THREAD

**Issue by jfranch** [d365collaborative/d365fo.tools#496]
I'm trying to call function Invoke-D365ApiRefreshToken and getting ClientId missing error:
![image](https://user-images.githubusercontent.com/28339621/102344207-d91d7800-3f9b-11eb-89c0-0ca5ff63772c.png)

Previously I asked for a token without issues:
![image](https://user-images.githubusercontent.com/28339621/102344591-6a8cea00-3f9c-11eb-97a9-70d7d23e1f1d.png)

Maybe I'm missing something?

**Comment by Splaxi** [comment]
Looking at the help for `Set-D365LcsApiConfig`

```powershell
Get-Help Set-D365LcsApiConfig -Full

SYNTAX
    Set-D365LcsApiConfig [[-ProjectId] <Int32>] [[-ClientId] <String>] [[-BearerToken] <String>] [[-ActiveTokenExpiresO
    n] <Int64>] [[-RefreshToken] <String>] [[-LcsApiUri] <String>] [-Temporary] [<CommonParameters>]
```
 
So you need to store the ClientId with `Set-D365LcsApiConfig`, if you don't want to avoid having to specify it.

Note that you're calling `Get-D365LcsApiToken` with the -ClientId, which explains why it works. But when setting your details with `Set-D365LcsApiConfig`, you're not providing the -ClientId for the `Set-D365LcsApiConfig`.

```powershell
#This will set all parameters that you can avoid specifying again.
Set-D365LcsApiConfig -ClientId -LcsApiUri -ProjectId

#This pulls a fresh token, and stores the BearerToken, RefreshToken and the ActiveTokenExpiresOn values
Get-D365LcsApiToken -Username -Password | Set-D365LcsApiConfig

#This will pull a fresh token, and stores the BearerToken, RefreshToken and the ActiveTokenExpiresOn values
Get-D365LcsApiConfig | Invoke-D365LcsApiRefreshToken | Set-D365LcsApiConfig
```

**Comment by jfranch** [comment]
Thanks @Splaxi , I didn't found this doc.

**Comment by Splaxi** [comment]
It might be a bit unclear, if you only look at a single command.

But Get-help will so you everything I have documented.

**Comment by Splaxi** [comment]
This wiki page shows you some of the same steps.

https://github.com/d365collaborative/d365fo.tools/wiki/How-To-Download-Latest-Bacpac-From-Lcs

**Comment by jfranch** [comment]
Hi, of course get-help shows a very well structured and plenty documentation. In this case I don't pay attention on optional parameters. The problem is not the documentation.
