### ISSUE TITLE
Implement cmdlet to fetch exposes services

### ISSUE THREAD

**Issue by Splaxi** [d365collaborative/d365fo.tools#5]
Implement Get cmdlet that pulls the json data from "/api/services"

Based on:
http://www.ksaelen.be/wordpresses/dynamicsaxblog/2016/01/dynamics-ax-7-tip-what-services-are-exposed/

**Comment by ITRasmus** [comment]
Hi
It is possible to use the get-ODataEntity with Entity api/services for the list of what services are exposed.
Should we not just keep it there, and then make a reference in the wiki ?

**Comment by Splaxi** [comment]
Hi

Can it be done through the rest api with client id and client secret?

I agree that this should belong to integrations, but while building custom services and maybe debugging them, it would be a great tool to have at hand in tools. 

We might have to do overlapping cmdlets, if the use case is strong enough. 

I would expect that we just want to query the URL as the context of the executing user. 

Am I way of with this approach?

**Comment by ITRasmus** [comment]
Hi
Yes it can be done with the client id and secret.
There is already implemented the webrequest needed for the query inside the tools module.
It will only take a little rewriting of the webrequest, and then off cause the code for the public method.
If we implement it with parameters for the client id and secret and then default the server url, it will be more easy to use.
So lets implement it and see what happens.
