### ISSUE TITLE
Import-D365Aaduser not working

### ISSUE THREAD

**Issue by Asiasasif** [d365collaborative/d365fo.tools#50]
I just tried the import-D365Aaduser and it throwed me an error. Screenshot attached. Launched powershell as Admin 
 DB owner access to AXDB for local admin account
 AAD user whose creds given when running the script has sysadmin 

 This is a cloud-hosted tier1 box
![error](https://user-images.githubusercontent.com/43236846/45482313-56c5fe00-b76b-11e8-895e-93670fee5ca1.PNG)

**Comment by Asiasasif** [comment]
I am running the below command

Import-D365AadUser -Users “**************@AVAAX7CTP7.onmicrosoft.com<mailto:**************@AVAAX7CTP7.onmicrosoft.com>”


[cid:image001.png@01D44B7C.D0A243B0]

Thanks,
Asif

**Comment by ITRasmus** [comment]
It looks like the user is containing a little more than just email@domain.com ?
Since we haven't teste the the SID generation with a onmicrosoft.com account
Could you try to use Get-PSFMessage and the post the result on pastebin and share the link.
Just remove all sensitive information fist.

**Comment by Splaxi** [comment]
From my point of view it looks like you copied to much into the parameter.

Import-D365User -Email "**************@AVAAX7CTP7.onmicrosoft.com" should work.

Please make sure you are only fill in the email address...

**Comment by ITRasmus** [comment]
Hi
Could i get you to try the function
Get-D365UserAuthenticationDetail "TheEmailYourAreTryingToImport" 
Please validate the result from function is correct or if there is an error please provide the error.

**Comment by Asiasasif** [comment]
Here is the result
Name                           Value
----                           -----
SID                            S-1-19-2398807710-3303502795-3208750774-1189134640-2456150598-2864208061-3273002221-3047239075-1510753007-4079435192
InstanceProvider               https://sts.windows.net/AVAAX7CTP7.onmicrosoft.com/
NetworkDomain                  https://sts.windows.net/
IdentityProvider               https://sts.windows.net/

**Comment by ITRasmus** [comment]
I have pushed a new version to powershellgallery, where the verbose logging is extended a little.
Could you try to update-module d365fo.tools 
import-module d365fo.tools -passthru
Then make sure it is 0.4.05
Then try again to import user again
the use the GET-PSFMEssage -Level Verbose and post the result

**Comment by Asiasasif** [comment]
Result after update and import user command

9/14/2018 10:24:36 AM Get-SQLCommand             36   Verbose System.Collection... Building the SQL connection string.
9/14/2018 10:24:36 AM Import-D365AadUser         135  Verbose                      Trying to connect to the Azure Active Directory
9/14/2018 10:24:52 AM Import-D365AadUser         199  Verbose                      Getting tenant from .

**Comment by ITRasmus** [comment]
Is Getting Tenant from . really the last message you got  ?
Is the . because there you removed the email ?
When you remove sensetive information please write something else so i can see the it acutalle wrote something insted of it just being blank.

**Comment by Asiasasif** [comment]
Yes, I gave the below command and that's the only message I got.

Import-D365AadUser -Users "acpcloud359@AVAAX7CTP7.onmicrosoft.com"

 Attached is the screenshot as well
![error](https://user-images.githubusercontent.com/43236846/45546727-ad841400-b80d-11e8-8f49-01e1c8776a68.PNG)

**Comment by ITRasmus** [comment]
Hi
I have released a new version 0.4.06 
Could you try to give it a shot. You can now do -SkipAzureAd if the user is not known with use azuread credentials

**Comment by Asiasasif** [comment]
Same error, attached screenshots

![error1](https://user-images.githubusercontent.com/43236846/45549539-b5e14c80-b817-11e8-8c0e-c945145fc27c.PNG)
![error](https://user-images.githubusercontent.com/43236846/45549540-b679e300-b817-11e8-9ecd-170096444d73.PNG)

**Comment by ITRasmus** [comment]
Did you Update the module and import it again ?
You have to use the -skipazuread

**Comment by Asiasasif** [comment]
It worked, I did update but didn't use -skipazureAD.. Thanks guys, this looks awesome :)

By default the role is system administrator and is there a way that we can import by passing the required security roles..

**Comment by Splaxi** [comment]
You could create a new new issue and write the suggestion.

That way we can label it and plan it into our work 😁

**Comment by skaue** [comment]
I think providing actual security roles would be the advanced scenario. However, allowing for granting the imported users the -ADMIN- could be an easy change, and will probably cover most of the scenarios needed. Could this be piped?

**Comment by Splaxi** [comment]
With the current design this cmdlet gives all new users the same security setup as the the current ADMIN in the userinfo table.

If a given, single user, needs to be THE ADMIN, you should be using the Set-D365Admin cmdlet.

On a personal level I would say that security handling is out of scope for this module. 

The d365fo.integrations module actually has a solution for importing users using the DMF and using that you should be capable of assigning desired security roles on a per user base.

**Comment by Splaxi** [comment]
Closing because the issue was resolved.

**Comment by Asiasasif** [comment]
Hi All,

I was trying to use on a new environment, I am not able to update the d365f0.tools and the version is showing as 4.54 only. Please advise.

I am trying to import users on a different tenant and I am getting the same error. "Connecting to Azure active directory"

**Comment by Splaxi** [comment]
Could you please create a new issue.

When creating the new issue you have show us all parameters used. If they contain sensitive information, please just replace them with XXXXXX. 

The parameters used are more important than the values passed to the parameter.
