### ISSUE TITLE
Wrong Alias for Get-D365BacpacTable

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#501]
Hello Motz,

Happy new Year ! i hope that all is well for you and your family

i found an issue in the last release 

Get-D365BacpacTable is mapped to a wrong alias and so Get-D365ModelFileFromBacpac cannot be used anymore

![image](https://user-images.githubusercontent.com/40988263/103535968-f609e480-4e91-11eb-8b58-5a2d70d70658.png)

i have not workspace to do the fix myself quickly

Have a good day
Charles

**Comment by Splaxi** [comment]
Hi Charles!

Nice catch, it was a late release that night - sorry for all the trouble. Will fix now!

**Comment by Splaxi** [comment]
Next version should be correct: 0.6.47

Should be public in 20-30 minutes from now.

Once again - I'm sorry that I didn't catch this one!

**Comment by Splaxi** [comment]
Let me know when you had the chance to test it.

**Comment by Splaxi** [comment]
Oh - BTW way.

We simply renamed the cmdlet to Export-D365BacpacModelFile

And I can see that I still have an issue with the alias in the renamed cmdlet 🤯🔫

Will fix it once more.

**Comment by Splaxi** [comment]
Latest version 0.6.48 should be correct.

Please take it for a spin and let me know if I missed anything else 😅

**Comment by Shind44** [comment]
Hello Motz,

that's ok for me 

Thanks
