### ISSUE TITLE
Download from StorageAccount fails

### ISSUE THREAD

**Issue by kgmadsen** [d365collaborative/d365fo.tools#507]
Hi,
Are we missing a method in the function ?
I got this error :

[Invoke-D365AzureStorageDownload] Something went wrong while downloading the file from Azure. | Method invocation failed because [Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob] does not contain a method named '**DownloadToFile**'.
WARNING: [14:25:23][Invoke-D365AzureStorageDownload] Stopping because of errors. | Something went wrong while downloading the file from Azure.

Using this command;
Invoke-D365AzureStorageDownload -AccountId $StorageAccountName -AccessToken $StorageAccountKey -Container $Script:ContainerName -FileName $backupFileName.Name -Path $Sql.backup

**Comment by Splaxi** [comment]
This normally indicate that you have installed either some of the newer powershell modules, unrelated to our tools. 

Or you installed a higher .NET version and that breaks the current download code.

**Comment by Splaxi** [comment]
#361 and #447 might have some details to look into.

**Comment by Splaxi** [comment]
@kgmadsen 

Did you get it working? Should we take a offline session and see if we can crush the issue?

**Comment by Splaxi** [comment]
Closing the issue for lack of response.
