### ISSUE TITLE
Issue with invoke-d365sdpinstall

### ISSUE THREAD

**Issue by fwilkinson** [d365collaborative/d365fo.tools#509]
I just used the install-module -name d365fo.tools on a new Cloud Hosted DEV VM and on step one it is giving me "The term 'Update-DisableRestartForAppPoolAfterIISResetOrReboot' is not recognized as the name of a cmdlet".  Any thoughts.

UPDATE  --- Nevermind -- Not enough coffee -- I downloaded the DataUpgrade package for 10.0.15, not the AX 2012 data upgrade package for 10.0.15

**Comment by Splaxi** [comment]
Will close it - let me know if you hit any issues 😉
