### ISSUE TITLE
TfsURI is empty

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#51]
When I was testing this, the TfsURI was not populated. Any idea why that is? 

https://github.com/d365collaborative/d365fo.tools/blob/c398d88aaf3093e86fc1ab0f54da8a22c3b15b09/functions/invoke-d365scdpbundleinstall.ps1#L55

I had to explicitly add it.

**Comment by Splaxi** [comment]
Fixed in 0.4.9
