### ISSUE TITLE
Enable partial database synchronisation for binary only packages

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#516]
The internal [Get-SyncElements](https://github.com/d365collaborative/d365fo.tools/blob/e65bc988912af58e3e75ae90f5d0c9a5f3214926/d365fo.tools/internal/functions/get-syncelements.ps1) function is used to create lists of elements that can be synchronized with the database. The function uses the Metadata API and specifically the `DiskProvider` version of the `IMetadataProvider` interface. This provider works with the xml files that make up the source code of a module.

However, modules can also be provided as deployable packages that only contain the binary/compiled module without the source code (e.g. ISV solutions). In this case, the `Get-SyncElements` function will find no elements. This means that no partial sync can be done with the d365fo.tools for binary only modules.

I propose that instead of the `DiskProvider`, the `RuntimeProvider` is used to retrieve the synchronizable elements.

**Comment by fhoo** [comment]
I‘d also vote for using the `RuntimeProvider`, as the database should be in sync with what gets executed, not what is currently modified and not compiled. Also the standard DB sync runs against the compiled DLLs and not the XMLs as far as I know.

**Comment by Splaxi** [comment]
Anyone up for the challenge to make the PR?

**Comment by Splaxi** [comment]
0.6.53 should contain the fix.
