### ISSUE TITLE
Import command require a Y/N response

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#53]
It seems the import-command require a response from console in order to complete. 

https://github.com/d365collaborative/d365fo.tools/blob/c398d88aaf3093e86fc1ab0f54da8a22c3b15b09/functions/invoke-d365sdpinstall.ps1#L150

![image](https://user-images.githubusercontent.com/14696/45691408-e2b79b80-bb58-11e8-81c9-49e9d81eb722.png)

This needs a rewrite of the cmdlet.

**Comment by Splaxi** [comment]
A way to solve it is actually just to test for the runbook in the installation records directory. If it exists, throw an error and have the user delete it or pass and -Force parameter.

The cmdlet will test on force and have the folder removed. Then we don't get prompted from the executable.

**Comment by Splaxi** [comment]
C:\Logs\InstallationRecords\Runbooks

Inside any cmdlet / function in the module this will provide the correct paht:
$Script:InstallationRecordsDir

Then we can scan that directory for a matching child with the name of the $RunbookId. Is the runbook id part of the content of the runbook file pointed out in the code reference?

**Comment by Splaxi** [comment]
@skaue Can you share the different executions for us to look into?

I believe it should be a fairly easy fix to get this nailed.

**Comment by Splaxi** [comment]
Should be fixed in 0.5.25 - with a precheck for if the runbook id is already present.
