### ISSUE TITLE
Import bacpac fails on 10.0.17

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#531]
PS C:\Users\Userc5c413ea041> Import-D365Bacpac -ImportModeTier1 -BacpacFile "D:\temp\turnkey testbackup.bacpac" -NewDatabaseName "AxDB2"
[18:13:49][Test-PathExists] The C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe path wasn't found
. Please ensure the path exists and you have enough permission to access the path.
WARNING: [18:13:49][Test-PathExists] Stopping because of missing paths.

the sqlPackage is in the 130 folder for some reason.

**Comment by Splaxi** [comment]
I guess that this is a newly deployed VM.

You should always run Invoke-D365InstallSqlPackage before working with bacpac files. 

This will download the latest version and reconfigure the module to use that version going forward.

**Comment by turbozapekanka** [comment]
Yes, already figured it out
Thanks!

**Comment by Splaxi** [comment]
Awesome.
