### ISSUE TITLE
Wiki update: Download assets with SAS Link

### ISSUE THREAD

**Issue by richardsondev** [d365collaborative/d365fo.tools#534]
Hey there,

On the following wiki page, it mentions starting the download in the browser and grabbing the link from the browser's download list. Since this page was written LCS has released a Generate SAS Link button directly on the Asset library. 

https://github.com/d365collaborative/d365fo.tools/wiki/How-To-Transfer-Via-AzCopy#start-download-from-lcs-via-the-browser

This document would benefit from calling this out as this makes the process a lot easier.

![image](https://user-images.githubusercontent.com/48865951/113388772-ae391300-9343-11eb-85ce-4b9572ff8c55.png)

**Comment by Splaxi** [comment]
You are totally right! 

I'll update the guide over the next few days.

**Comment by Splaxi** [comment]
Done!
