### ISSUE TITLE
New-D365Bacpac seems to have changed arguments for ExecutionMode

### ISSUE THREAD

**Issue by kennysaelen** [d365collaborative/d365fo.tools#54]
New-D365Bacpac **-ExecutionMode FromSql** -DatabaseServer localhost -DatabaseName AxDB -SqlUser sqluser -SqlPwd "pwd" -BackupDirectory J:\MSSQL_BACKUP\ -NewDatabaseName AxDB_EXPORTCOPY -BacpacDirectory J:\MSSQL_BACKUP\ -BacpacName bacpacname

This command fails as the -ExecutionMode parameter cannot be found. Is it possible that this has been renamed as I see ExportModeTier1 and ExportModeTier2 but when using these it does not find the parameter set?

**Comment by Splaxi** [comment]
Hi!

We changed some of the parameters, to simply the execution of the cmdlet.

This should be enough for you to be going:

New-D365Bacpac -ExportModeTier1 -BackupDirectory J:\MSSQL_BACKUP\ -NewDatabaseName AxDB_EXPORTCOPY -BacpacFile J:\MSSQL_BACKUP\BacpacFilename.bacpac

**Comment by Splaxi** [comment]
The valid parameters, if you want it to look like closer to the one you shared:

`New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseName AxDB -SqlUser sqluser -SqlPwd "pwd" -BackupDirectory J:\MSSQL_BACKUP\ -NewDatabaseName AxDB_EXPORTCOPY -BacpacFile J:\MSSQL_BACKUP\BacpacFilename.bacpac`

**Comment by Splaxi** [comment]
The help comments for the cmdlet will be updated in the next release - that is going out tonight.

**Comment by kennysaelen** [comment]
Splendid, it did indeed work when I changed the params this morning. 
Would it be possible to also update the readme document on github here?
