### ISSUE TITLE
Invoke-D365InstallSqlPackage is missing in Wiki How To Import Bacpac into Tier 1

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#548]
Today, I tried for the first time to follow along the [How To Import Bacpac into Tier 1](https://github.com/d365collaborative/d365fo.tools/wiki/How-To-Import-Bacpac-Into-Tier1) Wiki article. When running the Import-D365Bacpac command, I got an error message that complained about the missing SqlPackage.exe. 
Looking up the documentation for the Import-D365Bacpac command, it was easy enough to find out that you should first run the Invoke-D365InstallSqlPackage command. But it would be nice if the Wiki article (and maybe the error message) would tell you that.

The wiki article also mentions in section "Switch databases": "The command will run for quite some time, but it will eventually exit and output the file location of the newly created bacpac file."
This does not seem to be correct anymore, in my case the command only ran a few seconds and did not output a file location (neither does the .gif in the article).

**Comment by Splaxi** [comment]
Fair points!

I'll see when I can get to put a bit more attention towards the bacpac import guide.

**Comment by FH-Inway** [comment]
Let me know if I can help, although currently I don't have the permissions to edit wiki pages.

**Comment by Splaxi** [comment]
The wiki is just a repo like the real repo.

So you can do a PR, but otherwise just send me the raw changes, then I can add them and have you proof read them.

**Comment by FH-Inway** [comment]
"send me the raw changes"? What is this, the Unix kernel repository? ;)

Just kidding, I never realized the wikis are a repo, too. But it turns out, they are poorly supported repositories on GitHub. Among other things, it seems you can't create a pull request from a fork of wiki repo.
The most reasonable (but still not very user friendly) solution seems to be [Merge Wiki Changes From A Forked Github Repo](https://gist.github.com/larrybotha/10650410)
In that vain, my fork is located at https://github.com/FH-Inway/d365fo.tools.wiki.git and the changes are in the `improve-import-bacpac-t1-howto` branch.

Hm, maybe the raw changes might have been the easier way after all...
Well, guess that's a chance for both of us to practice our git foo :)

**Comment by Splaxi** [comment]
It seems that I can't locate the repository.

Did you by any chance delete it? 🤔

**Comment by FH-Inway** [comment]
Hm, not intentionally, no. But you are right, it does not exist anymore. Sorry about that, no idea what happened there, I will recreate it tomorrow when I have access again to the computer where I cloned the repo.

**Comment by Splaxi** [comment]
Sorry for all the trouble! 🙈🙉🙊

**Comment by FH-Inway** [comment]
Not at all, I welcome the opportunity to get to know GitHub better.

The repository is "available" at https://github.com/FH-Inway/d365fo.tools/wiki
Note that this shows the content of the main branch, which is empty. But you should be able to clone this repository locally with the following url and then checkout the `improve-import-bacpac-t1-howto` branch, which contains my changes:
https://github.com/FH-Inway/d365fo.tools.wiki.git

[Merge Wiki Changes From A Forked Github Repo](https://gist.github.com/larrybotha/10650410) provides instructions on how you can merge those changes into your instance of the wiki repository. We can also do a screen share session and find out together how this is done.

![image](https://user-images.githubusercontent.com/33372796/122556184-7c2e7780-d03b-11eb-808d-b56756319b63.png)

**Comment by Splaxi** [comment]
The update should be viewable in the wiki 🤘

**Comment by FH-Inway** [comment]
@Splaxi Looks good, thank you.

**Comment by Splaxi** [comment]
![h8ZRNWU2CDeA48fCYi](https://user-images.githubusercontent.com/8750181/123143813-3e768800-d45b-11eb-89b9-251b95cdfb64.gif)
