### ISSUE TITLE
Upload .bak or .bacpac to LCS

### ISSUE THREAD

**Issue by Ralph101** [d365collaborative/d365fo.tools#549]
Is there a possibilty to upload a .bak or .bacpac to LCS Asset Library? I saw Invoke-D365LcsUpload but there was no type database backup.

**Comment by Splaxi** [comment]
Hi,

Sorry, but no.

This is a decision that Microsoft stands by rather firm. The ordinary customer shouldn't need to do this after a GOLIVE, so we shouldn't expect it anytime soon. 

But just for the sake of understanding, could you explain what you are trying to accomplish/achieve with the support of uploading bak/bacpac files?

**Comment by ReneVolkmer** [comment]
this could be useful for automatization of restoring tier1 db to tier2 (i.e. GOLD to TEST )

**Comment by Splaxi** [comment]
@ReneVolkmer 

No doubt - but you should totally nudge every single person that you know at Microsoft. The very second they open up for this, we'll have a solution ready to support you guys.

But - I would argue that the last time I had to move GOLDEN to a TIER2, I could automate the generation of the bacpac, and get a notification when it was done. Then I "only" had to upload it to LCS, navigate to the TIER2 in question and select the bacpac file - and then the import ran as planned. Not ideal - but way better than doing everything by hand.

**Comment by ReneVolkmer** [comment]
true, it is not a big deal, but it would be nice to have uploading CLS assets covered in full scope. Anyway, many thanks for this tool!
