### ISSUE TITLE
Filename should not need path

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#55]
It seems counter-intuitive to have to provide both backupdirectory when the filename already has the path.

Either filepath is enough, or backupdirectory provides the path and filename can be sent without path.

https://github.com/d365collaborative/d365fo.tools/blob/9fc8345e634ebd596d9688a2e854fe9a6a74a29d/functions/new-d365bacpac.ps1#L114

**Comment by Splaxi** [comment]
Great point!

The reasoning behind is that we have a hard time knowing what kind of environments that people will run the module in.

Let's say that we are on a Tier1 in Azure. They have been adding disks to handle some kind of data migration preparation. The sheer size of the SQL database backup is filling up the 1 drive. Now they need to store the bacpac file on another disk, to keep the proces running.

So to put it "simple" - we would like to help the users to have options to store the full database backup and the bacpac on different drives, if they need that. 

The default values for the BackupDirectory and BacpacFile makes it seem counter-intuitive, but for the users that have the need, they can chose to store the files in different locations.

**Comment by skaue** [comment]
I see the argument is only valid in Tier1 scenarios, due to the dependency to the internal function that performs the sqlbackup (d365fo.tools/internal/functions/invoke-sqlbackuprestore.ps1).
Maybe the parameter should only be validated if run on Tier1?

**Comment by Splaxi** [comment]
Yeah.

We could look into the parameterset, so the backup path is only available when - ExportModeTier1 is set.

The default value for the parameter, combined with the new validation logic, might cause some issues.

So the validation of this path should be a bit more intelligent than the current design.

**Comment by Splaxi** [comment]
Should be fixed in 0.4.11
