### ISSUE TITLE
xpp files not generated after running Invoke-D365ModuleFullCompile

### ISSUE THREAD

**Issue by VincentVerweij** [d365collaborative/d365fo.tools#557]
Hi,

Currently I have set up a build pipeline in Azure DevOps to trigger a get latest from our repository on a devbox, next it will do a build and db sync by using the tools.
The code that I did use to achieve this (with the exception of get latest) is the following:
```powershell
$models = 'ApplicationSuite', 'OurOwnModel', 'CaseManagement', 'ContactPerson', 'Currency', 'Directory', 'Ledger', 'PersonnelManagement', 'Tax'

foreach ($model in $models)
{
    Write-Host "##[group]Compile output for model '$model'"
    Invoke-D365ModuleFullCompile -Module $model -ShowOriginalProgress -Verbose
    Write-Host "##[endgroup]"
}
```

_Now, before I continue with this bug, I will now already say that I don't think this is a bug in the d365fo.tools, probably my lack of knowledge about the underlying process. That being said..._

When I work on the devbox and start a debugging session I noticed that when jumping into files it doesn't have the *.xpp files generated.
My workaround for this is that I do open the file that it couldn't find from the Application Explorer and then press F10/F11 and it does jump into it (after I received the tab with Source code not found).
When I trigger the build models from Visual Studio's Dynamics 365 menu, it does seem to generate those *.xpp files.

So the question I have is, should I pass some extra flag to `Invoke-D365ModuleFullCompile` (couldn't find any)?
Or is this an extra functionality within the VS extension?

Kind regards,
Vincent

**Comment by Splaxi** [comment]
Hi @VincentVerweij 

Thanks for this report.

As you stated, this most likely is because none of us fully understand the underlying implementation.

That being said, you might be able to ping Joris (MS) and see if he knows enough to help crack this nut. What ever you find out, I'm more than happy to help to implement into the tools, if it fits into the broader community needs.

**Comment by VincentVerweij** [comment]
I'll post it on MS's Yammer and ping Joris, so you will see it coming by there.
If I get anything useful out of the conversation, I'll be happy to post it here to inform others about it too.

**Comment by fhoo** [comment]
Vincent, did you open a solution before starting the debugging? The issue you described seems similar to trying to debug without a solution.

**Comment by VincentVerweij** [comment]
Hi @fhoo, yes I did open a solution while I was debugging (although I must admit that I don't always do it).

**Comment by VincentVerweij** [comment]
Hi, me again,

I did ask the question on MS's Yammer and @fhoo came back with a possible solution on Yammer too, which is opening a Visual Studio solution.
But the catch here (provided by Daniel Weichsel) is that you need to open a solution which has a Dynamics 365 Finance and Operations project.
If it is an empty solution, then no xpp file will get generated when debugging.

> Fix to this open a Visual Studio solution and a Dynamics 365 Finance and Operations project.

So as I already thought, this is not a bug in the tools. Closing it.
