### ISSUE TITLE
Install fails - clash with Az module

### ISSUE THREAD

**Issue by mpburtt** [d365collaborative/d365fo.tools#563]
Running **install-module -name d365fo.tools**, it runs for a bit then falls over with the following error:

`PackageManagement\Install-Package : The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'AzureRM.Profile' may override the
existing commands. If you still want to install this module 'AzureRM.Profile', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.4.1\PSModule.psm1:9709 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage`

That seems to be a clash with the standard Az admin module. Anyone got any clues on how to get past that without clobbering the existing module?

**Comment by mpburtt** [comment]
I use a whole bunch of Az cmdlets (as a former Unix guy, I'll try to automate anything that I find I have to do more than once but that probably means my head is still living Perl & awk despite the 20+ years since I moved off Unix), most recently in the area of creating Azure Alerts for logic app execution failures

In the end, I've just gone ahead and done...

install-module -name d365fo.tools -AllowClobber
install-module Az -AllowClobber

which allowed the install to complete.

You're probably right - I should get used to the idea of AllowClobber, I just don't recall needing to do it until now.

**Comment by Splaxi** [comment]
I always think of it like this. 

If AllowClobber is a core parameter while installing new modules, it is a expected behavior that you encounter conflicts between modules. 

Next issue is that you might have to disable auto load of modules, but that is easy fixed.

**Comment by Splaxi** [comment]
Let me know if you need anything else.
