### ISSUE TITLE
Get-D365LcsEnvironmentMetadata Unauthorized

### ISSUE THREAD

**Issue by stuartahonour** [d365collaborative/d365fo.tools#564]
Trying to use Get-D365LcsEnvironmentMetadata -ProjectId "{Project ID Removed}" -LCSApiUri "https://lcsapi.lcs.dynamics.com" -TraverseAllPages -EnableException

It get the following  Error 

[Get-LcsEnvironmentMetadata] Error status code Unauthorized in request for getting the environment metadata a project in LCS. Unauthorized. | The remote server returned an error: (401) Unauthorized.
WARNING: [16:49:59][Get-LcsEnvironmentMetadata] Stopping because of errors
Exception calling "AddRange" with "1" argument(s): "Value cannot be null.
Parameter name: collection"
At line:15163 char:13
+             $resArray.AddRange($metadata.Data)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Is this because I'm not setting the -BearerToken

How do I get the authentication to work?

**Comment by Splaxi** [comment]
Let me know if need anything else.
