### ISSUE TITLE
Proposition: Add cmdlet for changing IISExpress to IIS on a Dev Box

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#571]
Add cmdlet for changing IISExpress to IIS on a Dev Box and vice versa.
Please find more details here https://ievgensaxblog.wordpress.com/2018/04/02/msdyn365fo-how-to-switch-from-iis-express-to-iis-on-development-vm/.

**Comment by Splaxi** [comment]
Great idea. 

Can you share some sample powershell scripts that works? 

Would make it easier for us to implement it.

**Comment by valerymoskalenko** [comment]
Unfortunately, I do it manually each time. :-(  It's 2 minutes operation.
