### ISSUE TITLE
Make execution of the switch-database-tierX.sql script in Switch-D365ActiveDatabase optional

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#572]
It would be useful to have an optional parameter for the [Switch-D365ActiveDatabase](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/functions/switch-d365activedatabase.ps1) command that disables the execution of the switch-database-tierX.sql script. There are use cases where you want to switch to a database that already has been switched, so the script does not need to be executed again. One use case is the revert to the previously used database that is described in example 2 of the [command documentation](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/docs/Switch-D365ActiveDatabase.md).

**Comment by Splaxi** [comment]
For Tier1 - what would be the issue with running the switch sql script?

I'm all in for options 👍

**Comment by FH-Inway** [comment]
Sorry, my bad, I thought I saw some behavior today during a database switch that I thought was caused by the set-bacpacvaluessql.sql script. I assumed that the content of this script is part of the switch-database-tier1.sql script without checking. I have to check what happened there.
