### ISSUE TITLE
Make wiki content publishable from base repo

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#573]
This moves the content of the repo's wiki to the folder "wiki" in the repo itself. In addition, a GitHub action/workflow is added to publish the contents of the wiki folder to the repo's wiki. This uses the https://github.com/SwiftDocOrg/github-wiki-publish-action

See PR #570

**Comment by Splaxi** [comment]
Will into it.

My personal life is a bit blown to pieces these days - context: https://twitter.com/splaxi/status/1432788711788396550

**Comment by FH-Inway** [comment]
Aw man, that sucks, I'm sorry. Take care, hope you and your family come out of it healthy and safe. Don't worry about this issue, it can wait.

**Comment by FH-Inway** [comment]
Hey @Splaxi , hope you are doing good. Just writing because you asked for a ping, but feel free to take more time.

**Comment by Splaxi** [comment]
I'm releasing a new version tonight.

After that, I'm going to see if I can make your PR part of the module.

**Comment by Splaxi** [comment]
PR has been merged an the action was executed without errors / issues. Could you do a PR for the wiki content, so we could see what if things work like you planned them to? 😉

**Comment by FH-Inway** [comment]
Great! I can already see that [changes for the wiki sidebar](https://github.com/d365collaborative/d365fo.tools/pull/570/commits/103f3135ecfe27d1fbb6827cdd58f198e47ddc7c) that were included in the PR have been published to the wiki. But I will have some more wiki changes soon for sure.
