### ISSUE TITLE
Suggestion: Enable and Disable Maintenance Mode for non-admin

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#58]
Currently Enable and Disable Maintenance Mode relies on a executable that only works in elevated (admin) mode. 

Can the following workaround be used for scenarios where user is not local admin?

https://github.com/skaue/d365fo.tools/commit/d3af2b52b044704ca10172e79ef6a5ade3c6026c

**Comment by Splaxi** [comment]
Comments has been made via the code editor.

**Comment by Splaxi** [comment]
Implemented in 0.4.18

**Comment by skaue** [comment]
This needs to be reopened. Somehow the path to the SQL is broken. For MS hosted environments where user does not have admin, the script fails finding the path to the internal folders holding the SQL scripts.

VERBOSE: [10:44:51][Test-TrustedConnection] Capabilities based on the centralized logic in the psm1 file.
VERBOSE: [10:44:51][Test-PathExists] Testing the path: \internal\sql\enable-maintenancemode.sql
[10:44:51][Test-PathExists] The \internal\sql\enable-maintenancemode.sql path wasn't found. Please ensure the path exists and you have enough permission to access the path.
WARNING: [10:44:52][Test-PathExists] Stopping because of missing paths.

**Comment by Splaxi** [comment]
@skaue Could you very that you actually are running the latest version? Just in case.

Can you confirm that this line is present in your module, in the specific ps1 file and the **commands.ps1** file?

https://github.com/d365collaborative/d365fo.tools/blob/development/d365fo.tools/functions/enable-d365maintenancemode.ps1#L96

I will be able to test things on a build box (MSHosted / non-admin) tonight.

**Comment by skaue** [comment]
I'll double-check. I might have forgot to update the scripts on this specific box.

**Comment by Splaxi** [comment]
Could you do a
`Get-PSFMessage -Level Verbose`

Directly after the import of the module?

**Comment by Splaxi** [comment]
You could also do this:

`& (Get-Module d365fo.tools) { $Script:ModuleRoot }`

**Comment by skaue** [comment]
Updated the script and it works as expected. My bad. If you need me, I'll be over there, in the corner of shame, hiding...

**Comment by Splaxi** [comment]
No worries. Couldn't understand why it started failing, but you never know when stuff starts breaking...
