### ISSUE TITLE
🐛 fix error when running Enable-D365MaintenanceMode not as administrator

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#590]
When running the [Enable-D365MaintenanceMode](https://github.com/d365collaborative/d365fo.tools/blob/development/d365fo.tools/functions/enable-d365maintenancemode.ps1) cmdlet from a PowerShell session without administrator privileges, an error is shown and the maintenance mode is not enabled.

**Repro steps**
1. Open PowerShell without administrator privileges
2. Run ```Enable-D365MaintenanceMode```

**Result**
Error message 
```
[Get-SQLCommand] Something went wrong while working with the sql server connection objects | Exception setting "ConnectionString": "The value's length for key 'password' exceeds it's limit of '128'."
```
See Gist [d365fo.tools Enable-D365MaintenanceMode error](https://gist.github.com/FH-Inway/939489e0b350d89cd770df8ee4431f81) for the full error message.

**Expected result**
Maintenance mode is enabled without error message, just like when running the cmdlet as administrator. Or if that is not possible, a warning message should inform the user that enabling the maintenance mode requires administrator privileges.

**Comment by FH-Inway** [comment]
I also tried cmdlet [Get-D365User](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/functions/get-d365user.ps1) thinking that the issue might impact all cmdlets that use a SQL script. However, that cmdlet was able to execute without administrator privileges. I think it might be related to how the parameters for the ```Get-SqlCommand``` call are created.

**Comment by Splaxi** [comment]
The 128 char limit / exception is normally tied back to the capabilities to descrypt the web.config file.

Why one cmdlet is capable of doing just that, while another isn't - seems odd. As promised, I'll dive into the details tonight.

**Comment by FH-Inway** [comment]
So something like
https://github.com/FH-Inway/d365fo.tools/blob/%23590-CheckForAdminRuntime/d365fo.tools/internal/functions/test-isadminruntime.ps1#L27-L42

And then used like
https://github.com/FH-Inway/d365fo.tools/blob/%23590-CheckForAdminRuntime/d365fo.tools/functions/enable-d365maintenancemode.ps1#L104-L108

User experience would look like this:
```
PS C:\windows\system32> Enable-D365MaintenanceMode
[19:33:53][Test-IsAdminRuntime] It seems that you ran this cmdlet non-elevated. To run this cmdlet, it needs to be called from an elevated console. Please exit the current console and start a new one with "Run As Administrator"
[19:33:53][Test-IsAdminRuntime] Elevated permissions needed. Please start an elevated session and run the cmdlet again.
[19:33:53][Enable-D365MaintenanceMode] Maintenance mode can only be enabled in an elevated session.
WARNING: [19:33:53][Enable-D365MaintenanceMode] Stopping because of running non-elevated.
```

What do you think?

---
As an aside, while writing this, I went down a bit of a rabbit hole: I first tried to do this with ```Stop-PSFFunction``` and along the way came across #265, which discusses how exception should be handled by the module. I also came across [#173 Test-PSFFunctionInterrupt doesn't catch Stop-PSFFunction](https://github.com/PowershellFrameworkCollective/psframework/issues/173), which is why I decided to not use it.

**Comment by Splaxi** [comment]
Coming with 0.6.70 in 20 minutes
