### ISSUE TITLE
Import-D365Bacpac -ImportTier1 Throwing The login already has an account under a different user name.

### ISSUE THREAD

**Issue by HPLund** [d365collaborative/d365fo.tools#601]
Checked ax_db and dbo is mapped to sa (not axdbadmin). The Imported Database had axdbadmin as Login name for dbo,

Verified in SSMS by running
`CREATE` USER [axdbadmin] FOR LOGIN [axdbadmin] WITH DEFAULT_SCHEMA=[dbo]

Mitigation
`ALTER` AUTHORIZATION ON database::x TO sa
`CREATE` USER [axdbadmin] FOR LOGIN [axdbadmin] WITH DEFAULT_SCHEMA=[dbo]

Don't know when this step is performed and hence have no control over the integrity of the imported Database (issue).

Will run it again with -Verbose Output as a new Database

**Comment by Splaxi** [comment]
Hi @HPLund

Could you share a bit more details?

Normally we recommend to import the bacpac into a "new" database, and after the import is completed, we utilize the swithc-d365database cmdlet.

If you could share where the database is coming from, and include som details about the version (D365FO) and stuff like that - we might be able to nail this together.

**Comment by HPLund** [comment]
Imported as a new Database. The same happened the second time (also as a new Database) – I have the Verbose log, but cannot share it as is. Bacpac source was a Tier 3 Sandbox which got a db-refresh from PROD November 1st.

I will perform the manual fix and switch database later this week. The reference to ax_db was only to show the difference in the dbo mapping from the default to the Database imported through D365fo.tools (and the only difference that can explain the Error raised which is correct).

D365fo.tools installed yesterday (vm restarted).

Hans-Petter Lund
DCE, Technical Architect, CGI Norway

**Comment by Splaxi** [comment]
I believe we should do some private chat, to learn more about what you did and didn't do 😉

Ping me on yammer and we can exchange contact details and take it by mail / teams.

**Comment by Splaxi** [comment]
I just hit the same issue with one of my customers. 

I'll update the tools and release a new version, so we can help other people out. Thanks for providing the solution:

```
ALTER AUTHORIZATION ON database::AxDB TO sa
```

**Comment by HPLund** [comment]
Just tested importing the same bacpac now after updating the Tools and it works like expected. Issue solved.

Hans-Petter Lund
DCE, Technical Architect, CGI Norway
