### ISSUE TITLE
Proposition: bacpac import extra options for performance

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#607]
Is it possible to implement the following SQL script as a part of importing bacpac file?
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1496370140733440

> Good point. And I think setting the recovery model to SIMPLE helps, too. Chances are you want that anyway in a development environment; you probably aren't setting up robust backups.
> 
> Here's a little SQL script I run once the SQLPACKAGE command has created the new database (named AxDB_YYYYmmDD in this example); you can adjust the "size" on the last line based on your expected database size. It will reduce logging overhead, turn off delayed durability, and make your database a certain size in one fell swoop instead of frequent too-small autogrowths.
> 
> ALTER DATABASE AxDB_YYYYmmDD SET RECOVERY SIMPLE;
> go
> 
> ALTER DATABASE AxDB_YYYYmmDD SET DELAYED_DURABILITY = FORCED;
> go
> 
> ALTER DATABASE AxDB_YYYYmmDD MODIFY FILE (NAME=AxDB_YYYYmmDD_log, SIZE=8192, FILEGROWTH=1024MB);
> go
> 
> ALTER DATABASE AxDB_YYYYmmDD MODIFY FILE (NAME=AxDB_YYYYmmDD, SIZE=90112MB, FILEGROWTH=2048MB);
> go
> 
> 
> Once the import completes, you can clean up by running this:
> ALTER DATABASE AxDB_YYYYmmDD SET DELAYED_DURABILITY = DISABLED;
> go
> 
> ALTER DATABASE AxDB_YYYYmmDD SET AUTO_SHRINK = OFF;
> go
> 
> DBCC SHRINKFILE(AxDB_YYYYmmDD_Log, 512);
> go
> 
> 
> If you are comfortable with SQL Server, obviously, tweak as you feel appropriate. But I think these settings will help performance a little for most people.
>

**Comment by Splaxi** [comment]
I saw the comment made by Brian.

I would argue that if we were to succeed with it, we should look more into the manifest / model file of the bacpac itself. Here we can inject all different kinds of options, that should make most of the mentioned settings possible.

What you could do, was to test an import - where you by hand do what he states is working. After the import, you create a bacpac file from the DB. From the bacpac file, we can extract the manifest/model file and compare it to a "standard" one and see what we could learn from it.

If you do the testing, and share the manifest/model file with me - I'll deep dive in what is possible and what is not.

**Comment by Splaxi** [comment]
Closing this as we did get any manifest / model file to test on.
