### ISSUE TITLE
Import-D365AadUser to support User Principal Name as IdValue

### ISSUE THREAD

**Issue by dennismdejong** [d365collaborative/d365fo.tools#611]
Due to restrictions we need the User Principal Name  as the userid in D365 F&O and not the Email or Givenname, can you please add an option next to 'Login' and 'FirstName'

**Comment by Splaxi** [comment]
You could try and see if the `Import-D365ExternalUser` is capable of helping you out on the short term.

It would be helpful if you identified the correct property name that you want us to support.

We are internally using the `Get-AzureADUser` so if you run that and look for the property name, and can share it with us - then it would help.

If you want to speed up things, you could do a PR, with the desired changes. Then we can review them and make things happen faster that way.

**Comment by dennismdejong** [comment]
I created PR https://github.com/d365collaborative/d365fo.tools/pull/612 just don't know hot to link these two

**Comment by dennismdejong** [comment]
@Splaxi could you approve my PR?

**Comment by Splaxi** [comment]
Contained with the 0.6.70 version that has been released
