### ISSUE TITLE
Error when using Start-D365EnvironmentV2

### ISSUE THREAD

**Issue by VincentVerweij** [d365collaborative/d365fo.tools#623]
I am receiving an error while using the new commandlet `Start-D365EnvironmentV2`.
The services start correctly, but when they are started it throws an error.

![image](https://user-images.githubusercontent.com/41574930/151191690-af0e4bc7-9e05-44c2-8e44-b904ab7fe9eb.png)

Also there's a visual glitch.
The output of the services when it is started is not shown as a table like the `Start-D365Environment` commandlet.

@Splaxi I will check the code and make a pull request if I did find the bug.

**Comment by Splaxi** [comment]
So you have 2 issues in the code, that could explain these things. Line 164 and Line 168.

1. You piping your $temp to a select-object - which isn't formatted.
https://github.com/d365collaborative/d365fo.tools/blob/e057a1f9a5c9c9af64fc44302e7b7f263a5a1263/d365fo.tools/functions/start-d365environmentv2.ps1#L164
What you should do is:
```
#Line 164
$Results = $temp | Select-Object @{Name = "Server"; Expression = { $ComputerName } }, Name, Status, StartType, DisplayName
```
and then the error on line 168 is solved by that and the output will match the `Start-D365Environment`

**Comment by Splaxi** [comment]
The changes should be coming with the next release, hopefully today 🤞

**Comment by FH-Inway** [comment]
@Splaxi or @VincentVerweij I think this issue can be closed now.
