### ISSUE TITLE
Getting error when using import-d365bacpac ":Data cannot be imported into target because it contains one or more user objects. Import should be performed against a new, empty database."

### ISSUE THREAD

**Issue by fwilkinson** [d365collaborative/d365fo.tools#624]
I installed the D365FO.TOOLS module last week and am trying to import a bacpac I have imported before on other VMs.  When I try to import it, it errors out with ":Data cannot be imported into target because it contains one or more user objects. Import should be performed against a new, empty database.". .  The list of actions on the screen are "Creating deployment plan" then "Intializing Deployment" then it errors.  Any thoughts?

**Comment by Splaxi** [comment]
What version of sqlpackage.exe are you using? The latest .net core?

Could you try to install an older version of d365fo.tools and load that - to see if that fixes anything?

Could you share the command that you ran?

What about the manifest file from the bacpac - could you share that, of the configuration section of it?

**Comment by fwilkinson** [comment]
I just installed the D365FO.Tools module on the new VM last week and ran the invoke-d365installsqlpackage to pull the latest version of the SQL package.

Here is the command:  Import-D365Bacpac -BacpacFile C:\temp\20210916TEST.bacpac -NewDatabaseName 20210916aTest -ImportModeTier1

I’ll pull the manifest data for you once the CMD line sqlpackage finishes.  I’m running it manually (the version of SQLPackage that D365FO.TOOLS downloaded), and it is to the “Disabling index” process now.  Looks like it might actually work.

Thanks Motz!



Ford Wilkinson
Phone: (970) 300-2428 | ***@***.******@***.***>
[A close up of a sign  Description automatically generated]
