### ISSUE TITLE
Problem with the installation of d365fo.tools on a latest DEV VM (10.0.24)

### ISSUE THREAD

**Issue by thedjsm** [d365collaborative/d365fo.tools#639]
Hi,

I've tried to install the tools on a new devbox (latest from LCS) (Windows server 2019, VS 2019 D365 10.0.24)
But i ran into a problem with the installation 
![image](https://user-images.githubusercontent.com/104141260/164448288-9296058d-0ebd-40f0-8769-a3123640426c.png)

Can i use the -AllowClobber parameters to force the installation of the module AzureRM.profile ?
Is there any issue about that?

Best regards.

**Comment by Splaxi** [comment]
You can safely use the -AllowClobber parameter to get things installed.

**Comment by thedjsm** [comment]
Thanks for your reply, i will try this.

**Comment by thedjsm** [comment]
Hi, Thanks for your help, it worked as expected
