### ISSUE TITLE
Import-D365AadUser / AadGroupID

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#64]
Idea : Make a solution (new parameter ?) to search the exact AadGroup name and not a "like" operator to be sure that we can get the correct Group

for exemple, i have 2 group

Group_A
Group_A_B

i want to use the command for Group_A, Currently that not working because the commande say "More than 1 group found

or develop a capabilities to send the ObjectId for AadGroup (witch is unique)

**Comment by Splaxi** [comment]
I would say that if you have that scenario, then you also know what you're doing.

So in that regard we should extend the Import-D365AadUser to have a new parameter called AadGroupId, which should give you what you need.

Are you up for the challenge? I will gladly assist when you hit something that doesn't make sense to you.

What do you say?

**Comment by Shind44** [comment]
@Splaxi   : I'm in :)

**Comment by Splaxi** [comment]
And now the task is on you :)

**Comment by Splaxi** [comment]
Just saw your PR.

Could you share your Twitter handle, for us to put you in as an author? 😀

**Comment by Shind44** [comment]
Mötz,
here my twitter account informations

charles colombel
@dropshind
