### ISSUE TITLE
Does not install on 10.0.24 VHD

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#640]
PS C:\windows\system32> Install-Module -Name d365fo.tools

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PackageManagement\Install-Package : The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'AzureRM.profile' may override the
existing commands. If you still want to install this module 'AzureRM.profile', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage

PS C:\windows\system32>

**Comment by turbozapekanka** [comment]
![image](https://user-images.githubusercontent.com/20775323/165885044-9d543a3f-7877-4868-820d-9c19460ef0d4.png)

**Comment by Splaxi** [comment]
You will need to run it with the -AllowClobber parameter as mentioned by the error.

**Comment by FH-Inway** [comment]
@Splaxi I think this one can be closed.

**Comment by Splaxi** [comment]
We didn't merge the PR - just yet.

Wanted to have the other issues of the table and have a stable period. Planning for 2. week of december - so we have some time before the holidays to fix any issues... 🤞

**Comment by FH-Inway** [comment]
@Splaxi I confirmed that on the 10.0.29 VHD, the 0.7.0 version of d365fo.tools can be installed without the `-AllowClobber` option. Can you close the issue?
