### ISSUE TITLE
Visual studio extensions are not updated, services are disabled

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#642]
Applied 10.0.27 update on top of the new 10.0.24 VHD with the following command:

Invoke-D365SDPInstall -Path "c:\temp\10.0.27" -Command RunAll -RunbookId “10.0.27”

1. VS2019 extension is not updated, had to manually run Microsoft.Dynamics.Framework.Tools.Installer.vsix
2. Services ended up in Disabled state for some reason:
![image](https://user-images.githubusercontent.com/20775323/165995256-1503f0a0-8862-4991-9370-1621362497dd.png)

**Comment by Splaxi** [comment]
I would argue this is an issue with the update and  not the tools it self...

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed. Version 10.0.27 is no longer supported and there do not seem to be other instances of this issue.
@turbozapekanka Feel free to provide further information or thoughts on how we can help with this.
