### ISSUE TITLE
New-D365Bacpac -ExportModeTier2 / Full Text Catalog Failed

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#65]
VERBOSE: [07:11:34][Test-TrustedConnection] Not capable of using Trusted Connection based on Tier validation.
VERBOSE: [07:11:34][Test-PathExists] Testing the path: C:\Temp\Bacpac
True
VERBOSE: [07:11:34][New-D365Bacpac] Invoking the Tier 2 - Creation of Azure DB copy
VERBOSE: [07:11:34][Get-SqlCommand] Building the SQL connection string.
VERBOSE: CREATE DATABASE XXXXXX_export] AS COPY OF XXXXXXX_4fc6f9ab2dd5fdd9]
VERBOSE: [07:12:45][Get-SqlCommand] Building the SQL connection string.
VERBOSE: [07:12:45][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [07:13:45][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [07:14:45][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [07:15:45][Invoke-AzureBackupRestore] Total time spent inside the function was 00:04:11.0502875
VERBOSE: [07:15:45][New-D365Bacpac] Invoking the Tier 2 - Clear Azure DB objects
VERBOSE: [07:15:45][Get-SqlCommand] Building the SQL connection string.
[07:15:47][Invoke-ClearAzureSpecificObjects] Something went wrong while clearing the Azure specific objects from the Azu
re DB | Exception calling "ExecuteNonQuery" with "0" argument(s): "T**he database principal owns a fulltext catalog in the
 database, and cannot be dropped."**

this error message refers to the MS document to Copy database grom Azure to SQL Server
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server

 **can't drop users in source database**
When you drop users in the source database, the axdbadmin or axdeployuser user might not be deleted, because that user is the current owner of the full-text catalog. This issue occurs if the database was originally created for CTP7 or CTP8 of Dynamics AX 7 (Finance and Operations). To resolve the issue, run the following Transact-SQL (T-SQL) command to change the owner to the dbo user.

**for this error, i reproduce on a 8.0 PU15 new database (real sandbox customer database)**

Copy
ALTER AUTHORIZATION ON Fulltext Catalog::[CATALOG_NAME]  TO [dbo]; 
For more information about this command, see ALTER AUTHORIZATION.

to get Full Texte Catalog from a DB
SELECT * FROM sys.fulltext_catalogs

**Comment by Splaxi** [comment]
While we test, could you save the SQL Script into at Test.sql file and pass it as a customsql script to the cmdlet? You need to include the other parameters as well.

New-D365Bacpac -CustomSqlFile "c:\temp\test.sql"

If that works, we have a better understanding on where to put it in the flow inside the cmdlet :)

**Comment by Shind44** [comment]
Mötz, 
i tried with customSQLFile but i think that this SQL commands will be called after cleaning 

here the SQL that i execute myself

declare @catalogSQL varchar(1000)
set quoted_identifier off

declare catalogCursor CURSOR for
select 'ALTER AUTHORIZATION ON Fulltext Catalog::[' + name + ']  TO [dbo]; '
from sys.fulltext_catalogs
OPEN catalogCursor
FETCH catalogCursor into @catalogSQL
WHILE @@Fetch_Status = 0
BEGIN
exec(@catalogSQL)
FETCH catalogCursor into @catalogSQL
END
CLOSE catalogCursor
DEALLOCATE catalogCursor

**Comment by Splaxi** [comment]
You are correct Charles.

That was why I wanted you to try that. Because then we know it must be part of the "clear-azurebacpacdatabase.sql" file that is located under "..\internal\sql\clear-azurebacpacdatabase.sql"

You could look into that file, copy in your own code and see if that works. If yes, then it should be easy for you or us to take in as a PR.

Let me know what way you want to go :)

**Comment by Shind44** [comment]
Mötz, 
ok i take the issue to fix it and take in after as a PR

**Comment by Splaxi** [comment]
Implemented in 0.4.18

**Comment by vzugravyi** [comment]
Hi guys, 
Hope you're doing well. 
I've used your tool before. And I like it. 
But after updating to the last version, the script was stopped working. 
I've received the next issue, and I can't solve it. 
[Invoke-AzureBackupRestore] Something went wrong while creating the copy of the Azure DB | Exception calling "
ExecuteNonQuery" with "0" argument(s): "CREATE DATABASE AS Copy of  operation failed. Internal service error.
A severe error occurred on the current command.  The results, if any, should be discarded."
