### ISSUE TITLE
Issues with Invoke-D365AzureStorageDownload

### ISSUE THREAD

**Issue by TrudAX** [d365collaborative/d365fo.tools#653]
Actual behaviour 
If you run Invoke-D365AzureStorageDownload as in provided examples and you don't have a file name available, it produces a warning: 
"Something went wrong while downloading the file from Azure. | Exception calling "DownloadToFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
but the execution flow will not be stopped
Expected behaviour:
Any exception during the function call should stop the execution flow by default. This function is used in the restore pipeline and if it can't download the file, there is no point to execute next command. 

See the provided example. command "Stop-D365Environment -All" should not execute

Invoke-D365AzureStorageDownload -EnableException -AccountId "fied365vmstorage" -AccessToken "ww==" -Container  "trudtemp"  -Path "J:\MSSQL_BACKUP"  -FileName ("11.bak" )
Stop-D365Environment -All

**Comment by Splaxi** [comment]
Could you share a screen shot? 

Is the () on purpose in the example?

**Comment by TrudAX** [comment]
![image](https://user-images.githubusercontent.com/26786918/173289034-4991b386-627f-40a9-bc07-0c17c4eb23f3.png)
Here is the image. The second command should not be executed
() is not on purpose

**Comment by TrudAX** [comment]
![image](https://user-images.githubusercontent.com/26786918/173289287-32a60bfc-824a-4470-887b-ff45c57a6645.png)

**Comment by Splaxi** [comment]
Could you try to run it in a stand alone powershell session?

Could you try to run the enable exception cmdlet and leave the parameter from the download cmdlet?

**Comment by FH-Inway** [comment]
> https://github.com/d365collaborative/d365fo.tools/blob/development/docs/Enable-D365Exception.md

I tested with this and it causes the exception to be thrown and subsequent commands are not executed. Note that it doesn't seem to make a difference if the [Invoke-D365AzureStorageDownload](https://github.com/d365collaborative/d365fo.tools/blob/development/d365fo.tools/functions/invoke-d365azurestoragedownload.ps1) cmdlet uses the `-EnableException` switch or not, the result is always the same.

We should probably mention the `Enable-D365Exception` in [Exception-handling](https://github.com/d365collaborative/d365fo.tools/wiki/Exception-handling) (btw., shouldn't there also be a `Disable-D365Exception` cmdlet?). Also, a bit of the thoughts behind how the module handles exceptions and why would not hurt and could be taken from the discussion of #265 .

**Comment by TrudAX** [comment]
@Splaxi  - "Enable-D365Exception" worked. Now the execution is stopped with the exception. 
Maybe add this into documentation, that before running Invoke-D365AzureStorageDownload set up  "Enable-D365Exception"

**Comment by Splaxi** [comment]
When back from my sick leave, I'll try to catch up on all the things and see how we can make it more clear for the community.

**Comment by FH-Inway** [comment]
> When back from my sick leave, I'll try to catch up on all the things and see how we can make it more clear for the community.

Hope you'll feel better soon.
I created #655 to help address the feedback from this issue.
