### ISSUE TITLE
Set-D365RsatConfiguration looking for the incorrect config file

### ISSUE THREAD

**Issue by jaestevan** [d365collaborative/d365fo.tools#678]
RSAT config file has been lately renamed to `Microsoft.Dynamics.RegressionSuite.WpfApp.exe.config` (previously `WindowsApp.exe.config`) and this command is hard-looking to the previous name. Here:

https://github.com/d365collaborative/d365fo.tools/blob/ffaa55f6c8d9552217c34511e6cd395d19a4de70/d365fo.tools/functions/set-d365rsatconfiguration.ps1#L64

Error:

    [Test-PathExists] The C:\Program Files (x86)\Regression Suite Automation Tool\Microsoft.Dynamics.RegressionSuite.WindowsApp.exe.config path wasn't found. Please ensure the path exists and you have enough permission to access the path.
    WARNING: [Test-PathExists] Stopping because of missing paths.

Will try to find time to fix it myself with a PR but recording it here just in case someone can handle it earlier :)

**Comment by FH-Inway** [comment]
Added the change in #774 
I implemented it as a parameter in case someone wants to continue using an older version of RSAT.
I also added checks for the attributes. In a current installation of RSAT, the `AddOperatorFieldsToExcelValidationEnabled` setting does not exist in the config file.

**Comment by FH-Inway** [comment]
@jaestevan The change is now available in version 0.7.5.
