### ISSUE TITLE
Get-D365Module throwing Cannot bind argument to parameter 'Path'

### ISSUE THREAD

**Issue by goshoom** [d365collaborative/d365fo.tools#679]
I got into situation when `Get-D365Module` failed with *Cannot bind argument to parameter 'Path' because it is an empty string.*.
`Get-D365Module` calls `Get-FileVersion -Path (Get-ChildItem $modulepath -Filter "Dynamics.AX.$($obj.Name).dll").FullName` and it tries to use an empty path if the DLL file doesn't exist.
This happened when a re-compilation failed before completion. The folder exists, but the file doesn't. This isn't a correct state of the environment, but it shouldn't prevent me from getting a list of modules (that I want to compile).
An extra check for the file existence is needed.

**Comment by FH-Inway** [comment]
Seems easy enough, there is already a check in place if the folder exists. We could either replace it with the check for the file or add it as an additional check.

https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/functions/get-d365module.ps1#L168-L176

**Comment by Splaxi** [comment]
@goshoom 

Did your PR's solve this issue or do we still have some work to do?

**Comment by goshoom** [comment]
@Splaxi I haven't done anything on it, at least not yet.

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed.
