### ISSUE TITLE
Cmdlet to download asset from shared asset library

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#687]
### Discussed in https://github.com/d365collaborative/d365fo.tools/discussions/680

<div type='discussions-op-text'>

<sup>Originally posted by **FH-Inway** November  3, 2022</sup>
@ Oleksandr Nikolaiev describes in https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=1976607079530496 how downloading an asset from the shared asset library can be automated. Looks to me like this is similar to other LCS actions that the d365fo.tools already support.

Though not part of the official LCS API and arguably an incorrect behavior that Microsoft may or may not fix in the future, I think it would be worthwhile to add a cmdlet for it.</div>

**Comment by FH-Inway** [comment]
First draft see #686 

[Get-D365LCSSharedAssetFile.log](https://gist.github.com/FH-Inway/016bbae623de24f878235d44f9bbed67#file-get-d365lcssharedassetfile-log) shows how the usage of the new cmdlet could look like.

Cmdlet documentation is not updated and copied from other cmdlets. I'm also not that happy with the names of the internal function cmdlets.

**Comment by Splaxi** [comment]
0.6.77 should solve the issue
