### ISSUE TITLE
Database is already open and can only have one user at a time

### ISSUE THREAD

**Issue by onikolaiev** [d365collaborative/d365fo.tools#690]
Sometimes I am facing this error message while switching DB. 
@BradBateman from Yammer provided a fix he found on Microsoft Docs.
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1994317149044736

d365fo.tools/internal/sql/switch-database-tier1.sql

So, probably, we need to add the following line before moving DB to SINGLE_USER mode
ALTER DATABASE [DBName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;

and this, when we're done
ALTER DATABASE [DBName] SET AUTO_UPDATE_STATISTICS_ASYNC ON;

**Comment by onikolaiev** [comment]
Created PR #691.

**Comment by Splaxi** [comment]
0.6.77 should solve the issue
