### ISSUE TITLE
Import-D365Bacpac not working with connection security improvment in SqlPackage

### ISSUE THREAD

**Issue by msgdelm** [d365collaborative/d365fo.tools#692]
Initializing a new devbox, I've downloaded the latest SqlPackage:
SqlPackage: Command-line tool for creating and deploying SQL Server databases and DACPAC packages. (16.1.6374.0)
Copyright (c) 2022 Microsoft Corporation.  All rights reserved.

Trying to import a bacpac in the Tier1 dev environment, I have the following error:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/72152679/202810692-f2aa92c4-fcea-4f9e-bf0d-ccc2fd0c06f0.png">

Following the link: https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758

There was security improvments blocking by default self-signed certificate.
The new option in sqlpackage should be used be default in everry commandlet working againt a Tier1.

**Comment by FH-Inway** [comment]
Thanks for reporting. Looks like this would require a change in the internal [Invoke-SqlPackage](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/internal/functions/invoke-sqlpackage.ps1) cmdlet.
Did you by any chance also use the other cmdlet [New-D365Bacpac](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/functions/new-d365bacpac.ps1) that makes use of SqlPackage?

**Comment by msgdelm** [comment]
Same issue with New-D365Bacpac:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/72152679/202816816-5431bf90-e8a1-4553-aee0-ba5694ea336e.png">

The BAK creation using the System.Data.SqlClient.SqlCommand is fine.
The bacpac with SqlPackage has the same issue.

**Comment by Splaxi** [comment]
Exposing the properties parameter for new bacpac and import bacpac should be a simple way to fix it...

**Comment by FH-Inway** [comment]
There does not seem to be a way to change the connection encryption behavior of SqlPackage with action properties. Instead, the new parameters (see https://aka.ms/dacfx-connection) have to be used. Do you think we should expose those? If possible, I would prefer setting them to default values.

So far, I was able to repro the issue on a vanilla 10.0.24 local vhd. Currently testing on a current 10.0.30 cloud hosted environment.

**Comment by FH-Inway** [comment]
From https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage
This shows which actions support which of the 4 new parameters.

Parameter | Short Form | Extract | Publish | Export | Import | DeployReport | DriftReport | Script
-- | -- | -- | -- | -- | -- | -- | -- | --
/SourceEncryptConnection: | /sec | x | x | x |   | x |   | x
/SourceTrustServerCertificate: | /stsc | x | x | x |   | x |   | x
/TargetEncryptConnection: | /tec |   | x |   | x | x | x | x
/TargetTrustServerCertificate: | /ttsc |   | x |   | x | x | x | x

For Export, I was able to test that `/SourceTrustServerCertificate:True` and `/SourceEncryptConnection:[False|Optional]` resolve the issue. As default, I'm currently leaning towards `/SourceEncryptConnection:Optional`

**Comment by FH-Inway** [comment]
We may also have to check for the SqlPackage version. On older versions, not all values of the parameters are supported and cause an error.

> C:\windows\system32> sqlpackage /version
> 16.0.5400.1
> C:\windows\system32> SqlPackage /a:export /ssn:localhost /sdn:AxDB /tf:C:\Temp\my.bacpac /p:CommandTimeout=1200 /p:VerifyFullTextDocumentTypesSupported=false /SourceEncryptConnection:Optional
> *** Argument 'SourceEncryptConnection' has an invalid value: 'Optional'.

**Comment by FH-Inway** [comment]
I tried the oldest version of SqlPackage I could get my hands on, which is version 18.5 from April 2020. This version supports all 4 parameters, but for `/[Source|Target]EncryptConnection`, only values `True` and `False`.

So now I'm proposing the following solution:
- We leave Import-D365Bacpac and New-D365Bacpac as is
- We change Invoke-SqlPackage
  - the import action gets `/TargetTrustServerCertificate:True` as additional parameter
  - the export action gets `/SourceTrustServerCertificate:True` as additional parameter

Invoke-SqlPackage also supports the publish action, but I have not been able to test that yet. @Splaxi , I believe you have more experience with that. Since the publish action is used by the Import-D365Bacpac cmdlet, should we give it the `/TargetTrustServerCertificate:True` as additional parameter?

**Comment by Splaxi** [comment]
My gut feeling is:

We are talking about Tier1 machines only communication, internally on the machine. So defaulting to the "*TrustServerCertificate:True" makes sense to me.

We should stay away from the EncryptionConnection - as people might be confused over time, why we don't encrypt the connection. Accepting a local certificate is easier to understand and accept.

**Comment by Splaxi** [comment]
@FH-Inway 

Did we conclude that the SourceTrustServerCertificate property is present in the older versions? Or should we fail on the wrong version of the SqlPackage.exe - to make sure people know that they should "upgrade" it?

**Comment by FH-Inway** [comment]
@Splaxi Yes, the `SourceTrustServerCertificate` parameter is present at least as far back as version 18.5 from April 2020. So I don't think there is a need to fail on the "wrong" version of SqlPackage.exe.

**Comment by Splaxi** [comment]
Thanks for all the support for the last few days / weeks!

**Comment by Splaxi** [comment]
0.6.77 should solve the issue
