### ISSUE TITLE
get error message while using d365fo.tools in MS VM 

### ISSUE THREAD

**Issue by senaaksoy** [d365collaborative/d365fo.tools#698]
We cannot use d365fo.tools almost two weeks in MS vm machines and cannot understand the problem .The error message in the attachtments . Anyone has any idea ? 
<img width="428" alt="d365fo tools" src="https://user-images.githubusercontent.com/119443701/204606544-7b986564-0045-410e-b3ed-5913c02d4129.png">

**Comment by FH-Inway** [comment]
You are installing the module with `-RequiredVersion 0.6.76`. 
This version has a known issue #693 
Please try the latest version 0.6.77 where this issue has been fixed.
