### ISSUE TITLE
Rename-D365ComputerName fails on the new 10.0.29 VHD

### ISSUE THREAD

**Issue by fhoo** [d365collaborative/d365fo.tools#704]
Renaming the VM with Rename-D365ComputerName fails on the latest VHD (10.0.29) with the following error message:

```
[Rename-D365ComputerName] Something went wrong while working against the database. | Exception calling "ExecuteNonQuery" with "0" argument(s): "The server 'DVHD10029' does not exist. Use sp_helpserver to show available servers.
```

The reason is that the current computer name is not registered with the SQL server and hence removing that server name with sp_dropserver fails.

**Comment by fhoo** [comment]
You can circumvent the error by setting the COMPUTERNAME environment variable to 'pkrvmug8s5trcwh' before calling the cmdlet, because that is the name which is initially configured. 
But I think the tools should be more tolerant against such an issue 😃 
```
$env:COMPUTERNAME = 'pkrvmug8s5trcwh'
Rename-D365ComputerName
```

**Comment by Splaxi** [comment]
Do you have a way, in TSQL, so we can avoid that part for failing?

**Comment by fhoo** [comment]
I think the easiest would be to put the sp_dropserver in a try / catch to avoid the statement to fail. So changing the rename-computer.sql to this:
```
BEGIN TRY
	EXEC sp_dropserver [@OldComputerName];
END TRY
BEGIN CATCH
	PRINT '@OldComputerName could not be dropped!'
END CATCH

EXEC sp_addserver [@NewComputerName], local;

```
should be ok.

If we want to remove all the registered server name despite the current computer name, we can go the route to first select all the registered servers into a table and then iterate over the result to remove all the server names like this:
```
declare @servers table (name nvarchar(128), network_name nvarchar(128), status nvarchar(max), id char(4), collation_name nvarchar(128), connection_timeout int, query_timeout int)

insert into @servers exec sp_helpserver

declare server_cursor cursor
for
	select name from @servers

declare @serverName nvarchar(128)

open server_cursor
fetch next from server_cursor into @serverName

while @@FETCH_STATUS = 0  
begin  
	EXEC sp_dropserver [@serverName]
	fetch next from server_cursor into @serverName  
end

close server_cursor
deallocate server_cursor
```

Which solution would you prefer? I'd say version one should be enough in the first step and we'll wait for the next VHD version to see if there are still wrong server names registered?

**Comment by fhoo** [comment]
I've added a pull request with the first and easiest option to fix that. So this issue can be closed when the pull request is merged.

**Comment by FH-Inway** [comment]
@fhoo or @Splaxi Can we close this issue now?

**Comment by fhoo** [comment]
Yes, I this can be closed. Thanks for cleaning up :)

**Comment by fhoo** [comment]
@FH-Inway I have tested your proposed fix and it works perfectly. So we should include it in the next version of the tools!
