### ISSUE TITLE
Get-D365LcsApiToken. Error 400

### ISSUE THREAD

**Issue by fsilva-jr** [d365collaborative/d365fo.tools#705]
When using the:
Get-D365LcsApiToken -ClientId "{YOUR_APP_ID}" -Username "{USERNAME}" -Password "{PASSWORD}" -LcsApiUri "https://lcsapi.lcs.dynamics.com" -Verbose | Set-D365LcsApiConfig -ProjectId 1234567

i am getting this error:
[Invoke-Authorization] Something went wrong while working against Azure Active Directory (AAD) | The remote server returned an error: (400) Bad Request.

It was working before...

My App Registration was created based on this post: https://ariste.info/en/dynamics365almguide/aad-app-creation/

I tried with different apps but no success.

Can someone point what i am doing wrong?

**Comment by Splaxi** [comment]
If it worked before, my suspicion is that MFA was enabled for the account in question...

**Comment by Kaffedreng** [comment]
It might be because of an update where the underlying authentication is failing, due to a missing parameter in the request.

I’ve managed to get it to work by adding client_secret to the body as well.
See the body variable in the code below.

```
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/x-www-form-urlencoded")

$body = "grant_type=password&client_id=<some guid>&resource=https%3A%2F%2Flcsapi.lcs.dynamics.com&client_secret=<my secret>&username=<my username>&password=<my password>”

$response = Invoke-RestMethod 'https://login.microsoftonline.com/common/oauth2/token' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json
```

In the module, the [command](https://github.com/d365collaborative/d365fo.tools/blob/development/d365fo.tools/functions/get-d365lcsapitoken.ps1) requires Password and Username, ClientId and the LCS url are not mandatory. 
But in reality, it seems to need ClientSecret as well as Client Id.

**Comment by FH-Inway** [comment]
@Kaffedreng It works for me without ClientSecret or ClientId.

@Splaxi Wouldn't MFA result in an authorization error instead of a bad request error?

**Comment by fsilva-jr** [comment]
This same account is used for other service connections and releases. MFA is not the issue i think.
The same error happens when trying from Powershell.
Tried changing app registration configurations, but no success yet.

**Comment by Splaxi** [comment]
The `$error` variable will tell us more...

So start a new session and run it again. When it fails, simply write `$error` and share it with us....

**Comment by Splaxi** [comment]
Going for the ClientSecret is an anti pattern. It would indicate that other configurations needs to be adjusted. What icks me, is that it used to work for @fsilva-jr - which would indicate that something changed. Be that security or configuration on the tenant level.

I have a customer, that also changed some settings on their tenant and this now yields the following error:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/8750181/212315632-a998f653-03e0-4b1c-aa57-d4baeab26d4e.png">

**Comment by fsilva-jr** [comment]
Here is the error:
![image](https://user-images.githubusercontent.com/50589817/212436582-32f949d3-135e-4a69-9edb-bf22cb6c5720.png)

User account: d365admin@domain.com
Pass: PasswordUau2023!

I am pretty sure that i am using the correct credentials. i use every day for administrative tasks. is the ! an issue?

Here is the entire line, with fake user and password but in the exactly same format:

Get-D365LcsApiToken   -Clientid "asok92ba-2214-9cb2-9801-af57ad6b0910" -Username d365admin@domain.com -Password "PasswordUau2023" -LcsApiUri https://lcsapi.lcs.dynamics.com/ -Verbose | Set-D365LcsApiConfig -ProjectId "1234567"

**Comment by fsilva-jr** [comment]
Tried with 3 different accounts with the right privilegies into Azure, DevOps and LCS. Same issue.

**Comment by fsilva-jr** [comment]
The $error was the key guys... thanks a lot for that!!!
In this case the "Federated Authentication" is the problem. This customer uses a third part tool called Okta to authenticate users account.
Thanks for all your time and inputs!

**Comment by Splaxi** [comment]
Awesome news! 

This isn't the first time that the okta solution has been the issue - but what confused me was that you said it worked previously. 

Did you do some changes to okta or did you disable okta for the specific user account in question?

**Comment by fsilva-jr** [comment]
Tuersday i will talk with security team to see what happened with this account...
What makes me confuse is that i am able to connect to Azure, LCS and DevOps using this account with no MFA required... i can see it goes through Okta, but no need to do anything else than user and password.

**Comment by Splaxi** [comment]
You could be affected by something that is called "Conditional Access Policy"

This makes it possible to disable MFA when you are on a whitelisted IP address and a lot of other things. 

Let us know when you learn something new about the issue 🤞

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed.
@fsilva-jr Feel free to provide additional information if you can share it publicly.

**Comment by fsilva-jr** [comment]
Hello!
We created a new account without MFA and Federated Authentication.
Thank you for all the help!
