### ISSUE TITLE
Cannot use Install-D365SupportingSoftware as Chrome checksum fails

### ISSUE THREAD

**Issue by mariusiulianc** [d365collaborative/d365fo.tools#706]
Hello, when using the:
Install-D365SupportingSoftware -Name "googlechrome"

I'm getting this error related to checksum:

Error - hashes do not match. Actual value was '6B9D7D0F4889924CA55F02B7B39B91D646ED497CC59B4187E0C28FC5B96474E7'.
ERROR: Checksum for 'C:\Users\localadmin\AppData\Local\Temp\chocolatey\GoogleChrome\108.0.5359.125\googlechromestandaloneenterprise64.msi' did not meet '254a5b8767656ad74cbb2c7a5444d8f3594fcf326659b0f6c6648d66b4706227' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of googlechrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.

I know how to skip checksum from chocolatey but I would like to know if it is possible to skip it from Install-D365SupportingSoftware.
Can someone point to how can we do that?

**Comment by FH-Inway** [comment]
Thanks for reporting. Unfortunately, the [Install-D365SupportingSoftware](https://github.com/d365collaborative/d365fo.tools/blob/f5afd0c6889b39d20115c37461f7729286fcd129/d365fo.tools/functions/install-d365supportingsoftware.ps1) cmdlet does not provide that option at the moment.

It should be pretty straightforward to add such a parameter to the cmdlet, though. Would you be interested in creating a pull request for that?

Curiously enough, when executing the cmdlet, it first updates all programs installed with chocolatey and it does so with the `--ignore-checksums` parameter:
https://github.com/d365collaborative/d365fo.tools/blob/f5afd0c6889b39d20115c37461f7729286fcd129/d365fo.tools/functions/install-d365supportingsoftware.ps1#L55-L58

**Comment by FH-Inway** [comment]
@Splaxi Do you think we should make this change to be consistent between chocolatey upgrades and installs? Otherwise this issue could be closed as there seems low interest in it.

**Comment by Splaxi** [comment]
If you got time and energy, be my guest 😉

Otherwise let's pause it for the time being...

**Comment by FH-Inway** [comment]
@Splaxi Let's close it for now.
