### ISSUE TITLE
Remove documentation for cmdlets that no longer exist

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#709]
[Get-D365InstalledPackageOld](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/docs/Get-D365InstalledPackageOld.md) and [Get-D365LabelOld](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/docs/Get-D365LabelOld.md) should be removed since the cmdlets do not exist anymore.

**Comment by Splaxi** [comment]
You're right 🤓
