### ISSUE TITLE
:sparkles: New cmdlet(s) for ModuleToRemove.txt to uninstall a package

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#710]
It would be nice to have cmdlets available that would make the process of [uninstalling a package](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/uninstall-deployable-package) easier and automatable.

I propose two new cmdlets:
- **New-D365ModuleToRemove**: This would take a list of module names (would be nice if the output of [Get-D365Module](https://github.com/d365collaborative/d365fo.tools/blob/a118cd987938d47963b6279a8f6cdf76e6a46e3a/d365fo.tools/functions/get-d365module.ps1) could be used as input as well) and generate a ModuleToRemove.txt file according to the Microsoft documentation.
- **Add-D365ModuleToRemove**: This would take the file path of a ModuleToRemove.txt or the output of New-D365ModuleToRemove as well as the file path of a deployable package and add the ModuleToRemove.txt to the deployable package in the package/AOSService/Scripts folder.

I'm also thinking about adding a parameter to Add-D365ModuleToRemove to provide module names so it can internally create the ModuleToRemove.txt file. This way the user would not have to work with two but just one cmdlet.

While researching this idea, I came upon [How to add ModuleToRemove.txt to your package during MsDyn365FO build](https://msdyn365fo.wordpress.com/2020/12/02/how-to-add-moduletoremove-txt-to-your-package-during-msdyn365fo-build/) by @PaulHeisterkamp , which explores a similar idea and provides some PowerShell snippets to get started.

**Comment by Splaxi** [comment]
Awesome idea! 

Let's make it happen 💪

**Comment by FH-Inway** [comment]
The existing cmdlet [New-D365ISVLicense](https://github.com/d365collaborative/d365fo.tools/blob/c34e0fd70311f7b368c618f0a54c29a917428d53/d365fo.tools/functions/new-d365isvlicense.ps1) does basically the same thing as the proposed Add-D365ModuleToRemove cmdlet. I propose the logic gets refactored out into an internal function Add-FileToPackage, which could then be used by both cmdlets.

**Comment by FH-Inway** [comment]
Cmdlets [New-D365ModuleToRemove](https://github.com/d365collaborative/d365fo.tools/wiki/New-D365ModuleToRemove) and [Add-D365ModuleToRemove](https://github.com/d365collaborative/d365fo.tools/wiki/Add-D365ModuleToRemove) are available as part of d365fo.tools starting with version 0.6.78.
