### ISSUE TITLE
Start-LcsDatabaseRefreshV2. The remote server returned an error: (401)

### ISSUE THREAD

**Issue by kalejjanis** [d365collaborative/d365fo.tools#712]
Hello. For the past days I've been struggling with this issue that you can see in the image below.
AppRegistration permissions are set correctly. User even has Global Admin rights in Azure as well as Project Owner role in LCS project. No MFA. Tried different accounts.
Now I'm running out of ideas.
![image](https://user-images.githubusercontent.com/33128977/217252327-e79454dd-e6eb-4a56-9a78-cec5965bce85.png)

Another image:
![image](https://user-images.githubusercontent.com/33128977/217253733-7fe728e7-b03a-4eaf-a292-d3a64da3fc99.png)

Any hint would be very appreciated.

Note: In this scenario I wanted to test the DB refresh process between two Tier1 Cloud Hosted environments.

**Comment by FH-Inway** [comment]
As far as I know, LCS does not support DB refreshes for T1 environments.

**Comment by Splaxi** [comment]
@FH-Inway Is spot on!

Tier1 requires you to do the heavy lifting yourself. I can recommend using the dbatools.io to handle the backup and restore operations. You would have to move the .bak file between the Tier1 environments.

You can search the yammer forums, there you will see a highlevel description for how to approach this issue...

**Comment by Splaxi** [comment]
You can see it here:

https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1684189654646784
