### ISSUE TITLE
New Parameter for SqlPackage.exe

### ISSUE THREAD

**Issue by fhoo** [d365collaborative/d365fo.tools#719]
There is a new parameter added to SqlPackage.exe in the official documentation. Do we need to add this to the bacpac commandlets?

https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/commit/4fc06d9b3c440a3b40344a7a5e1bff58f75ffd33

**Comment by FH-Inway** [comment]
Thanks for keeping a watch on these changes.
In this case we were already made aware sometime ago of the new parameter and added it to the module.
See #695 and #692.

**Comment by fhoo** [comment]
Seems I have missed that 🙈. So I can go back to sleep 😴 and the issue can be closed. 
Thanks.
