### ISSUE TITLE
Cannot get  Token from LCS

### ISSUE THREAD

**Issue by kblacquiere** [d365collaborative/d365fo.tools#727]
Hello, I'm trying to call Get-D365LcsApiToken with -ClientId XXXX -UserName uuuuu -Password pppp -LcsApiUri https://lcsapi.lcs.dynamics.com .

But we are receiving : "invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.

 I know that the username password are good because I am login into LCS Web Portal and it works ClientID is also Good because We are using Upload Package using LCS in DEVOPS and everything works ...

But we had to change or script few months ago to use MSAL for authentication.

So, I suspect that we have the problem trying to authenticate with d365fo.tools becaue of MSAL ...

Am I right ?

Do you have an idea how to fix this ?

Thanks in advance for you help !

**Comment by Splaxi** [comment]
As late as yesterday, I was working with the Get-D365LcsApiToken myself. My version is: 0.6.77

**Comment by FH-Inway** [comment]
@kblacquiere Did you get this working? Or do you have further questions or comments on this?

**Comment by Splaxi** [comment]
Will close in 7 days if no new information is provided

**Comment by kblacquiere** [comment]
Hello, It is not working but we think it's because we are using an AD account that is coming from our on premise infrastructure. There is syncronization between On premise AD and Azure AD . We will try with a pure Azure Ad account and see if it make a difference. We will keep you posted. Thanks

**Comment by FH-Inway** [comment]
@Splaxi Could you close the issue?

@kblacquiere Did you get it to work with a pure Azure AD account? Feel free to post further information, even if we close the issue. Others might benefit from your experiences.
