### ISSUE TITLE
Suggestion: Command to deploy SSRS Report

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#73]
I always needs to search the K:\AosService\PackagesLocalDirectory\Plugins\AxReportVmRoleStartupTask\DeployAllReportsToSsrs.ps1

to 
Deploy a specific SSRS Report (by Name)
Deploy all SSRS report for a Model
Deploy All SSRS Reports

it will be usefull to have this command directly in our favorite D365Fo Tools :)

**Comment by Splaxi** [comment]
Great news Charles! Look at 0.5.9 for Publish-D365SsrsReport 🤘
