### ISSUE TITLE
d365fo.tools/d365fo.tools/internal/sql/set-bacpacvaluessql.sql Incorrect syntax if dbname include hypern

### ISSUE THREAD

**Issue by tfa-dk** [d365collaborative/d365fo.tools#741]
Error:

VERBOSE: [13:37:46][Get-SQLCommand] Building the SQL connection string.
[13:37:46][Set-SqlBacpacValues] Something went wrong while working against the database. | Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near '-'."
WARNING: [13:37:48][Set-SqlBacpacValues] Stopping because of errors. | Something went wrong while working against the database.

Solution
  Line 21: 	ALTER AUTHORIZATION ON database::@DATABASENAME TO sa
Change to:  	ALTER AUTHORIZATION ON database::[@DATABASENAME] TO sa -- Add brackets [ ] if dbname include hypern '-'

**Comment by Splaxi** [comment]
You could create a PR with it - then we could uptake it faster and release it to you 😉

**Comment by FH-Inway** [comment]
Thanks for reporting. In case we pick this up at a later time, I'm leaving the link to the line to change here.

https://github.com/d365collaborative/d365fo.tools/blob/1885fa33371d5b4bf545b85769f71c50c3ede389/d365fo.tools/internal/sql/set-bacpacvaluessql.sql#L21

**Comment by valerymoskalenko** [comment]
JFI. I have the following workaround. 
But it would be better to fix it in the PowerShell module

```
$NewDB = $($f.BaseName).Replace(' ','_'); #'AxDB_CTS1005BU2'  #Temporary Database name for new AxDB. Use a file name or any meaningful name.
$NewDB = $($f.BaseName).Replace('-','_'); #'AxDB_CTS1005BU2'  #Temporary Database name for new AxDB. Use a file name or any meaningful name.
```
