### ISSUE TITLE
EnableException flag on Import-D365Bacpac does not work

### ISSUE THREAD

**Issue by caleblanchard** [d365collaborative/d365fo.tools#750]
The EnableException flag, when on, should pass exception back through causing the cmdlet to return and error code, and for the Import-D365Bacpac cmdlet, it does not. I discovered this when we started getting errors about the AutoDrop property. Our data restore automation, was not failing on the right step like it should have.

**Comment by FH-Inway** [comment]
Thanks for reporting. Can you tell us more how [Import-D365Bacpac](https://github.com/d365collaborative/d365fo.tools/blob/4170454b237013b4df2538f89e2abc8b9a74fbb3/d365fo.tools/functions/import-d365bacpac.ps1) gets called and how the `EnableException` flag is enabled? Are you using the [Enable-D365Exception](https://github.com/d365collaborative/d365fo.tools/blob/4170454b237013b4df2538f89e2abc8b9a74fbb3/d365fo.tools/functions/enable-d365exception.ps1) cmdlet or the `EnableException` switch of `Import-D365Bacpac`?

Have you tried setting the `$WarningPreference` or `$ErrorActionPreference` PowerShell settings to `"Stop"`? See [Exception handling](https://github.com/d365collaborative/d365fo.tools/wiki/Exception-handling) for more information.

Could you also post the output of `Import-D365Bacpac` (ideally when called with the `-Verbose` switch) and the content of the `$Error` variable (gets automatically set by PowerShell) after the cmdlet was executed?

**Comment by FH-Inway** [comment]
@caleblanchard Do you have any more information on this?

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed.

@caleblanchard Feel free to reopen this issue or create a new one.
