### ISSUE TITLE
Invoke-D365DbSync: TableSyncException: Invalid SQL connection string

### ISSUE THREAD

**Issue by onikolaiev** [d365collaborative/d365fo.tools#754]
Invoke-D365DbSync -Verbose -ShowOriginalProgress throws an exception :
![image](https://github.com/d365collaborative/d365fo.tools/assets/10218336/4eb0bd9d-8bf6-4e46-bc46-6de9ec220f34)
Quick research led to the result: the issue happens when the axdbadmin password starts from the '='.
Enclosing a password to the single quotes did the trick.

from
invoke-d365dbsync:144 "-connect=`"server=$DatabaseServer;Database=$DatabaseName; User Id=$SqlUser;Password=$SqlPwd;`""
to
invoke-d365dbsync:144 "-connect=`"server=$DatabaseServer;Database=$DatabaseName; User Id=$SqlUser;Password='$SqlPwd';`""

**Comment by FH-Inway** [comment]
The fix is available in version 0.7.2. Let us know if this successfully fixed the issue or if you have further questions or comments.
