### ISSUE TITLE
Import bacpac from tier2 to tier1 cloudhosted Vms dont work

### ISSUE THREAD

**Issue by mff2022** [d365collaborative/d365fo.tools#758]
Hi 

I'm getting below error message.

I have installed latest version of D365 tools 0.7.1

[12:22:23][Invoke-Process] Error output was: \r\n *** Error importing database:Could not import package.
Warning SQL72020: The compatibility level of the source schema 160 is not supported, which may result in undefined behavior. Please upgrade to a later version which supports this compatibilit
y level.

WARNING: [12:22:23][Invoke-Process] Stopping because of Exit Code. | Stopping because an Exit Code from SqlPackage.exe wasn't 0 (zero) like expected.
[12:22:23][Invoke-SqlPackage] The SqlPackage.exe exited with an error.
WARNING: [12:22:23][Invoke-SqlPackage] Stopping because of errors.

Could it be that this VM don't have SQL Server 2022 installed ? just SQL Server 2019 that have 150 compatibility level.
@Splaxi

**Comment by FH-Inway** [comment]
Thanks for reporting. We are seeing quite a few issues in the last few months with bacpacs. If you have access, take a look at https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2450700740993024, where someone else has the exact same issue.

A similar issue is also discussed in #747, maybe one of the ideas there can help you as well.

The thought with SQL Server 2022 is very likely a good one. If you can, try to import the bacpac to a SQL Server 2022 database and let uns know the result.

**Comment by FH-Inway** [comment]
@mff2022 Hopefully you got your issue resolved. Feel free to post additional results and information or create new issues or discussions.

**Comment by mff2022** [comment]
Thanks for your help . I looked at the yammer thread and solved it https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=2450700740993024

**Comment by FH-Inway** [comment]
Thanks for the feedback. Consider closing this issue unless you have further questions.
