### ISSUE TITLE
Get-D365Module breaking change

### ISSUE THREAD

**Issue by gertvdh** [d365collaborative/d365fo.tools#764]
since the change  https://github.com/d365collaborative/d365fo.tools/commit/c8426182c100cc0884f5d723f0a6d1cbc494b660 
where 

 if ($InDependencyOrder -eq $true) {
            $modules = $modelManifest.ListModulesInDependencyOrder()
        }
        else {
            $modules = $modelManifest.ListModules()
        }

was changed to 

$modules = $metadataProviderViaRuntime.ModelManifest.ListModulesInDependencyOrder() 

we are having errors getting module information, in our case we do not want the dependency order, but it still tries it and fails.
Can we have the old if statement back or the try catch fallback?

**Comment by FH-Inway** [comment]
You are in luck, this particular issue is already fixed in the latest version 0.7.2, which was released 2 days ago. See also  https://github.com/d365collaborative/d365fo.tools/issues/753#issuecomment-1763032813

https://github.com/d365collaborative/d365fo.tools/blob/66147ce8312a6d215c5a70066b22595ad655485f/d365fo.tools/functions/get-d365module.ps1#L164-L169

**Comment by gertvdh** [comment]
unfortunately not, on line 146 there is still 

$modules = $metadataProviderViaRuntime.ModelManifest.ListModulesInDependencyOrder() 

it breaks for us here

**Comment by FH-Inway** [comment]
Ah, I see. That one uses the runtime provider, I wonder why/how it breaks. Could you provide the error details and the dependencies of your modules? 

One guess would be that you have a dependency in a compiled/binary module on an uncompiled module.

Easiest fix might be to add a try/catch fallback there as well.

cc @Splaxi @TrudAX

**Comment by gertvdh** [comment]
In our case we create a deployable package for a limit amount of modules, but these modules depend on other modules. The create package functionality doesn't care if every dependent module is there or not, it just creates the dp.
We use Get-D365Module to get the version numbers of those modules (for release note purposes). Because of these missing modules, the ListModulesInDependencyOrder fails, and I agree it should. 
But our way of working was working before the change. It simply got the version number of some modules, that's all. 
So I would suggest to also put the try catch here

**Comment by FH-Inway** [comment]
Understood. Will try to get the fix in place later this week, or you can propose it yourself.

**Comment by FH-Inway** [comment]
@gertvdh Thanks for the pr.

@Splaxi Any chance this can be released soon so we can unblock gertvdh?

**Comment by Splaxi** [comment]
20 mins from now... 0.7.3 contains the fixes.

**Comment by FH-Inway** [comment]
@gertvdh Could you close the issue?
