### ISSUE TITLE
New-D365Bacpag faling ( teste on 0.7.1 07.0.2 and 0.7.3 )

### ISSUE THREAD

**Issue by HC-Pin** [d365collaborative/d365fo.tools#769]
SQLpackage : sqlpackage-win7-x64-en-162.1.167.1 ( https://aka.ms/sqlpackage-windows )  

New-D365Bacpac -ExportModeTier1 -BackupDirectory $AXTempFolder -NewDatabaseName $AxSqlInstance  -BacpacFile $NewBackup -DiagnosticFile $AXExportLog 

Error:
Get-SQLCommand : A parameter cannot be found that matches parameter name 'EnableException'.
At line:4482 char:34
+     $sqlCommand = Get-SQLCommand @PsBoundParameters
+                                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-SQLCommand], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-SQLCommand
 
The property 'CommandText' cannot be found on this object. Verify that the property exists and can be set.
At line:4486 char:5
+     $sqlCommand.CommandText = $commandText
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
[09:24:29][Invoke-ClearSqlSpecificObjects] Something went wrong while clearing the SQL specific objects in the database. | You cannot 

call a method on a null-valued expression.
Write-PSFMessage : You cannot call a method on a null-valued expression.
At line:4499 char:9
+         Write-PSFMessage -Level Host -Message $messageString -Excepti ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [Write-PSFMessage], RuntimeException
    + FullyQualifiedErrorId : d365fo.tools_Invoke-ClearSqlSpecificObjects,PSFramework.Commands.WritePSFMessageCommand
 
You cannot call a method on a null-valued expression.
At line:4505 char:13
+             $sqlCommand.Connection.Close()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At line:4508 char:9
+         $sqlCommand.Dispose()
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Something went wrong while clearing the SQL specific objects in the database.
At C:\Program Files\WindowsPowerShell\Modules\PSFramework\1.9.310\PSFramework.psm1:5644 char:23
+         if (-not $Cmdlet) { throw $records[0] }
+                             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], Exception
    + FullyQualifiedErrorId : d365fo.tools_Invoke-ClearSqlSpecificObjects

**Comment by Splaxi** [comment]
@FH-Inway 

Could it be that you are taking to many of the outer parameters, via the @PsBoundParameters object?

**Comment by Splaxi** [comment]
@HC-Pin 

Can you look at this PR, to see if these changes will work for you?

https://github.com/d365collaborative/d365fo.tools/pull/770

**Comment by FH-Inway** [comment]
> @FH-Inway
> 
> Could it be that you are taking to many of the outer parameters, via the @PsBoundParameters object?

Are you maybe mixing this up with some other change I made? I don't think I changed any of the cmdlets involved, but maybe I'm missing something.

I think you are right, and #770 should address the immediate issue. However, I would recommend the same approach used in other cmdlets is implemented: Creating a new `$Params` instance that gets explicitely assigned the parameters that are to be used with `Get-SQLCommand`. E.g. how `Clear-D365TempDBTables` does it:

https://github.com/d365collaborative/d365fo.tools/blob/b57835bfa127ad67c983070575d8992ec8afb2d7/d365fo.tools/functions/clear-d365tempdbtables.ps1#L84-L88

Otherwise, once a new parameter gets added to one of the four cmdlets from #770 and that new parameter is not also a parameter for `Get-SQLCommand`, the same error will occur again.

**Comment by FH-Inway** [comment]
@HC-Pin New version 0.7.4 is out, check if it resolves your issue.

@Splaxi Thanks for the quick release.

**Comment by HC-Pin** [comment]
Works without:  #Enable-D365Exception -Verbose

![image](https://github.com/d365collaborative/d365fo.tools/assets/148760389/ad222511-a583-4f2b-ae72-b4ded40f5aa7)

**Comment by FH-Inway** [comment]
@HC-Pin Did you try the newest version with `Enable-D365Exception`? It should work there now as well.

**Comment by HC-Pin** [comment]
No did not test it with Enable-D365Exception
