### ISSUE TITLE
Invoke-D365InstallSqlPackage: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by python1898** [d365collaborative/d365fo.tools#771]
We use the function Invoke-D365InstallSqlPackage. Since a few days we get the error: Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
 
I found out that the issue comes from the following line of code in the function (line 76):
$content = (Invoke-WebRequest -Uri "[https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download"](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download%22) -UseBasicParsing).content
 
The issue is the usage of 'docs'. Changing 'docs' to 'learn' in the url solves the issue.

**Comment by FH-Inway** [comment]
Thanks for reporting, we will try to fix this as soon as possible. We are also happy to merge your pull request, if you want to fix it yourself.

**Comment by FH-Inway** [comment]
@python1898 New version 0.7.4 is out, check if it resolves the issue.
