### ISSUE TITLE
Checkin File to VSTS 

### ISSUE THREAD

**Issue by sanjay1913** [d365collaborative/d365fo.tools#78]
Hello ,

Can anyone help some powershell working code in CI to check-in a file to VSTS repository ?

Using below code have some issue
"is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
 spelling of the name, or if a path was included, verify that the path is correct and try again"

My repository "MyRepository" under "TempProject" project :
--------------------------------------------------------------------
https://xyz-Abc.visualstudio.com/TempProject/_git/MyRepository

$File = https://xyz-Abc.visualstudio.com/TempProject/_git/MyRepository/MyTempFile1

VSTS TF location:
-------------------
$TF = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe"

& $TF checkout $File 
& $TF checkin /noprompt /force /collection:"$File"

**Comment by Splaxi** [comment]
Are you capable of doing what you want in a standard command prompt? If not I would recommend that you start with that as a starter.

If you face issues with getting it to work you would have a great chance for success, either by looking at stackoverflow.com or affiliated sites for people that have done something similar. If you don't find a solution, then ask a question and see if they can help you out.

When things work out in command prompt, you can come back to us and we will have a greater chance of helping you.

**Comment by Splaxi** [comment]
No feedback received - issue will be closed based on the fact that question was somewhat out of the scope in regards to what the module is built to do.
