### ISSUE TITLE
Update Add-D365WindowsDefenderRules to a new VS2022 version

### ISSUE THREAD

**Issue by TrudAX** [d365collaborative/d365fo.tools#782]
Hi 
Can you please add xppcAgent.17.0.exe to the list of excluded files from Defender?

The sample file
_Add-MpPreference -ExclusionExtension @('*.md', '*.man', '*.xml', '*.xpp', '*.netmodule') -ExclusionPath @('E:\Git', 'C:\AOSService', 'C:\Logs') -ExclusionProcess @('AosDeploy.exe', 'testhost.exe', 'xppfagen.exe', 'sqlservr.exe', 'axsetup.exe', 'robocopy.exe', 'xppcagent.exe', 'git.exe', 'xppc.dll', 'xppcAgent.17.0.exe', 'labelc.exe', 'xppc.exe', 'devenv.exe', 'xppbp.exe', 'vstestconsole.exe', 'batch.exe', 'qtagent32.exe', 'qtagent32_40.exe', 'w3wp.exe', 'iisexpress.exe')_

See this comment from MFP for details 
https://www.linkedin.com/feed/update/urn:li:activity:7134859823606624257?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7134859823606624257%2C7134922327930085376%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7134859823606624257%2C7134936549766377474%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287134922327930085376%2Curn%3Ali%3Aactivity%3A7134859823606624257%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287134936549766377474%2Curn%3Ali%3Aactivity%3A7134859823606624257%29

**Comment by FH-Inway** [comment]
Good suggestion, I will look into that.

Also very nice report on your experience with a highend machine for x++ development!

> Put a breakpoint to SalesTable.init and attach to process: almost instant (2-3 seconds)

🤤

**Comment by FH-Inway** [comment]
I started work on this, see #783 
Seems that the paths for the Dynamics related executables got outdated at some point, I updated them as well.

I still have to look at the following executables and other exclusions from mfp:
AosDeploy.exe
axsetup.exe
robocopy.exe
git.exe
vstestconsole.exe
qtagent32.exe
qtagent32_40.exe
Extensions: *.md, *.man, *.xml, *.xpp, *.netmodule

**Comment by FH-Inway** [comment]
I ended up not including AosDeploy.exe and axsetup.exe from mfp's exclusions, because I couldn't find them on environments I have access to. Also did not include robocopy.exe because it is already listed in the exclusions, as is qtagent32.exe. The rest was added.

**Comment by TrudAX** [comment]
Maybe AosDeploy.exe and axsetup.exe are from the package installation, so normally they don't present.

**Comment by FH-Inway** [comment]
@TrudAX I had the same idea, but couldn't find those executables in a service update package contents. Internet search says that axsetup.exe is an AX 2012 thing, no mention of it for D365FO. And no mention of AosDeploy.exe at all.

**Comment by FH-Inway** [comment]
@TrudAX Just stumbled upon the following comment in the web.config file: 
`<!--These are the default onebox values. These will be overwriten by values in oneboxconfig.xml in AosDeploy.exe-->`
Seems like AosDeploy.exe is used in creating one box environments.
