### ISSUE TITLE
Set-D365FavoriteBookmark doesn't work on Windows Server 2022 due to missing IE

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#787]
Set-D365FavoriteBookmark doesn't work on Windows Server 2022 due to missing IE
Tested on version 10.0.37 on the local VHD.
This image is based on Windows Server 2022 Datacenter Evaluation, where IE is not installed.
I believe that it is possible to do the same for the Edge browser.

Logs:
```
PS C:\Windows\system32> $FnOURL = Get-D365Url

PS C:\Windows\system32> $FnOURL

Url                                                
---                                                
https://usnconeboxax1aos.cloud.onebox.dynamics.com/

PS C:\Windows\system32> Set-D365FavoriteBookmark -Url $FnOURL.Url -D365FO -Verbose -Debug
VERBOSE: [22:58:04][Set-D365FavoriteBookmark] Setting the show bar and lock bar registry values.
DEBUG: 30790 | [22:58:04][Set-D365FavoriteBookmark] Setting the show bar and lock bar registry values.
Set-ItemProperty : Cannot find path 'HKCU:\Software\Microsoft\Internet Explorer\MINIE\' because it does not exist.
At line:30791 char:9
+         Set-ItemProperty -Path $pathShowBar -Name $propShowBar -Value ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKCU:\Software\...Explorer\MINIE\:String) [Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
```

Please find some helpful links here:
- General information https://learn.microsoft.com/en-us/deployedge/edge-learnmore-provision-favorites
- https://superuser.com/questions/1002351/add-bookmarks-to-microsoft-edge-manually
- https://community.spiceworks.com/topic/2461967-powershell-to-import-bookmarks-edge-chrome

**Comment by FH-Inway** [comment]
Thanks for the reminder, we wanted to do this in #587 , but at the time, Edge was not already preinstalled on all environment types. Seems that is now the case, so we could start work on it.

**Comment by Splaxi** [comment]
Let's crack it - and support FireFox / Chrome and Edge at the same time.

I'll take this one on me...

**Comment by Splaxi** [comment]
This is part of the 0.7.7 release. Will be available later today...
