### ISSUE TITLE
Upload bacpac file to LCS asset library issue

### ISSUE THREAD

**Issue by nagsworld** [d365collaborative/d365fo.tools#788]
Hello,
 
I am trying to upload the .bacpac file from my local drive to LCS asster library, and I am end with an error which does not have much details. Please help if anybody have solutions. Please let me know if any further questions.
 
_Here is the error I am receiving on console:_
[17:15:56][Start-LcsUploadV2] Something went wrong while working against the LCS API. | Response status code does not indicate success: 500 (Internal Server Error).
WARNING: [17:15:56][Start-LcsUploadV2] Stopping because of errors

_**Source code;**_
$LcsApiUri = "https://lcsapi.lcs.dynamics.com"
[int]$ProjectId = 1666824
$BearerToken = "Bearer $($TokenResponse.access_token)"  -- Getting token it right...
$LocalPath = "D:\bacpac\sivatestbackup.bacpac"	
#$FileType = "SoftwareDeployablePackage"	 
$FileType = "ProcessDataPackage"	 
try
{	 
    
  
    
    #Get-PSFMessage -Level Verbose | Write-Host
	Invoke-D365LcsUpload -ProjectId $ProjectId `
     -BearerToken $BearerToken `
     -FilePath $LocalPath `
     -LcsApiUri $LcsApiUri `
     -FileType $FileType `
     -FileName "ReadyForTesting" `
     -FileDescription "testing file upload" `
     -RetryTimeout "02:00:30" 
    #Get-PSFMessage -Level Verbose | Write-Host
    #(Get-D365EnvironmentSetting).Aos
}
catch {
    $formattedDateTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "Error occurred while uploading file to asset library tatus: $_ at:  current time = $formattedDateTime"
    return "Failed"
}

**Comment by FH-Inway** [comment]
Thanks for reporting. "Internal server error" indicates that the issue was with the LCS service itself. Is this the first time the upload is being done? Or did it work before?

According to https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2564964316397568 there seems to have been an LCS outage yesterday. Maybe try again to check if it was an intermittent issue and works now?

**Comment by FH-Inway** [comment]
See also discussion #614 

I just noticed you try to upload the .bacpac file to file type "ProcessDataPackage". I wouldn't expect that part of the asset library to accept database backups. As mentioned in the discussion, it may very well be that Microsoft does not allow uploads of database backups of any kind to the asset library.

**Comment by nagsworld** [comment]
> Thanks for reporting. "Internal server error" indicates that the issue was with the LCS service itself. Is this the first time the upload is being done? Or did it work before?
> 
> According to https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2564964316397568 there seems to have been an LCS outage yesterday. Maybe try again to check if it was an intermittent issue and works now?

Thanks for your reply. I have tried just now but still I am witnessing the same issue.

**Comment by nagsworld** [comment]
> See also discussion #614
> 
> I just noticed you try to upload the .bacpac file to file type "ProcessDataPackage". I wouldn't expect that part of the asset library to accept database backups. As mentioned in the discussion, it may very well be that Microsoft does not allow uploads of database backups of any kind to the asset library.

HI Thanks for your reply,

it was not allowed with .bak file, but with below url, it was working with bacpac file.

https://community.dynamics.com/forums/thread/details/?threadid=3fd87fcd-3d08-4fdd-b388-4a7d834b0e4f

**Comment by Splaxi** [comment]
@nagsworld 

The tools are only a wrapper around the official API that is exposed in the LCS platform. From the initial release of the API and the tools, the list of supported files have changed.

Below image shows what the tools support, based on the API in LCS:
![image](https://github.com/d365collaborative/d365fo.tools/assets/8750181/37d1f26c-10bc-4a47-83c9-22583953c21b)

I never personally used the "ProcessDataPackage" option - and I don't even know what menu item in maps to in LCS:
![image](https://github.com/d365collaborative/d365fo.tools/assets/8750181/73671fe1-a647-4297-90a4-e55b4c2cfb2d)

I did read the link - but nowhere could I see any reference bak / bacpac. I seems that the post is handling SoftwareDeployablePackages / zip files - which is a very common usecase, that I even personally are using everyday.

I would argue, that you should try to download any SoftwareDeployablePackage from the Asset Library - and simply upload it again with a new name. That way you know that all the moving parts are working.

When things are failing in PowerShell - you could try to type the following command:
```
$error
```

And look into the details, if any, is stored in the variable.

**Comment by Jnagasuresh** [comment]
Hi Splaxi,

Thanks for the reply.
I have tried even with package type "SoftwareDeployablePackage" and I am witnessing the same response.

**Comment by Splaxi** [comment]
Then I would argue that you need to step even further back in the analysis of your access for the LCS api.

A simple test is as follows:
```PowerShell
Get-D365LcsApiToken -Username 'ABC@contoso.com' -Password 'ThisIsAPassword' -ClientId '1f68ab91-550e-4766-858f-cc0627bf995c' -LcsApiUri 'https://lcsapi.lcs.dynamics.com' | Set-D365LcsApiConfig -LcsApiUri 'https://lcsapi.lcs.dynamics.com' -ClientId '1f68ab91-550e-4766-858f-cc0627bf995c' -ProjectId '123456789' -Temporary 
Get-D365LcsEnvironmentMetadata
```

This is the most basic way to ensure that you have all the needed details in place:
Username + Password
Registered Application (ClientId)
Correct LCS GEO (There are 6+ different endpoint across the world)

If the above fails - the `$error` will output details that should get you on the right track on what is missing.

**Comment by nagsworld** [comment]
> Then I would argue that you need to step even further back in the analysis of your access for the LCS api.
> 
> A simple test is as follows:
> 
> ```powershell
> Get-D365LcsApiToken -Username 'ABC@contoso.com' -Password 'ThisIsAPassword' -ClientId '1f68ab91-550e-4766-858f-cc0627bf995c' -LcsApiUri 'https://lcsapi.lcs.dynamics.com' | Set-D365LcsApiConfig -LcsApiUri 'https://lcsapi.lcs.dynamics.com' -ClientId '1f68ab91-550e-4766-858f-cc0627bf995c' -ProjectId '123456789' -Temporary 
> Get-D365LcsEnvironmentMetadata
> ```
> 
> This is the most basic way to ensure that you have all the needed details in place: Username + Password Registered Application (ClientId) Correct LCS GEO (There are 6+ different endpoint across the world)
> 
> If the above fails - the `$error` will output details that should get you on the right track on what is missing.
> 
> To be perfectly clear, you will have to replace **ALL** values for Username, Password, ClientId and ProjectId - you **MIGHT** need to utilize another LcsApiUri value than the one mentioned in the above examples.
---------------------------
Thank you so much for your time.

I tried the command you have added in above comment and I am able to execute the command Get-D365LcsApiToken with out any errors.

**Comment by Splaxi** [comment]
What about the `Get-D365LcsEnvironmentMetadata` ?

**Comment by nagsworld** [comment]
it was returning the existing environments to the console.

**Comment by Splaxi** [comment]
Closing this - as the LCS API doesn't support bacpac / bak files upload....
