### ISSUE TITLE
Move database from one env to another

### ISSUE THREAD

**Issue by mahaGokulChow** [d365collaborative/d365fo.tools#792]
****Can we automate the below steps using powershell ?**

Open an internet browser and connect to https://lcs.dynamics.com/.
Log into your account.
Open the project that represents the client system.
On the right side of the project screen, you will find all the tier 2 (or higher) environments.
Select “Full Details” for the environment you want to create the BACPAC file.
Select the menu option “Maintain”, then select “Move Database”.
Select “Import database”.
Select the BACPAC to be imported. This must be in the LCS project asset library under the “database backup”.
Once the process is complete, your import will be complete.

**Comment by Splaxi** [comment]
The tools supports the following:

* Invoke data refresh from PROD -> Tier2
* Invoke Bacpac generation from Tier2
* Invoke data refresh from Tier2 -> Tier2
