### ISSUE TITLE
:sparkles: Add Get-D365RsatSelfServiceCertificates cmdlet

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#800]
I could have sworn we already had this, but I could not find it. So I propose we add a new cmdlet to download the RSAT certificates from LCS as per https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/api/v1/reference-download-rsat-certificate

Ideally, the result can be piped directly to Import-D365RsatSelfServiceCertificates.

Current request for this: https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2251869006061568

**Comment by Splaxi** [comment]
L F G !

I'm all in for getting this done ASAP 🤘

**Comment by Splaxi** [comment]
I have a working initial version done 🔥

**Comment by Splaxi** [comment]
0.7.8

**Comment by FH-Inway** [comment]
@Splaxi I fixed a minor copy&paste issue in the documentation in #803 
Also added what I believe should enable piping the result of Get-D365LcsEnvironmentRsatCertificate into Import-D365RsatSelfServiceCertificates. Could you check if that works? Unfortunately, I currently do not have access to credentials to test it myself.

**Comment by Splaxi** [comment]
I'll take a leap of faith - and did the merge. Will release later today.

Let's fix the issues, if any, when someone hits them later down the road...

**Comment by FH-Inway** [comment]
Version with fixed piping now available in 0.7.10
