### ISSUE TITLE
Error Invoke-TimeSignal -Start

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#81]
In 8.1 AZURE Build Template VM, i get an error when i try to install a package with devInstall Mode

After analyzing, the problem is due to the d365fo.tools.psm1

> $importIndividualFiles is equals to "False"

so we do not execute "internal\scripts\postimport.ps1" (and so variable.ps1) and we execute the "resourcesAfter.ps1" witch not initialize $Script:TimeSignals value as Array

install command :
Install-Module D365Fo.Tools -Scope CurrentUser

PS C:\Users\Useraa908749a79> Invoke-D365SDPInstall -DevInstall -Path .\AXDeployableRuntime1\ -
Verbose
You cannot call a method on a null-valued expression.
At line:1721 char:13
+         if ($Script:TimeSignals.ContainsKey($Command)) {
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Splaxi** [comment]
Great find Charles!

I missed a minor thing in my new build pipeline. Building the next release as we speak.

**Comment by Splaxi** [comment]
Please try again

**Comment by Shind44** [comment]
Mötz,
after updating the Tools , all working fine 

Thanks
