### ISSUE TITLE
Invoke-D365DBSync / Catch error when synchronization went wrong on DevOps

### ISSUE THREAD

**Issue by MatthieuHz** [d365collaborative/d365fo.tools#819]
Hello !
We faced the LICENSING_POPULATEROLEPRIVILEGELICENSEMAPV2 procedure issue due to 10.0.39 update.
On DB synchronization, it just crashed
![image](https://github.com/d365collaborative/d365fo.tools/assets/15634271/e93250c7-6219-439d-8e2d-dd5d4e4d7ee8)
but the step is correct 
![image](https://github.com/d365collaborative/d365fo.tools/assets/15634271/d96c8b73-f349-4178-bd74-39f764f467f8)
Can we have the possibility to throw on error with the Invoke-D365DBSync function ?
Thank you very much
Matthieu

**Comment by FH-Inway** [comment]
Hi @MatthieuHz , take a look at our guidance on [exception handling](https://github.com/d365collaborative/d365fo.tools/wiki/Exception-handling). Let us know if this is helpful or does not help in your case.

**Comment by FH-Inway** [comment]
@MatthieuHz Hopefully the exception guidance was helpful to you. I'm closing the issue, but feel free to add more comments and we can reopen it.
