### ISSUE TITLE
Service Drive variable is missing on the new 10.0.39 VMs #829

### ISSUE THREAD

**Issue by torbennehmer** [d365collaborative/d365fo.tools#830]
Apparently, the new 10.0.39 VMs released yesterday do no longer have a SERVICEDRIVE environment variable, it is just missing. D365fo.tools then throws the expected error:

![image](https://github.com/d365collaborative/d365fo.tools/assets/2812067/e7b53acb-aa46-4f72-8283-70bf9e699d69)

As C: is a sane default on the Hyper V machines, the fallback works well, the main problem seems to be the recurring error message for the time being.

**Comment by FH-Inway** [comment]
@torbennehmer Thanks for reporting. I've let Microsoft know about it on [Yammer](https://www.yammer.com/dynamicsaxfeedbackprograms/threads/2806774839508992). Hopefully they can fix it along with the other issues of the 10.0.39 VHD.

I do not think we need a change for d365fo.tools to address this. As you already mentioned, it has a sane default and actionable message in case the user wants to get rid of the message.

**Comment by Splaxi** [comment]
@FH-Inway 

Any next steps?

**Comment by FH-Inway** [comment]
@Splaxi Not from my side at the moment. I was hoping Microsoft would fix this, but they mentioned in Yammer that further changes would be done on the next version of the VHD. So we can either close this issue or leave it open and check again once the next VHD version is available.
