### ISSUE TITLE
File Description not correctly set in LCS Asset upload

### ISSUE THREAD

**Issue by ismits** [d365collaborative/d365fo.tools#839]
$jsonDescription does not seem to be defined:

https://github.com/d365collaborative/d365fo.tools/blame/bb5322572562871b9c834d44458f9824238ded57/d365fo.tools/internal/functions/start-lcsuploadv2.ps1#L126

**Comment by ismits** [comment]
Additionally, it looks like the Token is not correctly referenced.

**Comment by Splaxi** [comment]
Good spot!

**Comment by ismits** [comment]
PR created: https://github.com/d365collaborative/d365fo.tools/pull/840

**Comment by FH-Inway** [comment]
Thanks again for the contribution! Released it in version [0.7.14](https://github.com/d365collaborative/d365fo.tools/releases/tag/0.7.14).
