### ISSUE TITLE
Issue with Last Version

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#85]
Mötz

i have a lot of issue with the last update of D365 Tools

> Import-D365BacPac
> Stop-D365Environnement
> Start-D365Environnement

each Time parameter binding seems to be KO

PS C:\> Import-D365Bacpac -ImportModeTier1 -DatabaseServer localhost -BacpacFile "C:\MSSQL_BACKUP\
RENCE\AxDB_REFERENCE.bacpac" -NewDatabaseName "AxDb" -Verbose
Test-PathExists : A parameter cannot be found that matches parameter name 'PathType'.
At line:6541 char:49
+     if (-not (Test-PathExists -Path $BacpacFile -PathType Leaf)) {
+                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-PathExists], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-PathExists

VERBOSE: [07:31:16][Test-TrustedConnection] Capabilities based on the centralized logic in the psm1 file.
VERBOSE: [07:31:16][Import-D365Bacpac] Testing if we are working against a Tier2 / Azure DB
Get-DeepClone : Cannot process argument transformation on parameter 'InputObject'. Cannot convert the "AxDB" value o
type "System.String" to type "System.Collections.Hashtable".
At line:458 char:46
+                 $clone[$key] = Get-DeepClone $InputObject[$key]
+                                              ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DeepClone], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DeepClone

Get-DeepClone : Cannot process argument transformation on parameter 'InputObject'. Cannot convert the "localhost"
value of type "System.String" to type "System.Collections.Hashtable".
At line:458 char:46
+                 $clone[$key] = Get-DeepClone $InputObject[$key]
+                                              ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DeepClone], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DeepClone

Get-DeepClone : Cannot process argument transformation on parameter 'InputObject'. Cannot convert the "axdbadmin"
value of type "System.String" to type "System.Collections.Hashtable".
At line:458 char:46
+                 $clone[$key] = Get-DeepClone $InputObject[$key]
+                                              ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DeepClone], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DeepClone

Get-DeepClone : Cannot process argument transformation on parameter 'InputObject'. Cannot convert the "AOSWebSite@12
value of type "System.String" to type "System.Collections.Hashtable".
At line:458 char:46
+                 $clone[$key] = Get-DeepClone $InputObject[$key]
+                                              ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DeepClone], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DeepClone

VERBOSE: [07:31:16][Import-D365Bacpac] Start importing the bacpac with a new database name and current settings
VERBOSE: [07:31:16][Test-PathExists] Testing the path: C:\Program Files (x86)\Microsoft SQL
Server\140\DAC\bin\SqlPackage.exe
VERBOSE: [07:31:16][Invoke-SqlPackage] Starting to prepare the parameters for sqlpackage.exe
VERBOSE: [07:31:16][Invoke-SqlPackage] Start sqlpackage.exe with parameters
*** Argument 'TargetServerName' has an invalid value: ''.
VERBOSE: [07:31:17][Invoke-SqlPackage] Total time spent inside the function was 00:00:01.0533910
VERBOSE: [07:31:17][Import-D365Bacpac] Importing completed
VERBOSE: [07:31:17][Import-D365Bacpac] Start working on the configuring the new database
VERBOSE: [07:31:17][Import-D365Bacpac] Building sql statement to update the imported SQL database

**Comment by Splaxi** [comment]
Should be fixed in the 0.4.54 release

**Comment by Shind44** [comment]
Failed again in 0.4.54 release

18-10-18T12:08:22.7559600Z VERBOSE: [12:08:22][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
2018-10-18T12:09:22.8428589Z VERBOSE: [12:09:22][Invoke-AzureBackupRestore] Total time spent inside the function was 00:04:00.7168779
2018-10-18T12:09:22.9498642Z New-D365Bacpac : A parameter cannot be found that matches parameter name 'or'.

**Comment by Splaxi** [comment]
Could you share all the parameters that you use?

**Comment by Splaxi** [comment]
I can test on my own Tier2 tonight.

So we get some insights.

**Comment by Splaxi** [comment]
Please remember to update to latest version before you test again :)

**Comment by Shind44** [comment]
of course :) i have a script with update-module on all always have the latest version

**Comment by Splaxi** [comment]
Just making sure 😎

**Comment by Splaxi** [comment]
Hi Charles!

7.3 - Tier2 environment 

`New-D365Bacpac -ExportModeTier2 -SqlUser "sqladmin" -SqlPwd "TOPSECRET" -Verbose`

Just started it.

So I would say it works - let me know what happens in you end of the world 🤔

**Comment by Shind44** [comment]
Hi Mötz,
this morning, all working fine !

Thanks

**Comment by Splaxi** [comment]
Well then we will close this issue
