### ISSUE TITLE
Issues running New-D365Bacpac in version 0.4.54

### ISSUE THREAD

**Issue by jan-jonas** [d365collaborative/d365fo.tools#89]
Hi,
I'm having issues running the New-D365Bacpac command in version 0.4.54 of your tools.

When using the following syntax (as written in your documentation):
New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseName AxDB -SqlUser "..." -SqlPwd "..." -BackupDirectory C:\Temp\ -NewDatabaseName Testing1 -BacpacFile C:\Temp\test.bacpac 

I get the following error:
New-D365Bacpac : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-D365Bacpac], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-D365Bacpac

I'm wondering why I need the parameters SqlUser and SqlPwd when creating a bacpac file on a T1 environment as it should work with trusted connection.

If I leave out the parameters and run:

New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseName AxDB -BackupDirectory C:\Temp\ -NewDatabaseName Testing1 -BacpacFile C:\Temp\test.bacpac

The command seems to do something (a new window opens and closes) and I get the following output:

[07:53:38][Invoke-SqlBackupRestore] Something went wrong while working against the database | Exception calling "Open" with "0" argument(s): "Login failed for user ''."
Stop-PSFFunction : A parameter cannot be found that matches parameter name 'StepsUpward'.
At line:1540 char:64
+ ... Stop-PSFFunction -Message "Stopping because of errors" -StepsUpward 1
+                                                            ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Stop-PSFFunction], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Stop-PSFFunction
 
Test-PSFFunctionInterrupt : A parameter cannot be found that matches parameter name 'or'.
At line:8382 char:43
+             if (Test-PSFFunctionInterrupt -or (-not $res)) { return }
+                                           ~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-PSFFunctionInterrupt], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-PSFFunctionInterrupt
 
[07:53:38][Invoke-ClearSqlSpecificObjects] Something went wrong while working against the database | Exception calling "Open" with "0" argument(s): "Login failed for user ''."
Stop-PSFFunction : A parameter cannot be found that matches parameter name 'StepsUpward'.
At line:1435 char:64
+ ... Stop-PSFFunction -Message "Stopping because of errors" -StepsUpward 1
+                                                            ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Stop-PSFFunction], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Stop-PSFFunction
 
Test-PSFFunctionInterrupt : A parameter cannot be found that matches parameter name 'or'.
At line:8390 char:43
+             if (Test-PSFFunctionInterrupt -or (-not $res)) { return }
+                                           ~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-PSFFunctionInterrupt], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-PSFFunctionInterrupt
 
Exception calling "set_Login" with "1" argument(s): "Cannot apply value 'null' to property Login: Value cannot be null.."
At line:8689 char:9
+         $srv.ConnectionContext.set_Login("$SqlUser")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidPropertyValueException
 

File                Filename   
----                --------   
C:\Temp\test.bacpac test.bacpac

Could you please point me to the right direction to create a bacpac file on a T1 environment. Thanks in advance!

**Comment by Shind44** [comment]
I get the same error (in 0.4.52 too)

**Comment by Shind44** [comment]
and event if we set the SQLLogin et SQLPassword to command we have the same issue



PS C:\TFS_DEPLOY_AGENT> New-D365Bacpac -ExportModeTier2 -DatabaseServer XXXXXX-appdbserver-e15fafb1.database.windows.net -DatabaseName XXXX_axdb_4fc6f9ab2dd5fdd9 -SqlUser sqladmin -SqlPwd "password" -BacpacFile C:\Temp\Bacpac\AxDB_REFERENCE.bacpac
-verbose
VERBOSE: [08:35:58][Test-TrustedConnection] Not capable of using Trusted Connection based on Tier validation.
VERBOSE: [08:35:58][Test-PathExists] Testing the path: C:\Temp\Bacpac
VERBOSE: [08:35:58][New-D365Bacpac] Invoking the Tier 2 - Creation of Azure DB copy
VERBOSE: [08:35:58][Get-SQLCommand] Building the SQL connection string.
VERBOSE: [08:35:58][Invoke-AzureBackupRestore] Will execute the following command: CREATE DATABASE [XXXXX_axdb_4fc6f9ab2dd5fdd9_export] AS COPY OF [XXXXX_axdb_4fc6f9ab2dd5fdd9]
VERBOSE: [08:36:58][Get-SQLCommand] Building the SQL connection string.
VERBOSE: [08:36:58][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [08:37:58][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [08:38:58][Invoke-AzureBackupRestore] Waiting for the creation of the copy.
VERBOSE: [08:39:58][Invoke-AzureBackupRestore] Total time spent inside the function was 00:04:00.5693086
Test-PSFFunctionInterrupt : A parameter cannot be found that matches parameter name 'or'.
At line:8420 char:43
+             if (Test-PSFFunctionInterrupt -or (-not $res)) { return }
+                                           ~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-PSFFunctionInterrupt], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-PSFFunctionInterrupt

VERBOSE: [08:39:58][New-D365Bacpac] Invoking the Tier 2 - Clear Azure DB objects
VERBOSE: [08:39:58][Get-SQLCommand] Building the SQL connection string.
Test-PSFFunctionInterrupt : A parameter cannot be found that matches parameter name 'or'.
At line:8427 char:43
+             if (Test-PSFFunctionInterrupt -or (-not $res)) { return }
+                                           ~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-PSFFunctionInterrupt], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-PSFFunctionInterrupt

VERBOSE: [08:40:01][New-D365Bacpac] Invoking the Tier 2 - Export of the bacpac file from Azure DB
VERBOSE: [08:40:01][Test-PathExists] Testing the path: C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe
VERBOSE: [08:40:01][Invoke-SqlPackage] Starting to prepare the parameters for sqlpackage.exe
VERBOSE: [08:40:01][Invoke-SqlPackage] Start sqlpackage.exe with parameters
Connecting to database 'xxxx_axdb_4fc6f9ab2dd5fdd9_export' on server 'xxxxx-appdbserver-e15fafb1.database.windows.net'.
Extracting schema
Extracting schema from database

**Comment by jan-jonas** [comment]
@Splaxi Thanks for the update. Please also consider updating the documentation as it seems to be outdated. I will test the fix in our environment as soon as you have released a new version or provided any other fix for the issue.

**Comment by Splaxi** [comment]
We did release a new version. 

The refactor merge we just did, should start enabling us to leverage some automation on the documentation side. We are doing our best we can.

For now always run the get-help for a cmdlet when in doubt. You still might find issues and that is were we need you guys to help us report it.

**Comment by jan-jonas** [comment]
@Splaxi: I still have problems to run the command after upgrading to version 0.4.58:

Command (without credentials):
New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseName AxDB -BackupDirectory C:\Temp\ -NewDatabaseName Testing1 -BacpacFile C:\Temp\test.bacpac

Result:
[07:56:19][Invoke-SqlBackupRestore] Something went wrong while working against the database | Exception calling "Open" with "0" argument(s): "Login failed for user ''."
WARNING: [07:56:20][Invoke-SqlBackupRestore] Stopping because of errors

Command (with credentials):
New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseName AxDB -SqlUser axdbadmin - SqlPwd "[...]" -BackupDirectory C:\Temp\ -NewDatabaseName Testing1 -BacpacFile C:\Temp\test.bacpac

Result:
New-D365Bacpac : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ New-D365Bacpac -ExportModeTier1 -DatabaseServer localhost -DatabaseNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-D365Bacpac], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-D365Bacpac


What I still do not understand completely is if I need to provide credentials when running a backup on a T1 machine with a local sql server as trusted connection should work here..,

**Comment by Splaxi** [comment]
The error is unable to logon on the SQL Server connection. That indicates thing about what Tier1 box you have.

Where is that Tier1 running? 

-Local VM (downloaded VHD) ?
-Azure VM (deployed through LCS) ?
-Microsoft hosted (brought through the subscription) ?

On a Tier1 - you should only have to use the following command

`New-D365Bacpac -ExportModeTier1`

The rest is then defaulted.

Want to pick the location of the exported bacpac file, this should work.

`New-D365Bacpac -ExportModeTier1 -BacpacFile C:\Temp\test.bacpac`

If that doesn't work we need to look into what gets loaded with 

`Get-PSFMessage -Level Verbose`

**Comment by Splaxi** [comment]
Could you share the results from

Get-D365ProductInformation

**Comment by jan-jonas** [comment]
Sure. Running "Get-D365ProductInformation" shows:

ProductVersion          : 7.0
ProductBuildVersion     : 7.0.4841.41291
ProductBuildBranch      : platprodrel
PlatformVersion         : Update15
PlatformBuildVersion    : 7.0.4841.41291
PlatformBranch          : platprodrel
ApplicationVersion      : 7.3
ApplicationBuildVersion : 7.3.11971.64790
ApplicationBranch       : App73
ProductRegisteredName   : Microsoft Dynamics 365 for Finance and Operations

**Comment by Splaxi** [comment]
Please exit all open powershell consoles.

Depending on if you installed the module with or without -Scope, please update the module, you have to start a PowerShell console the same way and update the module.

`Update-Module d365fo.tools -Force`

`Import-Module d365fo.tools -Force -PassThru`

And then try again 🤞

**Comment by jan-jonas** [comment]
Seems to run now. Thanks!

**Comment by Splaxi** [comment]
Thanks for reporting the issue and even more for the patience 😋

**Comment by Shind44** [comment]
I add the "Import-Module d365fo.tools -Force -PassThru" command in my automation script after update the module

maybe not running the latest version
